let dataAM = [
  {
    anoCenso: 2013,
    cod: 13084860,
    nome: "ALDEIA DO CONHECIMENTO PROFA RUTH PRESTES GONCALVES",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 473.1340026855469,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13025104,
    nome: "CEJA PROF AGENOR FERREIRA LIMA",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13096605,
    nome: "CEJA PROFESSOR PAULO FREIRE",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13083708,
    nome: "CEJA PROFESSORA JACIRA CABOCLO",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13100580,
    nome: "CENTRO DE ECUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1302801,
    cidade: "MARAA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13093851,
    nome: "CENTRO DE ECUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1303700,
    cidade: "SANTO ANTONIO DO ICA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13098055,
    nome: "CENTRO DE EDUC PROF PE STELIO DALISO - CETAM",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089862,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1302504,
    cidade: "MANACAPURU",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089870,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1301001,
    cidade: "CARAUARI",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094238,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1303106,
    cidade: "NOVA OLINDA DO NORTE",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089889,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1300706,
    cidade: "BOCA DO ACRE",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089897,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1301704,
    cidade: "HUMAITA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089900,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1301407,
    cidade: "EIRUNEPE",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094270,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1302553,
    cidade: "MANAQUIRI",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089919,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1304005,
    cidade: "SILVES",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089927,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1301902,
    cidade: "ITACOATIARA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089986,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1301209,
    cidade: "COARI",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13090011,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS",
    codCidade: 1301506,
    cidade: "ENVIRA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13096451,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1300201,
    cidade: "ATALAIA DO NORTE",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094408,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1300680,
    cidade: "BOA VISTA DO RAMOS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13096460,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1301605,
    cidade: "FONTE BOA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094416,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1303536,
    cidade: "PRESIDENTE FIGUEIREDO",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094424,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1300607,
    cidade: "BENJAMIN CONSTANT",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094432,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1301308,
    cidade: "CODAJAS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094440,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1301803,
    cidade: "IPIXUNA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094459,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1303205,
    cidade: "NOVO AIRAO",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094467,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1304104,
    cidade: "TAPAUA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094475,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1301852,
    cidade: "IRANDUBA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094483,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1300300,
    cidade: "AUTAZES",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094246,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1303007,
    cidade: "NHAMUNDA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094254,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1300839,
    cidade: "CAAPIRANGA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13295217,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1303908,
    cidade: "SAO PAULO DE OLIVENCA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094262,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1300086,
    cidade: "ANAMA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089935,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1303809,
    cidade: "SAO GABRIEL DA CACHOEIRA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094289,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1302009,
    cidade: "ITAPIRANGA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089943,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1304203,
    cidade: "TEFE",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094297,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1302405,
    cidade: "LABREA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094300,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1301951,
    cidade: "ITAMARATI",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089951,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1304062,
    cidade: "TABATINGA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089960,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1302900,
    cidade: "MAUES",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094319,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1304302,
    cidade: "URUCARA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089978,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1302702,
    cidade: "MANICORE",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094335,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1303601,
    cidade: "SANTA ISABEL DO RIO NEGRO",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094343,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1303502,
    cidade: "PAUINI",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13089994,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1303403,
    cidade: "PARINTINS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094351,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1304401,
    cidade: "URUCURITUBA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13099248,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1302207,
    cidade: "JURUA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094386,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1301100,
    cidade: "CAREIRO",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13094394,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS - CETAM",
    codCidade: 1300904,
    cidade: "CANUTAMA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13093894,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1300805,
    cidade: "BORBA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13097741,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1304260,
    cidade: "UARINI",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13093908,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1300029,
    cidade: "ALVARAES",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13093827,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1302306,
    cidade: "JUTAI",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13093835,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1303569,
    cidade: "RIO PRETO DA EVA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13093843,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1301654,
    cidade: "GUAJARA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13093860,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1303957,
    cidade: "SAO SEBASTIAO DO UATUMA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13093878,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1300144,
    cidade: "APUI",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13093886,
    nome: "CENTRO DE EDUCACAO TECNOLOGICA DO AMAZONAS CETAM",
    codCidade: 1300409,
    cidade: "BARCELOS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13162209,
    nome: "CENTRO DE EDUCACAO TECNOLOGICO DO AMAZONAS",
    codCidade: 1302108,
    cidade: "JAPURA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13095714,
    nome: "CENTRO DE FORMACAO PROFISSIONAL PE JOSE ANCHIETA",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13044133,
    nome: "CENTRO EDUCACIONAL 27 DE JULHO",
    codCidade: 1303957,
    cidade: "SAO SEBASTIAO DO UATUMA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13025767,
    nome: "CENTRO EDUCACIONAL ARTHUR VIRGILIO FILHO",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13030019,
    nome: "CENTRO EDUCACIONAL BERENICE MARTINS",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13063286,
    nome: "CENTRO EDUCACIONAL DOMENICO MARZI",
    codCidade: 1303908,
    cidade: "SAO PAULO DE OLIVENCA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13013076,
    nome: "CENTRO EDUCACIONAL GOVERNADOR GILBERTO MESTRINHO",
    codCidade: 1304203,
    cidade: "TEFE",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 493.62799072265625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13026470,
    nome: "COLEGIO AMAZONENSE D PEDRO II",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 505.87200927734375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13041924,
    nome: "COLEGIO BATISTA DE PARINTINS",
    codCidade: 1303403,
    cidade: "PARINTINS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.900000095367432,
    idebAF: 5.400000095367432,
    enemMediaGeral: 463.77398681640625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13026550,
    nome: "COLEGIO BRASILEIRO PEDRO SILVESTRE",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.699999809265137,
    enemMediaGeral: 486.8940124511719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13026577,
    nome: "COLEGIO MILITAR DA POLICIA MILITAR",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 7.099999904632568,
    idebAF: 5.900000095367432,
    enemMediaGeral: 551.81201171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13043765,
    nome: "COLEGIO NOSSA SENHORA DO CARMO",
    codCidade: 1303403,
    cidade: "PARINTINS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 7.099999904632568,
    idebAF: 5.300000190734863,
    enemMediaGeral: 481.89801025390625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13059548,
    nome: "E E MARIA EMILIA MARTINS MESTRINHO DE MEDEIROS RAPOSO",
    codCidade: 1300300,
    cidade: "AUTAZES",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13077430,
    nome: "E E PROFESSOR FRANCISCO DAS CHAGAS DE SOUZA ALBUQUERQUE",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 478.23199462890625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13018370,
    nome: "E E PROFESSOR GILBERTO MESTRINHO DE MEDEIROS RAPOSO",
    codCidade: 1301308,
    cidade: "CODAJAS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.599999904632568,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13046829,
    nome: "EDUCANDARIO SANTA RITA",
    codCidade: 1302405,
    cidade: "LABREA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13031031,
    nome: "EE PROF BERNADETE DO SOCORRO TRINDADE DA ROCHA",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13030574,
    nome: "EE PROFA MARIA ARMINDA GUIMARAES DE ANDRADE",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13304275,
    nome: "EE PROFESSOR ANTONIO JOSE BERNARDO VASCONCELOS",
    codCidade: 1300706,
    cidade: "BOCA DO ACRE",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 450.3420104980469,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13095099,
    nome: "EE PROFESSOR DEMOSTENES BELDUQUE ARAUJO TRAVESSA",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13099884,
    nome: "EETI ENGENHEIRO PROFESSOR SERGIO ALFREDO PESSOA FIGUEIREDO",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.699999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13098497,
    nome: "EETI GILBERTO MESTRINHO DE MEDEIROS RAPOSO",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13096591,
    nome: "EETI PROFESSORA CINTHIA REGIA GOMES DO LIVRAMENTO",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.900000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13246208,
    nome: "ES ESTADUAL AUREA PINHEIRO BRAGA",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 449.3479919433594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13090003,
    nome: "ESC DE FOR PROF ENFER SANITARISTA FCA SAAVEDRA",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13096613,
    nome: "ESC EST INDIGENA PROFESSOR LUIZ GONZAGA DE SOUZA FILHO",
    codCidade: 1301308,
    cidade: "CODAJAS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.299999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13084267,
    nome: "ESC EST PROFESSOR VICENTE GERALDO DE MENDONCA LIMA",
    codCidade: 1301902,
    cidade: "ITACOATIARA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13059696,
    nome: "ESC EST PROFESSORA MIRTES ROSA MENDES DE MENDONCA LIMA",
    codCidade: 1301902,
    cidade: "ITACOATIARA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13004263,
    nome: "ESC EST SENADOR JOAO BOSCO RAMOS DE LIMA",
    codCidade: 1302801,
    cidade: "MARAA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13304259,
    nome: "ESC EST TEMPO INT PROFESSOR GARCITYLZO DO LAGO E SILVA",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 4.900000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13258214,
    nome: "ESC EST TEMPO INT RAFAIEL HENRIQUE PINHEIRO DOS SANTOS",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13304224,
    nome: "ESC EST TEMPO INTEGRAL MARCANTONIO VILACA II",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 6.199999809265137,
    enemMediaGeral: 553.7479858398438,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13257218,
    nome: "ESCOLA EST PROFESSORA ANA LUCIA DE MORAES COSTA E SILVA",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.400000095367432,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13030000,
    nome: "ESCOLA EST TEREZA DE JESUS AZEVEDO DE VASCONCELOS DIAS",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13027042,
    nome: "ESCOLA ESTADUAL 1 DE MAIO",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.0,
    idebAF: 0.0,
    enemMediaGeral: 454.8399963378906,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13030132,
    nome: "ESCOLA ESTADUAL ADALBERTO VALE",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13040855,
    nome: "ESCOLA ESTADUAL ADELAIDE CABRAL",
    codCidade: 1302900,
    cidade: "MAUES",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.400000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13030140,
    nome: "ESCOLA ESTADUAL ADERSON DE MENEZES",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13030159,
    nome: "ESCOLA ESTADUAL AGNELLO BITTENCOURT",
    codCidade: 1302603,
    cidade: "MANAUS",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13022644,
    nome: "ESCOLA ESTADUAL AGRA REIS",
    codCidade: 1302504,
    cidade: "MANACAPURU",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13046446,
    nome: "ESCOLA ESTADUAL ALBERTO DE A CORREA",
    codCidade: 1303502,
    cidade: "PAUINI",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 13014307,
    nome: "ESCOLA ESTADUAL ALCINDA PINHEIRO COSTA",
    codCidade: 1300086,
    cidade: "ANAMA",
    estado: "AM",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataAM;
