let dataPR = [
      {
        "anoCenso": 2013,
        "cod": 41125479,
        "nome": "1 CENTENARIO C E EF M",
        "codCidade": 4104204,
        "cidade": "CAMPO LARGO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 486.5159912109375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41010710,
        "nome": "11 DE ABRIL C E EF M",
        "codCidade": 4126801,
        "cidade": "TAPEJARA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41028996,
        "nome": "11 DE OUTUBRO C E EF M",
        "codCidade": 4103701,
        "cidade": "CAMBE",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41017943,
        "nome": "14 DE DEZEMBRO C E EF M",
        "codCidade": 4118808,
        "cidade": "PEABIRU",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41021266,
        "nome": "14 DE DEZEMBRO C E EM PROFIS",
        "codCidade": 4100806,
        "cidade": "ALVORADA DO SUL",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 472.29400634765625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41139887,
        "nome": "29 DE ABRIL C E EF M",
        "codCidade": 4109609,
        "cidade": "GUARATUBA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 492.6619873046875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41063503,
        "nome": "31 DE MARCO C E EF M",
        "codCidade": 4119905,
        "cidade": "PONTA GROSSA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41107055,
        "nome": "ABILIO CARNEIRO C E EF M PROFIS",
        "codCidade": 4105706,
        "cidade": "CLEVELANDIA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 443.5060119628906,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41035224,
        "nome": "ABRAHAM LINCOLN C E EF M",
        "codCidade": 4113106,
        "cidade": "KALORE",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41125649,
        "nome": "ABRAHAM LINCOLN C E PRES EF M N",
        "codCidade": 4105805,
        "cidade": "COLOMBO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 496.6239929199219,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41023536,
        "nome": "ADAILE M LEITE C E EF M",
        "codCidade": 4115200,
        "cidade": "MARINGA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 492.8760070800781,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41113845,
        "nome": "ADAO SOBOCINSKI C E C EF M",
        "codCidade": 4113908,
        "cidade": "MALLET",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41017170,
        "nome": "ADAUCTO S ROCHA C E EF M",
        "codCidade": 4113734,
        "cidade": "LUIZIANA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41045149,
        "nome": "ADELAIDE GLASER ROSS C E EM",
        "codCidade": 4117008,
        "cidade": "NOVA FATIMA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41041003,
        "nome": "ADELIA A LOPES C E PROFA EF M",
        "codCidade": 4112702,
        "cidade": "JATAIZINHO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41095065,
        "nome": "ADELIA BIANCO SEGURO C E EF M",
        "codCidade": 4115739,
        "cidade": "MATO RICO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41029500,
        "nome": "ADELIA D BARBOSA C E PROFA EF M",
        "codCidade": 4113700,
        "cidade": "LONDRINA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41001940,
        "nome": "ADELIA ROSSI ARNALDI C E C EF M",
        "codCidade": 4118402,
        "cidade": "PARANAVAI",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 468.0979919433594,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41378237,
        "nome": "ADHELMAR SICURO C E C DR EF M",
        "codCidade": 4106209,
        "cidade": "CONTENDA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 468.7359924316406,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41117794,
        "nome": "ADILES BORDIN C E EF M",
        "codCidade": 4128203,
        "cidade": "UNIAO DA VITORIA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41018982,
        "nome": "ADOLPHO O FRANCO C E GOV EF M PROFIS",
        "codCidade": 4102109,
        "cidade": "ASTORGA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.0,
        "enemMediaGeral": 492.5740051269531,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41095936,
        "nome": "ADONIS MORSKI C E EF M PROFIS",
        "codCidade": 4103040,
        "cidade": "BOA VENTURA DE SAO ROQUE",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 470.49798583984375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41389719,
        "nome": "AFFONSO M ALBALADEJO C E C EF M",
        "codCidade": 4109708,
        "cidade": "IBAITI",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41114655,
        "nome": "AFONSO A DE CAMARGO C E DR EF M",
        "codCidade": 4122008,
        "cidade": "RIO AZUL",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41001060,
        "nome": "AFONSO CAMARGO C E PRES EF M PROFIS",
        "codCidade": 4113502,
        "cidade": "LOANDA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41137230,
        "nome": "AFONSO PENA C E EF M",
        "codCidade": 4125506,
        "cidade": "SAO JOSE DOS PINHAIS",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 492.2640075683594,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41042476,
        "nome": "AFRANIO PEIXOTO E E EF",
        "codCidade": 4100103,
        "cidade": "ABATIA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41123387,
        "nome": "AGALVIRA B PINTO C E PROFA EF M",
        "codCidade": 4101804,
        "cidade": "ARAUCARIA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41046188,
        "nome": "AGMAR M SCARDAZZI C E C PROFA EF M",
        "codCidade": 4126405,
        "cidade": "SERTANEJA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41093216,
        "nome": "AGOSTINHO PEREIRA C E PROF EF M",
        "codCidade": 4118501,
        "cidade": "PATO BRANCO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 505.9939880371094,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41000021,
        "nome": "AGOSTINHO STEFANELLO E E EF",
        "codCidade": 4100608,
        "cidade": "ALTO PARANA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41043642,
        "nome": "AIDES N DA SILVA C E PROF EF M N",
        "codCidade": 4106001,
        "cidade": "CONGONHINHAS",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41598040,
        "nome": "ALBA KEINERT PROF C E EF M",
        "codCidade": 4109401,
        "cidade": "GUARAPUAVA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41003330,
        "nome": "ALBERICO M DA SILVA C E EF M PROFIS",
        "codCidade": 4123709,
        "cidade": "SANTA ISABEL DO IVAI",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 466.99798583984375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41043901,
        "nome": "ALBERTO CARAZZAI C E EF M",
        "codCidade": 4106407,
        "cidade": "CORNELIO PROCOPIO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41057198,
        "nome": "ALBERTO DA SILVA PARANA C E EF M",
        "codCidade": 4128534,
        "cidade": "VENTANIA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41110960,
        "nome": "ALBERTO DE CARVALHO C E EF M PROFIS",
        "codCidade": 4120606,
        "cidade": "PRUDENTOPOLIS",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41140370,
        "nome": "ALBERTO GOMES VEIGA C E EM PROFIS",
        "codCidade": 4118204,
        "cidade": "PARANAGUA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 476.2460021972656,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41060997,
        "nome": "ALBERTO GONCALVES C E D EF M PROFIS N",
        "codCidade": 4117701,
        "cidade": "PALMEIRA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41023552,
        "nome": "ALBERTO J BYINGTON JR C E EF M",
        "codCidade": 4115200,
        "cidade": "MARINGA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 495.4259948730469,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41122801,
        "nome": "ALBERTO KRAUSE C E PROF EF M",
        "codCidade": 4100400,
        "cidade": "ALMIRANTE TAMANDARE",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41061888,
        "nome": "ALBERTO REBELLO VALENTE C E EF M",
        "codCidade": 4119905,
        "cidade": "PONTA GROSSA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41070224,
        "nome": "ALBERTO S DUMONT C E EF M",
        "codCidade": 4103453,
        "cidade": "CAFELANDIA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 467.52398681640625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41078519,
        "nome": "ALBERTO SANTOS DUMONT C E C EF M",
        "codCidade": 4121257,
        "cidade": "RAMILANDIA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 458.26800537109375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41025318,
        "nome": "ALBERTO SANTOS DUMONT C E EF M PROFIS",
        "codCidade": 4101408,
        "cidade": "APUCARANA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 481.6960144042969,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41011562,
        "nome": "ALBERTO SANTOS DUMONT C E EF M PROFIS",
        "codCidade": 4103909,
        "cidade": "CAMPINA DA LAGOA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41143582,
        "nome": "ALBINA NOVAK MUGINOSKI C E PROFA EF M",
        "codCidade": 4104204,
        "cidade": "CAMPO LARGO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41029542,
        "nome": "ALBINO F SANCHES C E EF M PROFIS",
        "codCidade": 4113700,
        "cidade": "LONDRINA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41109570,
        "nome": "ALCIDES MUNHOZ C E EF M",
        "codCidade": 4110102,
        "cidade": "IMBITUVA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41357191,
        "nome": "ALCINDO FANAYA JR C E P SURDOS EI EF M P",
        "codCidade": 4106902,
        "cidade": "CURITIBA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41127021,
        "nome": "ALCYONE M C VELLOZO C E PROF EF M",
        "codCidade": 4106902,
        "cidade": "CURITIBA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 477.88800048828125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41049500,
        "nome": "ALDO DALLAGO C E EF M N PROFIS",
        "codCidade": 4109708,
        "cidade": "IBAITI",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41125673,
        "nome": "ALFREDO CHAVES C E EF M",
        "codCidade": 4105805,
        "cidade": "COLOMBO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41141725,
        "nome": "ALFREDO GREIPEL JUNIOR C E C EF M",
        "codCidade": 4119103,
        "cidade": "PIEN",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41023560,
        "nome": "ALFREDO MOISES MALUF C E EF M",
        "codCidade": 4115200,
        "cidade": "MARINGA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41127048,
        "nome": "ALFREDO PARODI C E EF M",
        "codCidade": 4106902,
        "cidade": "CURITIBA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41127056,
        "nome": "ALGACYR M MAEDER C E PROF EF M",
        "codCidade": 4106902,
        "cidade": "CURITIBA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 495.7640075683594,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41127072,
        "nome": "ALINE PICHETH E E EF",
        "codCidade": 4106902,
        "cidade": "CURITIBA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.800000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41075919,
        "nome": "ALMIRO SARTORI C E EF M",
        "codCidade": 4108304,
        "cidade": "FOZ DO IGUACU",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41045181,
        "nome": "ALOYSIO DE BARROS TOSTES C E DR EF M",
        "codCidade": 4117008,
        "cidade": "NOVA FATIMA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41407245,
        "nome": "ALTAHIR GONCALVES E E PROFA EF",
        "codCidade": 4101200,
        "cidade": "ANTONINA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41126556,
        "nome": "ALTAIR DA SILVA LEME C E PROF EF M",
        "codCidade": 4105805,
        "cidade": "COLOMBO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41053761,
        "nome": "ALTAIR MONGRUEL C E EF M N",
        "codCidade": 4117305,
        "cidade": "ORTIGUEIRA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41011139,
        "nome": "ALTAMIRA DO PARANA C E EF M",
        "codCidade": 4100459,
        "cidade": "ALTAMIRA DO PARANA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41070526,
        "nome": "ALTO A DO IGUACU C E EF M",
        "codCidade": 4104600,
        "cidade": "CAPITAO LEONIDAS MARQUES",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 475.47198486328125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41145569,
        "nome": "ALTO DA GLORIA C E EF M",
        "codCidade": 4117602,
        "cidade": "PALMAS",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41105176,
        "nome": "ALTO RECREIO C E EF M",
        "codCidade": 4120903,
        "cidade": "QUEDAS DO IGUACU",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 465.02801513671875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41018184,
        "nome": "ALTO SAO JOAO C E C DE EF M",
        "codCidade": 4122503,
        "cidade": "RONCADOR",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41105184,
        "nome": "ALVARO N DE CAMARGO C E EF M",
        "codCidade": 4107546,
        "cidade": "ESPIGAO ALTO DO IGUACU",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 479.7279968261719,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41049322,
        "nome": "ALVINA PRESTES C E PROF EF N",
        "codCidade": 4107751,
        "cidade": "FIGUEIRA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41035232,
        "nome": "ALVORADA DA INFANCIA C E C EF M",
        "codCidade": 4113106,
        "cidade": "KALORE",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 424.2200012207031,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41061012,
        "nome": "AMADEU MARIO MARGRAF C E EF M",
        "codCidade": 4117701,
        "cidade": "PALMEIRA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41061969,
        "nome": "AMALIO PINHEIRO C E PROF EF M",
        "codCidade": 4119905,
        "cidade": "PONTA GROSSA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41127102,
        "nome": "AMANCIO MORO C E EF M",
        "codCidade": 4106902,
        "cidade": "CURITIBA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 500.9079895019531,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41072626,
        "nome": "AMANCIO MORO C E EF M N PROFIS",
        "codCidade": 4106308,
        "cidade": "CORBELIA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41059620,
        "nome": "AMANDA CARNEIRO DE MELLO C E EF M",
        "codCidade": 4104907,
        "cidade": "CASTRO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 490.3160095214844,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41099508,
        "nome": "AMARILIO C E PROF EF M",
        "codCidade": 4109401,
        "cidade": "GUARAPUAVA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.900000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41122453,
        "nome": "AMAZONAS C E CEL EF M",
        "codCidade": 4120101,
        "cidade": "PORTO AMAZONAS",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 468.14801025390625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41122615,
        "nome": "AMBROSIO BINI C E EF M",
        "codCidade": 4100400,
        "cidade": "ALMIRANTE TAMANDARE",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 466.5419921875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41135580,
        "nome": "AMYNTAS DE BARROS C E EF M PROFIS",
        "codCidade": 4119152,
        "cidade": "PINHAIS",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 487.5060119628906,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41116615,
        "nome": "ANA BOICO OLINQUEVICZ C E EF M",
        "codCidade": 4108502,
        "cidade": "GENERAL CARNEIRO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41378962,
        "nome": "ANA DIVANIR BORATTO C E EFM",
        "codCidade": 4119905,
        "cidade": "PONTA GROSSA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41029623,
        "nome": "ANA MOLINA GARCIA C E EF M",
        "codCidade": 4113700,
        "cidade": "LONDRINA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41007549,
        "nome": "ANA NERI C E EF M",
        "codCidade": 4118857,
        "cidade": "PEROBAL",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41099532,
        "nome": "ANA VANDA BASSARA C E EF M PROF",
        "codCidade": 4109401,
        "cidade": "GUARAPUAVA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 495.25799560546875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41004086,
        "nome": "ANALIA FRANCO E E EF",
        "codCidade": 4100509,
        "cidade": "ALTONIA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41021100,
        "nome": "ANASTACIO CEREZINE E E EF",
        "codCidade": 4100806,
        "cidade": "ALVORADA DO SUL",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41004957,
        "nome": "ANCHIETA C E E F M N",
        "codCidade": 4106605,
        "cidade": "CRUZEIRO DO OESTE",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41088352,
        "nome": "ANCHIETA C E PE EF M",
        "codCidade": 4122800,
        "cidade": "SALGADO FILHO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 480.2860107421875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41063597,
        "nome": "ANCHIETA C E PE EF M",
        "codCidade": 4102000,
        "cidade": "ASSIS CHATEAUBRIAND",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.800000190734863,
        "enemMediaGeral": 496.17999267578125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41000862,
        "nome": "ANCHIETA E E PE EF",
        "codCidade": 4110300,
        "cidade": "INAJA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41136292,
        "nome": "ANDRE ANDREATTA C E EF M",
        "codCidade": 4120804,
        "cidade": "QUATRO BARRAS",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41043936,
        "nome": "ANDRE SEUGLING C E EF M PROFIS",
        "codCidade": 4106407,
        "cidade": "CORNELIO PROCOPIO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 493.7860107421875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41028406,
        "nome": "ANDREA NUZZI C E MAESTRO EF M",
        "codCidade": 4103701,
        "cidade": "CAMBE",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41026381,
        "nome": "ANESIO A DE AZEVEDO C E PROF EF M",
        "codCidade": 4101507,
        "cidade": "ARAPONGAS",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.900000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41046960,
        "nome": "ANESIO DE A LEITE C E EF M",
        "codCidade": 4111803,
        "cidade": "JACAREZINHO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41112555,
        "nome": "ANGAI C E C DE EF M",
        "codCidade": 4107736,
        "cidade": "FERNANDES PINHEIRO",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41122623,
        "nome": "ANGELA SANDRI TEIXEIRA C E PROF EF M",
        "codCidade": 4100400,
        "cidade": "ALMIRANTE TAMANDARE",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 465.4700012207031,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41146085,
        "nome": "ANGELINA A C DO PRADO C E EF M",
        "codCidade": 4125506,
        "cidade": "SAO JOSE DOS PINHAIS",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 41147448,
        "nome": "ANGELINA R VEZOZZO E E EF",
        "codCidade": 4103602,
        "cidade": "CAMBARA",
        "estado": "PR",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      }
    ]
  

  export default dataPR;