let dataRJ = [
      {
        "anoCenso": 2013,
        "cod": 33046263,
        "nome": "CAIC 1003 DONA DARCY VARGAS",
        "codCidade": 3300456,
        "cidade": "BELFORD ROXO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 475.50201416015625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33105065,
        "nome": "CAIC EUCLIDES DA CUNHA",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33062340,
        "nome": "CAIC JOAQUIM JOSE DA SILVA XAVER - O TIRADENTES",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33100659,
        "nome": "CAIC NACOES UNIDAS",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 3.4000000953674316,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33120692,
        "nome": "CAIC THEOPHILO DE SOUZA PINTO",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33049920,
        "nome": "CE ABDALA CHAMA",
        "codCidade": 3301702,
        "cidade": "DUQUE DE CAXIAS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 494.28399658203125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33086540,
        "nome": "CE ACARI",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33077088,
        "nome": "CE ADALGISA MONTEIRO",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33049785,
        "nome": "CE ADELINA CASTRO",
        "codCidade": 3301702,
        "cidade": "DUQUE DE CAXIAS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 452.3080139160156,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33034869,
        "nome": "CE ADELINO TERRA",
        "codCidade": 3300308,
        "cidade": "BARRA DO PIRAI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.5,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33074160,
        "nome": "CE ADLAI STEVENSON",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33030626,
        "nome": "CE AFFONSINA MAZZILLO TEIXEIRA CAMPOS",
        "codCidade": 3304003,
        "cidade": "PIRAI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33068011,
        "nome": "CE AFONSO PENA",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33079331,
        "nome": "CE AGOSTINHO NETO",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33093156,
        "nome": "CE AGOSTINHO PORTO",
        "codCidade": 3305109,
        "cidade": "SAO JOAO DE MERITI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33051364,
        "nome": "CE AGRICOLA JOSE SOARES JUNIOR",
        "codCidade": 3301900,
        "cidade": "ITABORAI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33071535,
        "nome": "CE AGRIPINO GRIECO",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33072051,
        "nome": "CE ALAGOAS",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33136459,
        "nome": "CE ALBA CANIZARES DO NASCIMENTO",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33087717,
        "nome": "CE ALBERT EINSTEIN",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33077096,
        "nome": "CE ALBERTO PASQUALINI",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 487.8280029296875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33077363,
        "nome": "CE ALBERTO RANGEL",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33013497,
        "nome": "CE ALBERTO TORRES",
        "codCidade": 3305000,
        "cidade": "SAO JOAO DA BARRA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33051097,
        "nome": "CE ALCINDO GUANABARA",
        "codCidade": 3301850,
        "cidade": "GUAPIMIRIM",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 481.62200927734375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33062250,
        "nome": "CE ALDEBARA",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33049793,
        "nome": "CE ALEXANDER GRAHAM BELL",
        "codCidade": 3301702,
        "cidade": "DUQUE DE CAXIAS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 503.0820007324219,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33036071,
        "nome": "CE ALFREDO GOMES",
        "codCidade": 3306107,
        "cidade": "VALENCA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.800000190734863,
        "enemMediaGeral": 512.968017578125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33059152,
        "nome": "CE ALFREDO NEVES",
        "codCidade": 3303500,
        "cidade": "NOVA IGUACU",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 478.6400146484375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33032459,
        "nome": "CE ALFREDO PUJOL",
        "codCidade": 3304409,
        "cidade": "RIO CLARO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33046743,
        "nome": "CE ALICE PACCINI GELIO",
        "codCidade": 3300456,
        "cidade": "BELFORD ROXO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 473.0719909667969,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33077371,
        "nome": "CE ALINA DE BRITO",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33037965,
        "nome": "CE ALMIRANTE ALVARO ALBERTO",
        "codCidade": 3303807,
        "cidade": "PARATY",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.900000095367432,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 522.5859985351562,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33007403,
        "nome": "CE ALMIRANTE BARAO DE TEFFE",
        "codCidade": 3304706,
        "cidade": "SANTO ANTONIO DE PADUA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.900000095367432,
        "enemMediaGeral": 510.8240051269531,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33027137,
        "nome": "CE ALMIRANTE FREDERICO VILLAR",
        "codCidade": 3300258,
        "cidade": "ARRAIAL DO CABO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33082227,
        "nome": "CE ALMIRANTE FRONTIN",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33021082,
        "nome": "CE ALMIRANTE PROTOGENES",
        "codCidade": 3301603,
        "cidade": "DUAS BARRAS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.599999904632568,
        "idebAF": 5.300000190734863,
        "enemMediaGeral": 500.6400146484375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33035628,
        "nome": "CE ALMIRANTE RODRIGUES SILVA",
        "codCidade": 3306107,
        "cidade": "VALENCA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33087750,
        "nome": "CE ALMIRANTE TAMANDARE",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33028125,
        "nome": "CE ALMIRANTE TAMANDARE",
        "codCidade": 3305208,
        "cidade": "SAO PEDRO DA ALDEIA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33052492,
        "nome": "CE ALMIRANTE TAMANDARE",
        "codCidade": 3302270,
        "cidade": "JAPERI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.800000190734863,
        "enemMediaGeral": 498.9259948730469,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33057737,
        "nome": "CE ALMIRANTE TAMANDARE",
        "codCidade": 3303302,
        "cidade": "NITEROI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 493.697998046875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33038791,
        "nome": "CE ALVARO ALVIM",
        "codCidade": 3302908,
        "cidade": "MIGUEL PEREIRA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 530.1480102539062,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33048444,
        "nome": "CE ALVARO NEGROMONTE",
        "codCidade": 3301702,
        "cidade": "DUQUE DE CAXIAS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 487.8399963378906,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33090270,
        "nome": "CE AMANDA VELASCO",
        "codCidade": 3304904,
        "cidade": "SAO GONCALO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 477.6080017089844,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33074798,
        "nome": "CE AMAPA",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 448.6499938964844,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33063397,
        "nome": "CE AMARO CAVALCANTI",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 499.0480041503906,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33082235,
        "nome": "CE AMAZONAS",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33060797,
        "nome": "CE AMBAI",
        "codCidade": 3303500,
        "cidade": "NOVA IGUACU",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33031185,
        "nome": "CE AMERICO PIMENTA",
        "codCidade": 3304128,
        "cidade": "QUATIS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 513.6420288085938,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33061246,
        "nome": "CE ANA NERI",
        "codCidade": 3302858,
        "cidade": "MESQUITA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 484.4280090332031,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33014086,
        "nome": "CE ANA NUNES VIANA",
        "codCidade": 3304755,
        "cidade": "SAO FRANCISCO DE ITABAPOANA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 444.760009765625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33066124,
        "nome": "CE ANACLETO DE MEDEIROS",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33065276,
        "nome": "CE ANDRE MAUROIS",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 505.9679870605469,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33031711,
        "nome": "CE ANIBAL BENEVOLO",
        "codCidade": 3304201,
        "cidade": "RESENDE",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33085463,
        "nome": "CE ANITA GARIBALDI",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33031380,
        "nome": "CE ANTONINA RAMOS FREIRE",
        "codCidade": 3304201,
        "cidade": "RESENDE",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33058571,
        "nome": "CE ANTONIO DA SILVA",
        "codCidade": 3303500,
        "cidade": "NOVA IGUACU",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 483.2380065917969,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33037027,
        "nome": "CE ANTONIO DIAS LIMA",
        "codCidade": 3300100,
        "cidade": "ANGRA DOS REIS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33054576,
        "nome": "CE ANTONIO FIGUEIRA DE ALMEIDA",
        "codCidade": 3303203,
        "cidade": "NILOPOLIS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 500.00799560546875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33052182,
        "nome": "CE ANTONIO FRANCISCO LEAL",
        "codCidade": 3305752,
        "cidade": "TANGUA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 486.5039978027344,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33092214,
        "nome": "CE ANTONIO GONCALVES",
        "codCidade": 3305109,
        "cidade": "SAO JOAO DE MERITI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 486.9540100097656,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33140715,
        "nome": "CE ANTONIO HOUAISS",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 479.6080017089844,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33044368,
        "nome": "CE ANTONIO LOPES DE CAMPOS FILHO",
        "codCidade": 3304300,
        "cidade": "RIO BONITO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.5999999046325684,
        "enemMediaGeral": 466.40399169921875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33020140,
        "nome": "CE ANTONIO PECLY",
        "codCidade": 3301504,
        "cidade": "CORDEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.400000095367432,
        "enemMediaGeral": 513.9000244140625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33066590,
        "nome": "CE ANTONIO PRADO JUNIOR",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 505.02801513671875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33052433,
        "nome": "CE ARMANDO DIAS",
        "codCidade": 3302270,
        "cidade": "JAPERI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 409.92401123046875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33089043,
        "nome": "CE ARMANDO GONCALVES",
        "codCidade": 3304904,
        "cidade": "SAO GONCALO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33036209,
        "nome": "CE ARNOR SILVESTRE VIEIRA",
        "codCidade": 3306107,
        "cidade": "VALENCA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.800000190734863,
        "enemMediaGeral": 495.13800048828125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33058580,
        "nome": "CE ARRUDA NEGREIROS",
        "codCidade": 3303500,
        "cidade": "NOVA IGUACU",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.5,
        "enemMediaGeral": 484.2879943847656,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33002975,
        "nome": "CE ARY PARREIRAS",
        "codCidade": 3302304,
        "cidade": "LAJE DO MURIAE",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.900000095367432,
        "enemMediaGeral": 513.5380249023438,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33090300,
        "nome": "CE AUGUSTO CEZARIO DIAZ ANDRE",
        "codCidade": 3304904,
        "cidade": "SAO GONCALO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 497.2080078125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33086427,
        "nome": "CE AUGUSTO RUSCHI",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33021813,
        "nome": "CE AUGUSTO SPINELLI",
        "codCidade": 3303401,
        "cidade": "NOVA FRIBURGO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.800000190734863,
        "enemMediaGeral": 550.6259765625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33048452,
        "nome": "CE AURA BARRETO",
        "codCidade": 3301702,
        "cidade": "DUQUE DE CAXIAS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 454.5220031738281,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33055610,
        "nome": "CE AURELINO LEAL",
        "codCidade": 3303302,
        "cidade": "NITEROI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 507.1679992675781,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33054584,
        "nome": "CE AYDANO DE ALMEIDA",
        "codCidade": 3303203,
        "cidade": "NILOPOLIS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 501.12799072265625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33043752,
        "nome": "CE BACCOPARO MARTINS",
        "codCidade": 3300803,
        "cidade": "CACHOEIRAS DE MACACU",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33068844,
        "nome": "CE BAHIA",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33047243,
        "nome": "CE BAIRRO JARDIM AMERICA",
        "codCidade": 3300456,
        "cidade": "BELFORD ROXO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 466.8320007324219,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33046751,
        "nome": "CE BAIRRO NOVA AURORA",
        "codCidade": 3300456,
        "cidade": "BELFORD ROXO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33029342,
        "nome": "CE BALDOMERO BARBARA",
        "codCidade": 3300407,
        "cidade": "BARRA MANSA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 528.302001953125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33055629,
        "nome": "CE BALTAZAR BERNARDINO",
        "codCidade": 3303302,
        "cidade": "NITEROI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 3.9000000953674316,
        "idebAF": 3.5,
        "enemMediaGeral": 468.35400390625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33012121,
        "nome": "CE BALTAZAR CARNEIRO",
        "codCidade": 3301157,
        "cidade": "CARDOSO MOREIRA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33079340,
        "nome": "CE BANGU",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33029369,
        "nome": "CE BARAO DE AIURUOCA",
        "codCidade": 3300407,
        "cidade": "BARRA MANSA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 509.1180114746094,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33097577,
        "nome": "CE BARAO DE ITACURUSSA",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33128600,
        "nome": "CE BARAO DE ITARARE",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33036004,
        "nome": "CE BARAO DE JUPARANA",
        "codCidade": 3306107,
        "cidade": "VALENCA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33072078,
        "nome": "CE BARAO DE MACAUBAS",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33012458,
        "nome": "CE BARAO DE MACAUBAS",
        "codCidade": 3304805,
        "cidade": "SAO FIDELIS",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.199999809265137,
        "idebAF": 4.900000095367432,
        "enemMediaGeral": 488.1919860839844,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33032793,
        "nome": "CE BARAO DE MAUA",
        "codCidade": 3306305,
        "cidade": "VOLTA REDONDA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 501.54998779296875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33016569,
        "nome": "CE BARAO DE MONTE CEDRO",
        "codCidade": 3304151,
        "cidade": "QUISSAMA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33017646,
        "nome": "CE BARAO DE PALMEIRAS",
        "codCidade": 3303708,
        "cidade": "PARAIBA DO SUL",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 489.5780029296875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33023751,
        "nome": "CE BARAO DE SANTA MARIA MADALENA",
        "codCidade": 3304607,
        "cidade": "SANTA MARIA MADALENA",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 526.9180297851562,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33060800,
        "nome": "CE BARAO DE TINGUA",
        "codCidade": 3303500,
        "cidade": "NOVA IGUACU",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33034311,
        "nome": "CE BARAO DO RIO BONITO",
        "codCidade": 3300308,
        "cidade": "BARRA DO PIRAI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 492.28399658203125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33084238,
        "nome": "CE BARAO DO RIO BRANCO",
        "codCidade": 3304557,
        "cidade": "RIO DE JANEIRO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33052514,
        "nome": "CE BARAO DO RIO BRANCO",
        "codCidade": 3302270,
        "cidade": "JAPERI",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33044384,
        "nome": "CE BARAO DO RIO BRANCO",
        "codCidade": 3304300,
        "cidade": "RIO BONITO",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 500.9219970703125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 33025320,
        "nome": "CE BARRA DE SAO JOAO",
        "codCidade": 3301306,
        "cidade": "CASIMIRO DE ABREU",
        "estado": "RJ",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 492.3399963378906,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      }
    ]

    export default dataRJ;