let dataMA =
    [
      {
        "anoCenso": 2013,
        "cod": 21050554,
        "nome": "CE ACRISIO FIGUEIREDO",
        "codCidade": 2111003,
        "cidade": "SAO JOAO BATISTA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21326428,
        "nome": "CE ALCIDES CESAR",
        "codCidade": 2111748,
        "cidade": "SENADOR ALEXANDRE COSTA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21198247,
        "nome": "CE ALFREDO DUALIBE",
        "codCidade": 2108058,
        "cidade": "PAULINO NEVES",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21069026,
        "nome": "CE ALMEIDA BRAGA",
        "codCidade": 2106201,
        "cidade": "LUIS DOMINGUES",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21017093,
        "nome": "CE ALMIRANTE TAMANDARE",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 471.8599853515625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21155771,
        "nome": "CE ALUISIO AZEVEDO",
        "codCidade": 2103000,
        "cidade": "CAXIAS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 457.4159851074219,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21112398,
        "nome": "CE ALVES CARDOSO",
        "codCidade": 2111508,
        "cidade": "SAO MATEUS DO MARANHAO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21122342,
        "nome": "CE AMARAL RAPOSO",
        "codCidade": 2104800,
        "cidade": "GRAJAU",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21025649,
        "nome": "CE AMERICA CENTRAL",
        "codCidade": 2107100,
        "cidade": "MORROS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21022445,
        "nome": "CE AMERICA DO NORTE",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21127328,
        "nome": "CE ANA ISABEL TAVARES",
        "codCidade": 2103802,
        "cidade": "DOM PEDRO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 476.3219909667969,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21169012,
        "nome": "CE ANALIA NEIVA",
        "codCidade": 2107308,
        "cidade": "NOVA IORQUE",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 453.614013671875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21359202,
        "nome": "CE ANICETO MARIANO COSTA",
        "codCidade": 2106508,
        "cidade": "MATINHA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21009783,
        "nome": "CE ANJO DA GUARDA",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21164622,
        "nome": "CE ANNA BERNARDES",
        "codCidade": 2112209,
        "cidade": "TIMON",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 422.2539978027344,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21102759,
        "nome": "CE ANTONIO CORREA",
        "codCidade": 2104008,
        "cidade": "ESPERANTINOPOLIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 440.9219970703125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21243000,
        "nome": "CE ANTONIO CORREA ANEXO II SAO RAIMUNDO DO DOCA BEZERRA",
        "codCidade": 2111631,
        "cidade": "SAO RAIMUNDO DO DOCA BEZERRA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21122318,
        "nome": "CE ANTONIO FRANCISCO DOS REIS",
        "codCidade": 2104800,
        "cidade": "GRAJAU",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21199850,
        "nome": "CE ANTONIO JOAQUIM ARAUJO",
        "codCidade": 2102754,
        "cidade": "CAPINZAL DO NORTE",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21020698,
        "nome": "CE ANTONIO RIBEIRO DA SILVA",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 3.299999952316284,
        "idebAF": 2.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21205183,
        "nome": "CE ANTONIO SIRLEY DE ARRUDA LIMA",
        "codCidade": 2104099,
        "cidade": "FORMOSA DA SERRA NEGRA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 424.6000061035156,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21085064,
        "nome": "CE APARICIO BANDEIRA",
        "codCidade": 2113009,
        "cidade": "VITORINO FREIRE",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21185565,
        "nome": "CE AQUILES LISBOA",
        "codCidade": 2110658,
        "cidade": "SAO DOMINGOS DO AZEITAO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.199999809265137,
        "enemMediaGeral": 428.79400634765625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21118582,
        "nome": "CE ARDALIAO AMERICO PIRES",
        "codCidade": 2101608,
        "cidade": "BARRA DO CORDA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21164940,
        "nome": "CE ARISTIDES LOBAO",
        "codCidade": 2101509,
        "cidade": "BARAO DE GRAJAU",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 452.4800109863281,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21335214,
        "nome": "CE ARLINDO FERREIRA DE LUCENA",
        "codCidade": 2101608,
        "cidade": "BARRA DO CORDA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21044759,
        "nome": "CE ARTUR TEIXEIRA DE CARVALHO",
        "codCidade": 2108405,
        "cidade": "PERI MIRIM",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21134197,
        "nome": "CE ATENEU SAO JOSE",
        "codCidade": 2100907,
        "cidade": "ARAIOSES",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21339210,
        "nome": "CE ATENEU SAO JOSE ANEXO II - ILHAS CANARIAS",
        "codCidade": 2100907,
        "cidade": "ARAIOSES",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21077762,
        "nome": "CE BANDEIRA TRIBUZZI CAIC",
        "codCidade": 2109908,
        "cidade": "SANTA INES",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 458.17401123046875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21088144,
        "nome": "CE BANDEIRANTE",
        "codCidade": 2114007,
        "cidade": "ZE DOCA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21053960,
        "nome": "CE BELA VISTA",
        "codCidade": 2101772,
        "cidade": "BELA VISTA DO MARANHAO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21114218,
        "nome": "CE BEM ONY GOMES",
        "codCidade": 2100956,
        "cidade": "ARAME",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21068518,
        "nome": "CE BENEDITA JORGE",
        "codCidade": 2104305,
        "cidade": "GODOFREDO VIANA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21016933,
        "nome": "CE BENEDITO LEITE",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 476.0260009765625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21009805,
        "nome": "CE BERNARDO COELHO DE ALMEIDA",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 468.2699890136719,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21093350,
        "nome": "CE CAMINHO DO FUTURO",
        "codCidade": 2105302,
        "cidade": "IMPERATRIZ",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21138192,
        "nome": "CE CANDIDO MENDES",
        "codCidade": 2102101,
        "cidade": "BREJO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21035113,
        "nome": "CE CASEMIRO DE ABREU",
        "codCidade": 2112506,
        "cidade": "TUTOIA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21096040,
        "nome": "CE CASTELO BRANCO",
        "codCidade": 2105302,
        "cidade": "IMPERATRIZ",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 466.0260009765625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21159750,
        "nome": "CE CEZAR MARQUES",
        "codCidade": 2103000,
        "cidade": "CAXIAS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21145334,
        "nome": "CE CHAGAS ARAUJO",
        "codCidade": 2112605,
        "cidade": "URBANO SANTOS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21103321,
        "nome": "CE CHAGAS COSTA",
        "codCidade": 2105203,
        "cidade": "IGARAPE GRANDE",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21037604,
        "nome": "CE CIDADE DE ARARI",
        "codCidade": 2101004,
        "cidade": "ARARI",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 516.4439697265625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21021910,
        "nome": "CE CIDADE DE SAO LUIS",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21017115,
        "nome": "CE CIDADE OPERARIA I",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21010102,
        "nome": "CE CIDADE OPERARIA II",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 456.4159851074219,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21150311,
        "nome": "CE CLODOMIR MILET",
        "codCidade": 2103604,
        "cidade": "COROATA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 3.5,
        "idebAF": 2.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21009864,
        "nome": "CE COELHO NETO",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 459.7699890136719,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21022453,
        "nome": "CE COELHO NETO",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21148759,
        "nome": "CE COLARES MOREIRA",
        "codCidade": 2103307,
        "cidade": "CODO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21155755,
        "nome": "CE CONEGO ADERSON GUIMARAES JUNIOR",
        "codCidade": 2103000,
        "cidade": "CAXIAS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 434.9519958496094,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21162484,
        "nome": "CE CONEGO JESUS DE MOURA SOARES",
        "codCidade": 2107803,
        "cidade": "PARNARAMA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 432.8039855957031,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21251355,
        "nome": "CE CONEGO NESTOR CUNHA",
        "codCidade": 2110104,
        "cidade": "SANTA QUITERIA DO MARANHAO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21001901,
        "nome": "CE CRISTINO PIMENTA",
        "codCidade": 2101301,
        "cidade": "BACURI",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21159742,
        "nome": "CE CRISTOVAO COLOMBO",
        "codCidade": 2103000,
        "cidade": "CAXIAS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21075662,
        "nome": "CE CRISTOVAO COLOMBO",
        "codCidade": 2105708,
        "cidade": "LAGO DA PEDRA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21242941,
        "nome": "CE CRISTOVAO COLOMBO - ANEXO I - LAGOA GRANDE DO MARANHAO",
        "codCidade": 2105963,
        "cidade": "LAGOA GRANDE DO MARANHAO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21131384,
        "nome": "CE DARCY VARGAS",
        "codCidade": 2111250,
        "cidade": "SAO JOSE DOS BASILIOS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21136262,
        "nome": "CE DEBORAH CORREIA LIMA",
        "codCidade": 2110609,
        "cidade": "SAO BERNARDO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21093660,
        "nome": "CE DELAHE FIQUENE",
        "codCidade": 2105302,
        "cidade": "IMPERATRIZ",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21177384,
        "nome": "CE DELFINO AGUIAR DE AZEVEDO",
        "codCidade": 2111052,
        "cidade": "SAO JOAO DO PARAISO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 435.5320129394531,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21241996,
        "nome": "CE DEP ALEXANDRE COSTA",
        "codCidade": 2106672,
        "cidade": "MILAGRES DO MARANHAO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21129282,
        "nome": "CE DEPUTADO PIRES SABOIA",
        "codCidade": 2104503,
        "cidade": "GOVERNADOR ARCHER",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21221111,
        "nome": "CE DES EMESIO ARAUJO",
        "codCidade": 2101731,
        "cidade": "BELAGUA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21129991,
        "nome": "CE DIAS CARNEIRO",
        "codCidade": 2104602,
        "cidade": "GOVERNADOR EUGENIO BARROS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21272212,
        "nome": "CE DIMAS SIMAS LIMA ANEXO I",
        "codCidade": 2104800,
        "cidade": "GRAJAU",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21209669,
        "nome": "CE DIOLINDO DE PAULA RIBEIRO",
        "codCidade": 2107258,
        "cidade": "NOVA COLINAS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21065802,
        "nome": "CE DJALMA CRUZ",
        "codCidade": 2102606,
        "cidade": "CANDIDO MENDES",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21049351,
        "nome": "CE DOM FRANCISCO",
        "codCidade": 2110500,
        "cidade": "SAO BENTO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 460.3659973144531,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21053847,
        "nome": "CE DOM HAMLETO DE ANGELIS - CEMA",
        "codCidade": 2112803,
        "cidade": "VIANA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21048282,
        "nome": "CE DOM LUIS BRITO",
        "codCidade": 2110500,
        "cidade": "SAO BENTO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21118590,
        "nome": "CE DOM MARCELINO DE MILAO",
        "codCidade": 2101608,
        "cidade": "BARRA DO CORDA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21077711,
        "nome": "CE DOM PEDRO II",
        "codCidade": 2112274,
        "cidade": "TUFILANDIA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21046662,
        "nome": "CE DOM UNGARELLI",
        "codCidade": 2108603,
        "cidade": "PINHEIRO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21243344,
        "nome": "CE DOM UNGARELLI ANEXO I PRESIDENTE SARNEY",
        "codCidade": 2109270,
        "cidade": "PRESIDENTE SARNEY",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21008680,
        "nome": "CE DOMINGOS VIEIRA FILHO",
        "codCidade": 2107506,
        "cidade": "PACO DO LUMIAR",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 463.5060119628906,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21092699,
        "nome": "CE DORGIVAL PINHEIRO DE SOUSA",
        "codCidade": 2105302,
        "cidade": "IMPERATRIZ",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 467.6520080566406,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21173915,
        "nome": "CE DR ADONIAS LUCAS DE LACERDA",
        "codCidade": 2111904,
        "cidade": "SUCUPIRA DO NORTE",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21151806,
        "nome": "CE DR CARLOS MAGNO BACELAR",
        "codCidade": 2100105,
        "cidade": "AFONSO CUNHA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21153922,
        "nome": "CE DR CARLOS MAGNO DUQUE BACELAR",
        "codCidade": 2103406,
        "cidade": "COELHO NETO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21004013,
        "nome": "CE DR DEUSDETH CORTEZ VIEIRA DA SILVA",
        "codCidade": 2101350,
        "cidade": "BACURITUBA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21081590,
        "nome": "CE DR FERNANDO CASTRO",
        "codCidade": 2102325,
        "cidade": "BURITICUPU",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21020833,
        "nome": "CE DR FRANCISCO DE ASSIS XIMENES ARAGAO FILHO",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 468.2200012207031,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21110069,
        "nome": "CE DR GENESIO REGO",
        "codCidade": 2110302,
        "cidade": "SANTO ANTONIO DOS LOPES",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21022356,
        "nome": "CE DR GERALDO MELO",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21041504,
        "nome": "CE DR GETULIO VARGAS",
        "codCidade": 2106904,
        "cidade": "MONCAO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21136289,
        "nome": "CE DR HENRIQUE COUTO",
        "codCidade": 2110609,
        "cidade": "SAO BERNARDO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21013926,
        "nome": "CE DR JOAO BACELAR PORTELA",
        "codCidade": 2111300,
        "cidade": "SAO LUIS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 478.114013671875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21051763,
        "nome": "CE DR JOSE AROUCHE",
        "codCidade": 2111706,
        "cidade": "SAO VICENTE FERRER",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21044066,
        "nome": "CE DR JOSE JOAQUIM MARQUES",
        "codCidade": 2108306,
        "cidade": "PENALVA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21136904,
        "nome": "CE DR JOSE MARIA CABRAL MARQUES",
        "codCidade": 2100808,
        "cidade": "ANAPURUS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 429.03399658203125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21171726,
        "nome": "CE DR JOSE NEIVA",
        "codCidade": 2108009,
        "cidade": "PASTOS BONS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21134227,
        "nome": "CE DR JOSE SARNEY",
        "codCidade": 2100154,
        "cidade": "AGUA DOCE DO MARANHAO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21037710,
        "nome": "CE DR MILTON ERICEIRA",
        "codCidade": 2101004,
        "cidade": "ARARI",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21280401,
        "nome": "CE DR MILTON ERICEIRA ANEXO",
        "codCidade": 2101004,
        "cidade": "ARARI",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21123012,
        "nome": "CE DR NEWTON BELLO",
        "codCidade": 2105609,
        "cidade": "JOSELANDIA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21143951,
        "nome": "CE DR ODILON SILVA SOARES",
        "codCidade": 2110401,
        "cidade": "SAO BENEDITO DO RIO PRETO",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21194315,
        "nome": "CE DR OTAVIO VIEIRA PASSOS",
        "codCidade": 2103208,
        "cidade": "CHAPADINHA",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 21173427,
        "nome": "CE DR PAULO RAMOS",
        "codCidade": 2111102,
        "cidade": "SAO JOAO DOS PATOS",
        "estado": "MA",
        "regiao": "Nordeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      }
    ]
  export default dataMA;