let dataCE = [
  {
    anoCenso: 2013,
    cod: 23100133,
    nome: "ABRAAO BAQUIT EEFM",
    codCidade: 2311306,
    cidade: "QUIXADA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23079495,
    nome: "ADAHIL BARRETO CAVALCANTE EEFM",
    codCidade: 2307650,
    cidade: "MARACANAU",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 453.0639953613281,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23160098,
    nome: "ADAUTO LEITE EEFM",
    codCidade: 2308104,
    cidade: "MAURITI",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.0,
    enemMediaGeral: 431.260009765625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23041030,
    nome: "ADELINO CUNHA ALCANTARA EEEP",
    codCidade: 2312403,
    cidade: "SAO GONCALO DO AMARANTE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 543.52197265625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23056592,
    nome: "ADOLFO FERREIRA DE SOUSA EEEP",
    codCidade: 2311603,
    cidade: "REDENCAO",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 497.3739929199219,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23041790,
    nome: "ADRIANO NOBRE EEEP",
    codCidade: 2306306,
    cidade: "ITAPAGE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 596.0180053710938,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23167963,
    nome: "ADRIAO DO VALE NUVENS EEM",
    codCidade: 2312106,
    cidade: "SANTANA DO CARIRI",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 439.42999267578125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23247754,
    nome: "AGOSTINHO NERES PORTELA EEM",
    codCidade: 2312908,
    cidade: "SOBRAL",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 449.7919921875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23242949,
    nome: "ALDA FACANHA EEEP",
    codCidade: 2301000,
    cidade: "AQUIRAZ",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23150173,
    nome: "ALDA FERRER AUGUSTO DUTRA EEFM",
    codCidade: 2307502,
    cidade: "LAVRAS DA MANGABEIRA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 434.0679931640625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23265264,
    nome: "ALFREDO ALMEIDA MACHADO LICEU DE QUIXERAMOBIM",
    codCidade: 2311405,
    cidade: "QUIXERAMOBIM",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 462.61199951171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23090235,
    nome: "ALFREDO GOMES EEFM",
    codCidade: 2309300,
    cidade: "NOVA RUSSAS",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 461.0559997558594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23099380,
    nome: "ALFREDO MACHADO EEM",
    codCidade: 2307635,
    cidade: "MADALENA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 479.2019958496094,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23111291,
    nome: "ALFREDO NUNES DE MELO EEEP",
    codCidade: 2300309,
    cidade: "ACOPIARA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 503.37200927734375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23165278,
    nome: "ALM ERNANE VITORINO ABOIM SILVA CERE",
    codCidade: 2307304,
    cidade: "JUAZEIRO DO NORTE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.099999904632568,
    enemMediaGeral: 476.1960144042969,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23051930,
    nome: "ALMIR PINTO EEM",
    codCidade: 2301208,
    cidade: "ARACOIABA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 444.3999938964844,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23142332,
    nome: "AMELIA FIGUEIREDO DE LAVOR EEEP",
    codCidade: 2305506,
    cidade: "IGUATU",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 532.3280029296875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23034009,
    nome: "AMONTADA EEFM DE",
    codCidade: 2300754,
    cidade: "AMONTADA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 411.885986328125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23064323,
    nome: "ANA BEZERRA DE SA EEM",
    codCidade: 2304285,
    cidade: "EUSEBIO",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 451.302001953125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23235705,
    nome: "ANA NORONHA EEM",
    codCidade: 2310308,
    cidade: "PARAMBU",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 435.10198974609375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23035684,
    nome: "ANASTACIO ALVES BRAGA EEFM",
    codCidade: 2306405,
    cidade: "ITAPIPOCA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 438.760009765625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23160110,
    nome: "ANDRE CARTAXO EEM",
    codCidade: 2308104,
    cidade: "MAURITI",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 414.1520080566406,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23065214,
    nome: "ANISIO TEIXEIRA EEFM",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 497.6820068359375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23065494,
    nome: "ANTONIETA SIQUEIRA EEFM",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 448.3580017089844,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23015705,
    nome: "ANTONIO CUSTODIO EEM",
    codCidade: 2304509,
    cidade: "FRECHEIRINHA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 454.7980041503906,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23041811,
    nome: "ANTONIO CUSTODIO MESQUITA EEFM",
    codCidade: 2306306,
    cidade: "ITAPAGE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 445.7200012207031,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23187735,
    nome: "ANTONIO DIAS MACEDO EEFM",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.9000000953674316,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 465.3840026855469,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23244992,
    nome: "ANTONIO GERALDO DE LIMA EEM",
    codCidade: 2306256,
    cidade: "ITAITINGA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23249676,
    nome: "ANTONIO LUIZ COELHO EEM",
    codCidade: 2307700,
    cidade: "MARANGUAPE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 433.39801025390625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23179902,
    nome: "ANTONIO MOTA EEFM",
    codCidade: 2300804,
    cidade: "ANTONINA DO NORTE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.5,
    enemMediaGeral: 458.6159973144531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23545607,
    nome: "ANTONIO MOTA FILHO EEEP",
    codCidade: 2313203,
    cidade: "TAMBORIL",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 475.6520080566406,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23564040,
    nome: "ANTONIO RODRIGUES DE OLIVEIRA EEEP",
    codCidade: 2310506,
    cidade: "PEDRA BRANCA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 511.20001220703125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23032103,
    nome: "ARACY MAGALHAES MARTINS EEM",
    codCidade: 2312205,
    cidade: "SANTA QUITERIA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 427.2699890136719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23167386,
    nome: "ARISTARCO CARDOSO EEM",
    codCidade: 2311108,
    cidade: "PORTEIRAS",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 434.0480041503906,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23127821,
    nome: "ARSENIO FERREIRA MAIA EEFM",
    codCidade: 2307601,
    cidade: "LIMOEIRO DO NORTE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 483.1260070800781,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23101865,
    nome: "ASSIS BEZERRA EEFM",
    codCidade: 2311405,
    cidade: "QUIXERAMOBIM",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 440.81201171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23026596,
    nome: "AUTON ARAGAOEEFM",
    codCidade: 2305803,
    cidade: "IPU",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 438.6839904785156,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23133155,
    nome: "AVELINO MAGALHAES EEEP",
    codCidade: 2313104,
    cidade: "TABULEIRO DO NORTE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 521.5239868164062,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23025905,
    nome: "AYRES DE SOUSA EEM",
    codCidade: 2312908,
    cidade: "SOBRAL",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 436.9639892578125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23168749,
    nome: "BELARMINO LINS DE MEDEIROS EEFM",
    codCidade: 2300101,
    cidade: "ABAIARA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 422.3280029296875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23124172,
    nome: "BENI CARVALHO EEFM",
    codCidade: 2301109,
    cidade: "ARACATI",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 439.7279968261719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23062126,
    nome: "BRANCA CARNEIRO DE MENDONCA EEM",
    codCidade: 2303709,
    cidade: "CAUCAIA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 454.0880126953125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23056860,
    nome: "CAMILO BRASILIENSE EEFM",
    codCidade: 2311603,
    cidade: "REDENCAO",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 430.87200927734375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23153261,
    nome: "CAMPOS SALES EEFM DE",
    codCidade: 2302701,
    cidade: "CAMPOS SALES",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 443.7359924316406,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23008300,
    nome: "CARMINHA VASCONCELOS EEFM",
    codCidade: 2308906,
    cidade: "MORRINHOS",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 429.0140075683594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23049375,
    nome: "CASEMIRO BEZERRA DE ARAUJO EEFM",
    codCidade: 2303006,
    cidade: "CARIDADE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 457.8940124511719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23083476,
    nome: "CASIMIRO LEITE DE OLIVEIRA EEFM",
    codCidade: 2309706,
    cidade: "PACATUBA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 443.59600830078125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23064706,
    nome: "CEJA ADELINO ALCANTARA FILHO",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23135913,
    nome: "CEJA COSME ALVES DE LIMA",
    codCidade: 2306900,
    cidade: "JAGUARIBE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23244429,
    nome: "CEJA DE PACAJUS",
    codCidade: 2309607,
    cidade: "PACAJUS",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23053364,
    nome: "CEJA DONANINHA ARRUDA",
    codCidade: 2302107,
    cidade: "BATURITE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23231939,
    nome: "CEJA DR GERARDO CAMELO MADEIRA",
    codCidade: 2305803,
    cidade: "IPU",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23211202,
    nome: "CEJA DR JOSE NILSON OSTERNE DE OLIVEIRA",
    codCidade: 2307601,
    cidade: "LIMOEIRO DO NORTE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23238585,
    nome: "CEJA FREI JOSE ADEMIR DE ALMEIDA",
    codCidade: 2302800,
    cidade: "CANINDE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23180617,
    nome: "CEJA GOV LUIZ GONZAGA DA FONSECA MOTA",
    codCidade: 2305506,
    cidade: "IGUATU",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23245247,
    nome: "CEJA GUILHERME GOUVEIA",
    codCidade: 2304707,
    cidade: "GRANJA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23236493,
    nome: "CEJA JOAO DA SILVA RAMOS",
    codCidade: 2302602,
    cidade: "CAMOCIM",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23180781,
    nome: "CEJA JOAO RICARDO DA SILVEIRA",
    codCidade: 2311306,
    cidade: "QUIXADA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23225262,
    nome: "CEJA JOSE WALTER",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23221119,
    nome: "CEJA PADRE LUIZ GONZAGA XAVIER DE LIMA",
    codCidade: 2306405,
    cidade: "ITAPIPOCA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23227885,
    nome: "CEJA PAULO FREIRE",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23203390,
    nome: "CEJA PROF CECY CIALDINE",
    codCidade: 2312908,
    cidade: "SOBRAL",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23236582,
    nome: "CEJA PROFESSOR MILTON CUNHA",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23225653,
    nome: "CEJA PROFESSOR MOREIRA CAMPOS",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23166070,
    nome: "CEJA PROFESSORA CICERA GERMANO CORREIA",
    codCidade: 2307304,
    cidade: "JUAZEIRO DO NORTE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23234105,
    nome: "CEJA PROFESSORA MARIA EUDES VERAS",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23227362,
    nome: "CEJA PROFESSORA OFELIA PORTELA MOITA",
    codCidade: 2313401,
    cidade: "TIANGUA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23186488,
    nome: "CESAR CALS EEFM DR",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.199999809265137,
    enemMediaGeral: 493.5480041503906,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23067268,
    nome: "CLOVIS BEVILAQUA EEFM",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5,
    enemMediaGeral: 437.0979919433594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23091240,
    nome: "COELHO MASCARENHAS EEM",
    codCidade: 2309409,
    cidade: "NOVO ORIENTE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 437.4020080566406,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23198710,
    nome: "COLEGIO DA POLICIA MILITAR DO CEARA",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 7.699999809265137,
    idebAF: 7.0,
    enemMediaGeral: 600.5800170898438,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23081945,
    nome: "COLEGIO ESTADUAL ANCHIETA",
    codCidade: 2307700,
    cidade: "MARANGUAPE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 449.5159912109375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23223081,
    nome: "COLEGIO ESTADUAL RUI BARBOSA",
    codCidade: 2307650,
    cidade: "MARACANAU",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 445.56201171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23067330,
    nome: "COLONIA Z-8 EEF",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 4.599999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23078774,
    nome: "COMENDADOR MIGUEL GURGEL EEEP",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 514.2760009765625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23099194,
    nome: "CONEGO LUIZ BRAGA ROCHA EEM",
    codCidade: 2305266,
    cidade: "IBARETAMA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 436.0660095214844,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23225416,
    nome: "CONJUNTO CEARA EEM LICEU DO",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 487.7019958496094,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23024291,
    nome: "CORONEL APOLIANO EEM",
    codCidade: 2312809,
    cidade: "SENADOR SA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 426.73199462890625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23053380,
    nome: "CORONEL ESTEVAO ALVES DA ROCHA EEF",
    codCidade: 2302107,
    cidade: "BATURITE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23061693,
    nome: "CORONEL OSVALDO STUDART EEFM",
    codCidade: 2301000,
    cidade: "AQUIRAZ",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.0,
    enemMediaGeral: 437.5379943847656,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23067691,
    nome: "CRISTO REDENTOR EEF",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 4.599999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23057190,
    nome: "DANISIO DALTON DA ROCHA CORREA EEM",
    codCidade: 2301950,
    cidade: "BARREIRA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 462.1159973144531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23564440,
    nome: "DARIO CATUNDA FONTENELE EEEP",
    codCidade: 2305902,
    cidade: "IPUEIRAS",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23096209,
    nome: "DAVID VIEIRA DA SILVA EEEP",
    codCidade: 2302404,
    cidade: "BOA VIAGEM",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 523.6680297851562,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23104147,
    nome: "DE AIUABA EEM",
    codCidade: 2300408,
    cidade: "AIUABA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 475.23199462890625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23060948,
    nome: "DE AQUIRAZ EEFM",
    codCidade: 2301000,
    cidade: "AQUIRAZ",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 464.2040100097656,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23242426,
    nome: "DE CROATA FLAVIO RODRIGUES EEM",
    codCidade: 2304236,
    cidade: "CROATA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 450.0140075683594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23122064,
    nome: "DE SENADOR POMPEU EEEP",
    codCidade: 2312700,
    cidade: "SENADOR POMPEU",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 512.7479858398438,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23026693,
    nome: "DELMIRO GOUVEIA EEFM",
    codCidade: 2305803,
    cidade: "IPU",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 443.61199951171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23083549,
    nome: "DEP FAUSTO AGUIAR ARRUDA EEFM",
    codCidade: 2309706,
    cidade: "PACATUBA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 446.52801513671875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23069961,
    nome: "DEP FRANCISCO DE ALMEIDA MONTE EEFM",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 478.2699890136719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23071370,
    nome: "DEP IRAPUAN CAVALCANTE PINHEIRO EEFM",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 479.7619934082031,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23069490,
    nome: "DEP JOACY PEREIRA EEFM",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5,
    enemMediaGeral: 468.70599365234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23138106,
    nome: "DEP JOAQUIM FIGUEIREDO CORREIA EEFM",
    codCidade: 2306009,
    cidade: "IRACEMA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 451.62200927734375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23073918,
    nome: "DEP MANOEL RODRIGUES EEFM",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0,
    enemMediaGeral: 459.5419921875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23068710,
    nome: "DEP PAULINO ROCHA EEFM",
    codCidade: 2304400,
    cidade: "FORTALEZA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 451.1579895019531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23265400,
    nome: "DEPUTADO FRANCISCO ALVES SOBRINHO LICEU DE ACOPIARA",
    codCidade: 2300309,
    cidade: "ACOPIARA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 444.1499938964844,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23014385,
    nome: "DEPUTADO MANOEL RODRIGUES EEM",
    codCidade: 2314102,
    cidade: "VICOSA DO CEARA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 471.89801025390625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23083654,
    nome: "DES RAIMUNDO CARVALHO LIMA EEFM",
    codCidade: 2309706,
    cidade: "PACATUBA",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 445.2619934082031,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 23190884,
    nome: "DOM ANTONIO CAMPELO DE ARAGAO CAIC",
    codCidade: 2307304,
    cidade: "JUAZEIRO DO NORTE",
    estado: "CE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 467.864013671875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataCE;
