let dataAC = [
  {
    anoCenso: 2013,
    cod: 12013340,
    nome: "COLEGIO JOAO CALVINO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 488.88800048828125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12014591,
    nome: "ESC 15 DE JUNHO",
    codCidade: 1200450,
    cidade: "SENADOR GUIOMARD",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.0,
    enemMediaGeral: 468.74798583984375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011584,
    nome: "ESC ALCIMAR NUNES LEITAO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 474.6499938964844,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011614,
    nome: "ESC ANITA GARIBALDI",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12017469,
    nome: "ESC ANTHERO SOARES BEZERRA",
    codCidade: 1200708,
    cidade: "XAPURI",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12009725,
    nome: "ESC ARGENTINA PEREIRA FEITOSA",
    codCidade: 1200179,
    cidade: "CAPIXABA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.099999904632568,
    enemMediaGeral: 450.9739990234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12007412,
    nome: "ESC ASSIS VASCONCELOS",
    codCidade: 1200500,
    cidade: "SENA MADUREIRA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011169,
    nome: "ESC AUREA PIRES MONTES DE SOUZA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12051233,
    nome: "ESC BELO JARDIM",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12031674,
    nome: "ESC BELO PORVIR",
    codCidade: 1200252,
    cidade: "EPITACIOLANDIA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 457.7080078125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12091260,
    nome: "ESC BOA UNIAO ENSINO JOVEM",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12003050,
    nome: "ESC BORGES DE AQUINO",
    codCidade: 1200393,
    cidade: "PORTO WALTER",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12015326,
    nome: "ESC CEL JOSE PLACIDO DE CASTRO",
    codCidade: 1200807,
    cidade: "PORTO ACRE",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 444.3280029296875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12029599,
    nome: "ESC CENT DE EDUC PROFISSIONAL CAMPOS PEREIRA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12026697,
    nome: "ESC CENTRO DE EDUCACAO DE JOVENS E ADULTOS",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011401,
    nome: "ESC CLINIO BRANDAO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.800000190734863,
    idebAF: 4.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011444,
    nome: "ESC COLEGIO ESTADUAL BARAO DO RIO BRANCO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 473.0459899902344,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12000450,
    nome: "ESC CRAVEIRO COSTA",
    codCidade: 1200203,
    cidade: "CRUZEIRO DO SUL",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12028363,
    nome: "ESC CRECHE OLHAR DE CRIANCA",
    codCidade: 1200708,
    cidade: "XAPURI",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12003590,
    nome: "ESC CUNHA VASCONCELOS",
    codCidade: 1200427,
    cidade: "RODRIGUES ALVES",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12021717,
    nome: "ESC DJALMA TELES GALDINO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 4.099999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12007617,
    nome: "ESC DOM JULIO MATTIOLI",
    codCidade: 1200500,
    cidade: "SENA MADUREIRA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 463.1159973144531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011711,
    nome: "ESC DR PIMENTEL GOMES",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012378,
    nome: "ESC DUQUE DE CAXIAS",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12013404,
    nome: "ESC ELOZIRA DOS SANTOS THOME",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.099999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12007757,
    nome: "ESC FONTENELE DE CASTRO",
    codCidade: 1200500,
    cidade: "SENA MADUREIRA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12022004,
    nome: "ESC FRANCISCO BRAGA DE SOUZA",
    codCidade: 1200427,
    cidade: "RODRIGUES ALVES",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 433.00201416015625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12010189,
    nome: "ESC FRANKLIN ROOSEVELT",
    codCidade: 1200385,
    cidade: "PLACIDO DE CASTRO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12014354,
    nome: "ESC FREI THIAGO MARIA MATIOLLI",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011797,
    nome: "ESC GEORGETE ELUAN KALUME",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12027758,
    nome: "ESC GLORIA PEREZ",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 464.5679931640625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12091235,
    nome: "ESC GOVERNADOR JOSE AUGUSTO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012564,
    nome: "ESC HENRIQUE LIMA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12004154,
    nome: "ESC IMACULADA CONCEICAO",
    codCidade: 1200302,
    cidade: "FEIJO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.400000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12007625,
    nome: "ESC INSTITUTO SANTA JULIANA",
    codCidade: 1200500,
    cidade: "SENA MADUREIRA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.599999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12014389,
    nome: "ESC INSTITUTO SAO JOSE",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.099999904632568,
    idebAF: 4.699999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12005860,
    nome: "ESC INSTITUTO SAO JOSE",
    codCidade: 1200609,
    cidade: "TARAUACA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.099999904632568,
    idebAF: 5.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12028690,
    nome: "ESC IZA MELLO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12030155,
    nome: "ESC JAIRO DE FIGUEIREDO MELO",
    codCidade: 1200328,
    cidade: "JORDAO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 413.614013671875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12017108,
    nome: "ESC JOANA RIBEIRO AMED",
    codCidade: 1200252,
    cidade: "EPITACIOLANDIA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12091243,
    nome: "ESC JOAO EDUARDO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011860,
    nome: "ESC JOAO MARIANO DA SILVA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.0,
    idebAF: 5.900000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012661,
    nome: "ESC JOAO PAULO I",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012670,
    nome: "ESC JOAO PAULO II",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12023779,
    nome: "ESC JOAO RICARDO DE FREITAS",
    codCidade: 1200385,
    cidade: "PLACIDO DE CASTRO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 462.7300109863281,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12021687,
    nome: "ESC JOELMA OLIVEIRA DE LIMA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12019135,
    nome: "ESC JOSE FRANCISCO DA SILVA",
    codCidade: 1200385,
    cidade: "PLACIDO DE CASTRO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011878,
    nome: "ESC JOSE SALES DE ARAUJO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.400000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12016284,
    nome: "ESC KAIRALA JOSE KAIRALA",
    codCidade: 1200104,
    cidade: "BRASILEIA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012750,
    nome: "ESC LEONCIO DE CARVALHO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 458.36199951171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12029491,
    nome: "ESC LINDAURA MARTINS LEITAO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12027340,
    nome: "ESC LOURIVAL PINHO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 461.3340148925781,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12013013,
    nome: "ESC LOURIVAL SOMBRA PEREIRA LIMA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.699999809265137,
    enemMediaGeral: 475.7239990234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011894,
    nome: "ESC LUIZA BATISTA DE SOUZA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012815,
    nome: "ESC MADRE HILDEBRANDA DA PRA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12013498,
    nome: "ESC MARIA ANGELICA DE CASTRO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012025,
    nome: "ESC MARIA CHALUB LEITE",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.699999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12013455,
    nome: "ESC MARIA RAIMUNDA BALBINO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.599999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12003930,
    nome: "ESC NANZIO MAGALHAES",
    codCidade: 1200302,
    cidade: "FEIJO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12011959,
    nome: "ESC NATALINO DA SILVEIRA BRITO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12013293,
    nome: "ESC PADRE DIOGO FEIJO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12018007,
    nome: "ESC PLACIDO DE CASTRO",
    codCidade: 1200708,
    cidade: "XAPURI",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12028576,
    nome: "ESC PROF ALMADA BRITO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12013374,
    nome: "ESC PROF BERTA VIEIRA DE ANDRADE",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12052221,
    nome: "ESC PROF CLICIA GADELHA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 467.6400146484375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012556,
    nome: "ESC PROF HELOISA MOURAO MARQUES",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 477.9079895019531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12009229,
    nome: "ESC PROF PEDRO DE CASTRO MEIRELES",
    codCidade: 1200013,
    cidade: "ACRELANDIA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12044636,
    nome: "ESC PROF PEDRO MARTINELLO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 466.260009765625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12091251,
    nome: "ESC PROF TEREZINHA MIGUEIS",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.699999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12050229,
    nome: "ESC PROFESSOR JOSUE FERNANDES",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12013471,
    nome: "ESC RAIMUNDO GOMES DE OLIVEIRA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.699999809265137,
    idebAF: 5.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012050,
    nome: "ESC RAIMUNDO HERMINIO DE MELO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.599999904632568,
    idebAF: 4.900000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12008389,
    nome: "ESC RAIMUNDO MAGALHAES",
    codCidade: 1200500,
    cidade: "SENA MADUREIRA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012068,
    nome: "ESC RAMONA MULA PASTOR DE CASTRO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12013730,
    nome: "ESC SAO FRANCISCO DE ASSIS I",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12044822,
    nome: "ESC SEBASTIAO PEDROSA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 449.2659912109375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12012106,
    nome: "ESC SENADOR ADALBERTO SENA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12013889,
    nome: "ESC SERAFIM DA SILVA SALGADO",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12028843,
    nome: "ESC TECNICA EM SAUDE MARIA MOREIRA DA ROCHA",
    codCidade: 1200401,
    cidade: "RIO BRANCO",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 12006190,
    nome: "ESC TUPANIR GAUDENCIO DA COSTA",
    codCidade: 1200609,
    cidade: "TARAUACA",
    estado: "AC",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.900000095367432,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataAC;
