let dataGO = [
  {
    anoCenso: 2013,
    cod: 52070921,
    nome: "CAIC DARCY RIBEIRO",
    codCidade: 5201405,
    cidade: "APARECIDA DE GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52051200,
    nome: "CAIC JOSE ELIAS DE AZEVEDO",
    codCidade: 5219753,
    cidade: "SANTO ANTONIO DO DESCOBERTO",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52276350,
    nome: "CENTRO DE APOIO PEDAGOGICO PARA ATENDIMENTO AS PESSOAS COM DEFICIENCIA VISUAL - CAP",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52030032,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO CEL LUIS NETO",
    codCidade: 5220108,
    cidade: "SAO LUIS DE MONTES BELOS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52069974,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DE ARAGARCAS",
    codCidade: 5201702,
    cidade: "ARAGARCAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52070069,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DE IPORA",
    codCidade: 5210208,
    cidade: "IPORA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52069770,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO FRANCISCO HONORIO DA SILVA",
    codCidade: 5217203,
    cidade: "PIRANHAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52074897,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO HERBERT JOSE DE SOUZA",
    codCidade: 5221601,
    cidade: "URUACU",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52069885,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO INSTITUTO PESTALOZZI",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52073238,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO SAO FRANCISCO DE ASSIS",
    codCidade: 5209101,
    cidade: "GOIATUBA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52070778,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO VIVA A VIDA",
    codCidade: 5204102,
    cidade: "CACHOEIRA ALTA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52264360,
    nome: "CENTRO DE CAPACITACAO DE PROFISSIONAIS DA EDUCACAO E DE ATENDIMENTO AS PESSOAS COM SURDEZ - CAS",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52032957,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52080390,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS ARCO IRIS",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52004562,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS DE ARAGARCAS",
    codCidade: 5201702,
    cidade: "ARAGARCAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52027139,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS DOM BOSCO",
    codCidade: 5210208,
    cidade: "IPORA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52075311,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS FILOSTRO MACHADO CARNEIRO",
    codCidade: 5204508,
    cidade: "CALDAS NOVAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.699999809265137,
    enemMediaGeral: 482.1159973144531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52090930,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS GELMIRES REIS",
    codCidade: 5212501,
    cidade: "LUZIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52068935,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS PROF ALZIRA DE SOUZA CAMPOS",
    codCidade: 5205109,
    cidade: "CATALAO",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52020282,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS PROFESSOR ELIAS CHADUD",
    codCidade: 5201108,
    cidade: "ANAPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52011852,
    nome: "CENTRO DE EDUCACAO E CONVIVENCIA JUVENIL CORONEL GASPAR",
    codCidade: 5221601,
    cidade: "URUACU",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52025802,
    nome: "CENTRO DE EDUCACAO E CONVIVENCIA JUVENIL DR ORNELO MACHADO",
    codCidade: 5216809,
    cidade: "PETROLINA DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52027074,
    nome: "CENTRO DE EDUCACAO E CONVIVENCIA JUVENIL ELIAS DE ARAUJO ROCHA",
    codCidade: 5210208,
    cidade: "IPORA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52065820,
    nome: "CENTRO DE EDUCACAO E CONVIVENCIA JUVENIL GERALDO FERREIRA PIRES",
    codCidade: 5208509,
    cidade: "GOIANDIRA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52039242,
    nome: "CENTRO DE EDUCACAO E CONVIVENCIA JUVENIL RUI BARBOSA",
    codCidade: 5214507,
    cidade: "NEROPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52210359,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL AGUINALDO DE CAMPOS NETTO",
    codCidade: 5205109,
    cidade: "CATALAO",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52198359,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL CIDADE DE GOIAS",
    codCidade: 5208905,
    cidade: "GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52102203,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL DE ANAPOLIS",
    codCidade: 5201108,
    cidade: "ANAPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52242358,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL DE CAIAPONIA",
    codCidade: 5204409,
    cidade: "CAIAPONIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52290360,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL DE CERES",
    codCidade: 5205406,
    cidade: "CERES",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52211355,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL DE GOIATUBA",
    codCidade: 5209101,
    cidade: "GOIATUBA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52091376,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL DE PIRANHAS",
    codCidade: 5217203,
    cidade: "PIRANHAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52200400,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL DE PORANGATU - CEPP",
    codCidade: 5218003,
    cidade: "PORANGATU",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52096475,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL DE URUANA",
    codCidade: 5221700,
    cidade: "URUANA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52215385,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL EM ARTES BASILEU FRANCA",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52192350,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL GOVERNADOR OTAVIO LAGE",
    codCidade: 5208608,
    cidade: "GOIANESIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52091201,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL SEBASTIAO SIQUEIRA",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52050793,
    nome: "CENTRO INTEGRADO DE EDUCACAO MODELO CIEM",
    codCidade: 5217609,
    cidade: "PLANALTINA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.099999904632568,
    enemMediaGeral: 482.31201171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52068749,
    nome: "COLEGIO DA POLICIA MILITAR DE GOIAS UNIDADE AYRTON SENNA",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.0,
    enemMediaGeral: 494.8659973144531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52088499,
    nome: "COLEGIO DA POLICIA MILITAR DE GOIAS UNIDADE CARLOS CUNHA FILHO",
    codCidade: 5218805,
    cidade: "RIO VERDE",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 6.699999809265137,
    enemMediaGeral: 537.5460205078125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52088413,
    nome: "COLEGIO DA POLICIA MILITAR DE GOIAS UNIDADE DIONARIA ROCHA",
    codCidade: 5211503,
    cidade: "ITUMBIARA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.900000095367432,
    enemMediaGeral: 547.6900024414062,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52020576,
    nome: "COLEGIO DA POLICIA MILITAR DE GOIAS UNIDADE DR CEZAR TOLEDO",
    codCidade: 5201108,
    cidade: "ANAPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 7.0,
    enemMediaGeral: 549.6699829101562,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52033457,
    nome: "COLEGIO DA POLICIA MILITAR DE GOIAS UNIDADE HUGO DE CARVALHO RAMOS",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 6.300000190734863,
    enemMediaGeral: 539.906005859375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52034119,
    nome: "COLEGIO DA POLICIA MILITAR DE GOIAS UNIDADE POLIVALENTE MODELO VASCO DOS REIS",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.699999809265137,
    enemMediaGeral: 557.52001953125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52034275,
    nome: "COLEGIO DE APLICACAO DO INSTITUTO DE EDUCACAO DE GOIAS",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52043746,
    nome: "COLEGIO ESTADUAL 13 DE MAIO",
    codCidade: 5200308,
    cidade: "ALEXANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 490.24798583984375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52043711,
    nome: "COLEGIO ESTADUAL 31 DE MARCO",
    codCidade: 5200308,
    cidade: "ALEXANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52054292,
    nome: "COLEGIO ESTADUAL ABEL PEREIRA DE CASTRO",
    codCidade: 5218805,
    cidade: "RIO VERDE",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52084485,
    nome: "COLEGIO ESTADUAL ABIGAIL BRASIL DA SILVEIRA",
    codCidade: 5212501,
    cidade: "LUZIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52064948,
    nome: "COLEGIO ESTADUAL ABRAHAO ANDRE",
    codCidade: 5205109,
    cidade: "CATALAO",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 483.9339904785156,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52039803,
    nome: "COLEGIO ESTADUAL ADAGUISMAR DE OLIVEIRA",
    codCidade: 5221403,
    cidade: "TRINDADE",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52064425,
    nome: "COLEGIO ESTADUAL ADELINO ANTONIO GOMIDE",
    codCidade: 5201207,
    cidade: "ANHANGUERA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 489.614013671875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52045617,
    nome: "COLEGIO ESTADUAL ADELVINA FLORES RIBEIRO",
    codCidade: 5206206,
    cidade: "CRISTALINA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52020363,
    nome: "COLEGIO ESTADUAL ADOLPHO BATISTA",
    codCidade: 5201108,
    cidade: "ANAPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 448.6719970703125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52063070,
    nome: "COLEGIO ESTADUAL ADONIAS LEMES DO PRADO",
    codCidade: 5220264,
    cidade: "SAO MIGUEL DO PASSA QUATRO",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.900000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52059464,
    nome: "COLEGIO ESTADUAL ADONIRO MARTINS DE ANDRADE",
    codCidade: 5211503,
    cidade: "ITUMBIARA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.400000095367432,
    enemMediaGeral: 435.7640075683594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52033317,
    nome: "COLEGIO ESTADUAL AECIO OLIVEIRA DE ANDRADE",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52011798,
    nome: "COLEGIO ESTADUAL AEROPORTO",
    codCidade: 5221601,
    cidade: "URUACU",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 4.599999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52032213,
    nome: "COLEGIO ESTADUAL AGNELO RIBEIRO",
    codCidade: 5203302,
    cidade: "BELA VISTA DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52043533,
    nome: "COLEGIO ESTADUAL AGUA FRIA",
    codCidade: 5200175,
    cidade: "AGUA FRIA DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52061663,
    nome: "COLEGIO ESTADUAL AGUA QUENTE",
    codCidade: 5218789,
    cidade: "RIO QUENTE",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 468.10400390625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52070140,
    nome: "COLEGIO ESTADUAL ALBERICO DE ARAUJO RORIZ",
    codCidade: 5221858,
    cidade: "VALPARAISO DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52034798,
    nome: "COLEGIO ESTADUAL ALBERT SABIN",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.599999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52052613,
    nome: "COLEGIO ESTADUAL ALCANTARA DE CARVALHO",
    codCidade: 5211909,
    cidade: "JATAI",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52047431,
    nome: "COLEGIO ESTADUAL ALCEU DE ARAUJO RORIZ",
    codCidade: 5212501,
    cidade: "LUZIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.699999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52004260,
    nome: "COLEGIO ESTADUAL ALCIDES RAMOS JUBE",
    codCidade: 5212956,
    cidade: "MATRINCHA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52055582,
    nome: "COLEGIO ESTADUAL ALFREDO NASSER",
    codCidade: 5219407,
    cidade: "SANTA RITA DO ARAGUAIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 464.13800048828125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52027996,
    nome: "COLEGIO ESTADUAL ALFREDO NASSER",
    codCidade: 5215207,
    cidade: "NOVO BRASIL",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.0,
    enemMediaGeral: 459.9939880371094,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52001954,
    nome: "COLEGIO ESTADUAL ALFREDO NASSER",
    codCidade: 5203807,
    cidade: "BRITANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 460.8559875488281,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52004805,
    nome: "COLEGIO ESTADUAL ALFREDO NASSER",
    codCidade: 5202353,
    cidade: "ARENOPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.699999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52039625,
    nome: "COLEGIO ESTADUAL ALFREDO NASSER",
    codCidade: 5221197,
    cidade: "TEREZOPOLIS DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52017109,
    nome: "COLEGIO ESTADUAL ALFREDO NASSER",
    codCidade: 5209804,
    cidade: "HIDROLINA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.300000190734863,
    enemMediaGeral: 477.5,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52011747,
    nome: "COLEGIO ESTADUAL ALFREDO NASSER",
    codCidade: 5221601,
    cidade: "URUACU",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 472.2699890136719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52047288,
    nome: "COLEGIO ESTADUAL ALMIRANTE TAMANDARE",
    codCidade: 5221858,
    cidade: "VALPARAISO DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52030776,
    nome: "COLEGIO ESTADUAL ALTO PARAISO",
    codCidade: 5201405,
    cidade: "APARECIDA DE GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52018318,
    nome: "COLEGIO ESTADUAL ALVAMIR FARIA DOS ANJOS",
    codCidade: 5214705,
    cidade: "NOVA AMERICA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.599999904632568,
    enemMediaGeral: 463.4440002441406,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52074030,
    nome: "COLEGIO ESTADUAL AMALIA HERMANO TEIXEIRA",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.099999904632568,
    enemMediaGeral: 476.86199951171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52051609,
    nome: "COLEGIO ESTADUAL AMELIA FLORENCIA BARROS",
    codCidade: 5222203,
    cidade: "VILA BOA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.099999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52046192,
    nome: "COLEGIO ESTADUAL AMERICANO DO BRASIL",
    codCidade: 5208004,
    cidade: "FORMOSA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52029964,
    nome: "COLEGIO ESTADUAL AMERICO ANTUNES",
    codCidade: 5220108,
    cidade: "SAO LUIS DE MONTES BELOS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.599999904632568,
    enemMediaGeral: 468.77398681640625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52020843,
    nome: "COLEGIO ESTADUAL AMERICO BORGES DE CARVALHO",
    codCidade: 5201108,
    cidade: "ANAPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52029182,
    nome: "COLEGIO ESTADUAL AMERICO GONCALVES FALEIRO",
    codCidade: 5207808,
    cidade: "FIRMINOPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52053970,
    nome: "COLEGIO ESTADUAL ANA ALGEMIRA DO PRADO",
    codCidade: 5215652,
    cidade: "PALESTINA DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.800000190734863,
    enemMediaGeral: 449.9679870605469,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52001148,
    nome: "COLEGIO ESTADUAL ANA MARIA TORRES",
    codCidade: 5215256,
    cidade: "NOVO PLANALTO",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.599999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52005100,
    nome: "COLEGIO ESTADUAL ANA RITA DE FARIA",
    codCidade: 5203401,
    cidade: "BOM JARDIM DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52045080,
    nome: "COLEGIO ESTADUAL ANDRE GAUDIE",
    codCidade: 5205802,
    cidade: "CORUMBA DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.099999904632568,
    enemMediaGeral: 480.7919921875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52060004,
    nome: "COLEGIO ESTADUAL ANGELO URZEDA",
    codCidade: 5212600,
    cidade: "MAIRIPOTABA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.800000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52064794,
    nome: "COLEGIO ESTADUAL ANICE CECILIO PEDREIRO",
    codCidade: 5205109,
    cidade: "CATALAO",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.199999809265137,
    idebAF: 4.5,
    enemMediaGeral: 490.7380065917969,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52027678,
    nome: "COLEGIO ESTADUAL ANTENOR PADILHA",
    codCidade: 5211602,
    cidade: "IVOLANDIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.800000190734863,
    idebAF: 5.900000095367432,
    enemMediaGeral: 469.9339904785156,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52020371,
    nome: "COLEGIO ESTADUAL ANTENSINA SANTANA",
    codCidade: 5201108,
    cidade: "ANAPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.800000190734863,
    enemMediaGeral: 482.89801025390625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52007650,
    nome: "COLEGIO ESTADUAL ANTONIO ALBINO FERREIRA",
    codCidade: 5213087,
    cidade: "MINACU",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 460.0159912109375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52030822,
    nome: "COLEGIO ESTADUAL ANTONIO ALVES FORTES",
    codCidade: 5201405,
    cidade: "APARECIDA DE GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52040208,
    nome: "COLEGIO ESTADUAL ANTONIO CLARET CARDOSO",
    codCidade: 5200803,
    cidade: "ALVORADA DO NORTE",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52066550,
    nome: "COLEGIO ESTADUAL ANTONIO FERREIRA GOULART",
    codCidade: 5215504,
    cidade: "OUVIDOR",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52026256,
    nome: "COLEGIO ESTADUAL ANTONIO FERREIRA RIOS",
    codCidade: 5219902,
    cidade: "SAO FRANCISCO DE GOIAS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.0,
    enemMediaGeral: 477.56201171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52033953,
    nome: "COLEGIO ESTADUAL ANTONIO OLIVEIRA DA SILVA",
    codCidade: 5208707,
    cidade: "GOIANIA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52006409,
    nome: "COLEGIO ESTADUAL ARAPOEMA MEIRELES",
    codCidade: 5204706,
    cidade: "CAMPINORTE",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52041816,
    nome: "COLEGIO ESTADUAL ARGEMIRO ANTONIO DE ARAUJO",
    codCidade: 5218300,
    cidade: "POSSE",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.199999809265137,
    enemMediaGeral: 455.2820129394531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52072088,
    nome: "COLEGIO ESTADUAL ARISTON GOMES DA SILVA",
    codCidade: 5210208,
    cidade: "IPORA",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.900000095367432,
    enemMediaGeral: 484.1820068359375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 52020851,
    nome: "COLEGIO ESTADUAL ARLINDO COSTA",
    codCidade: 5201108,
    cidade: "ANAPOLIS",
    estado: "GO",
    regiao: "Centro-Oeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.699999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataGO;
