let dataBA = [
  {
    anoCenso: 2013,
    cod: 29386632,
    nome: "CENTRO DE APOIO PEDAGAGOGICO AO DEFICIENTE VISUAL",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29903734,
    nome: "CENTRO DE ESPORTES ARTE E CULTURA CESAR BORGES",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29322480,
    nome: "COLEGIO POLIVALENTE DE ITANHEM",
    codCidade: 2916005,
    cidade: "ITANHEM",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29413532,
    nome: "CRECHE BEM QUERER",
    codCidade: 2933307,
    cidade: "VITORIA DA CONQUISTA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29842727,
    nome: "E - COLEGIO ESTADUAL NOVA DE SUSSUARANA",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29436842,
    nome: "EE - CENTRO DE APOIO PEDAGOGICO - CAP",
    codCidade: 2910800,
    cidade: "FEIRA DE SANTANA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29380375,
    nome: "EE - CENTRO DE APOIO PEDAGOGICO AO DEFICIENTE VISUAL",
    codCidade: 2910800,
    cidade: "FEIRA DE SANTANA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29848792,
    nome: "EE - CENTRO DE APOIO PEDAGOGICO DE IPIAU-CAPI",
    codCidade: 2913903,
    cidade: "IPIAU",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29397324,
    nome: "EE - CENTRO DE APOIO PEDAGOGICO DE JEQUIE - CAP",
    codCidade: 2918001,
    cidade: "JEQUIE",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29305373,
    nome: "EE - CENTRO DE APOIO PEDAGOGICO GRAPIUNA",
    codCidade: 2914802,
    cidade: "ITABUNA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29200296,
    nome: "EE - CENTRO DE CAPACITACAO DE PROFISSIONAIS DA EDUCACAO -WILSON LINS-CAS BA",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29179815,
    nome: "EE - CENTRO DE EDUCACAO ESPECIAL DA BAHIA - CEEBA",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29091462,
    nome: "EE - CENTRO DE EDUCACAO PRESIDENTE TANCREDO NEVES",
    codCidade: 2908507,
    cidade: "CONCEICAO DO JACUIPE",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29093295,
    nome: "EE - CENTRO DE ENSINO E CULTURA DR EDUARDO FROES DA MOTTA",
    codCidade: 2910800,
    cidade: "FEIRA DE SANTANA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 452.989990234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29277604,
    nome: "EE - CENTRO DE TREINAMENTO E RECUPERACAO REGIS PACHECO",
    codCidade: 2933307,
    cidade: "VITORIA DA CONQUISTA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29145805,
    nome: "EE - CENTRO EDUCACIONAL 30 DE JUNHO",
    codCidade: 2930501,
    cidade: "SERRINHA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29019508,
    nome: "EE - CENTRO EDUCACIONAL ANTONIO HONORATO",
    codCidade: 2907202,
    cidade: "CASA NOVA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29179548,
    nome: "EE - CENTRO EDUCACIONAL CARNEIRO RIBEIRO - CLASSE I",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29179394,
    nome: "EE - CENTRO EDUCACIONAL CARNEIRO RIBEIRO - CLASSE II",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29179629,
    nome: "EE - CENTRO EDUCACIONAL CARNEIRO RIBEIRO - CLASSE III",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29179491,
    nome: "EE - CENTRO EDUCACIONAL CARNEIRO RIBEIRO - CLASSE IV",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29983720,
    nome: "EE - CENTRO EDUCACIONAL CARNEIRO RIBEIRO - ESCOLA PARQUE",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29093341,
    nome: "EE - CENTRO EDUCACIONAL CENECISTA CONEGO CUPERTINO DE LACERDA",
    codCidade: 2910800,
    cidade: "FEIRA DE SANTANA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29013259,
    nome: "EE - CENTRO EDUCACIONAL DE CORRENTINA",
    codCidade: 2909307,
    cidade: "CORRENTINA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29275474,
    nome: "EE - CENTRO EDUCACIONAL DE PLANALTO",
    codCidade: 2925006,
    cidade: "PLANALTO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29220076,
    nome: "EE - CENTRO EDUCACIONAL DE SEABRA",
    codCidade: 2929909,
    cidade: "SEABRA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29070350,
    nome: "EE - CENTRO EDUCACIONAL DEOCLECIANO BARBOSA DE CASTRO",
    codCidade: 2917508,
    cidade: "JACOBINA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29180490,
    nome: "EE - CENTRO EDUCACIONAL EDGAR SANTOS",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29282004,
    nome: "EE - CENTRO EDUCACIONAL GILBERTO VIANA",
    codCidade: 2915809,
    cidade: "ITAMBE",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 459.10198974609375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29368219,
    nome: "EE - CENTRO EDUCACIONAL MACHADO DE ASSIS",
    codCidade: 2931350,
    cidade: "TEIXEIRA DE FREITAS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29063299,
    nome: "EE - CENTRO EDUCACIONAL MANOEL TEIXEIRA LEITE",
    codCidade: 2914406,
    cidade: "IRAQUARA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29297974,
    nome: "EE - CENTRO EDUCACIONAL MONTEIRO LOBATO",
    codCidade: 2910909,
    cidade: "FIRMINO ALVES",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29327695,
    nome: "EE - CENTRO EDUCACIONAL PROFESSOR ROMULO GALVAO - MONTE CASTELO",
    codCidade: 2931350,
    cidade: "TEIXEIRA DE FREITAS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29216486,
    nome: "EE - CENTRO EDUCACIONAL RENATO PEREIRA VIANA",
    codCidade: 2919306,
    cidade: "LENCOIS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29014239,
    nome: "EE - CENTRO EDUCACIONAL SANTAMARIENSE",
    codCidade: 2928109,
    cidade: "SANTA MARIA DA VITORIA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.599999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29201020,
    nome: "EE - CENTRO EDUCACIONAL SANTO ANTONIO",
    codCidade: 2930709,
    cidade: "SIMOES FILHO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.900000095367432,
    idebAF: 4.099999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29016916,
    nome: "EE - CENTRO EDUCACIONAL SAO GONCALO",
    codCidade: 2930303,
    cidade: "SERRA DOURADA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29043069,
    nome: "EE - CENTRO EDUCACIONAL SAO JOSE",
    codCidade: 2903904,
    cidade: "BOM JESUS DA LAPA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29107440,
    nome: "EE - CENTRO EDUCACIONAL SAO JOSE",
    codCidade: 2927507,
    cidade: "SANTA BARBARA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29205387,
    nome: "EE - CENTRO EDUCACIONAL SAO SEBASTIAO",
    codCidade: 2907558,
    cidade: "CATURAMA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29073324,
    nome: "EE - CENTRO EDUCACIONAL SOROR JOANA ANGELICA",
    codCidade: 2921401,
    cidade: "MIRANGABA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29170583,
    nome: "EE - CENTRO EDUCACIONAL TEODORO SAMPAIO",
    codCidade: 2928604,
    cidade: "SANTO AMARO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29191190,
    nome: "EE - CENTRO EST DE ED PROFISSIONAL EM SAUDE E TECNOLOGIA DA INFORMACAO CARLOS CORREA DE MENEZES SANT",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29344247,
    nome: "EE - CENTRO EST ED PROF EM GESTAO E NEGOCIOS DO CENTPRO BAHIANO PROFESSORA FELICIDADE JESUS MAGALHA",
    codCidade: 2917508,
    cidade: "JACOBINA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29192196,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO MAGALHAES NETO",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29200342,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PESTALOZZI DA BAHIA",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29863724,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL AGUAS",
    codCidade: 2902708,
    cidade: "BARRA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29432960,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL AUREO DE OLIVEIRA FILHO",
    codCidade: 2910800,
    cidade: "FEIRA DE SANTANA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29397693,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL DO CAMPO PAULO FREIRE",
    codCidade: 2928000,
    cidade: "SANTALUZ",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29862728,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL DO OCEANO",
    codCidade: 2933208,
    cidade: "VERA CRUZ",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29199387,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM APOIO EDUCACIONAL TECNOLOGIA DA INFORMACAO ISAIAS A",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 482.7359924316406,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29447151,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM ARTES E DESIGN",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29304377,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM BIOTECNOLOGIA E SAUDE",
    codCidade: 2914802,
    cidade: "ITABUNA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 471.6940002441406,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29196434,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM CONTROLE E PROCESSOS INDUSTRIAIS NEWTON SUCUPIRA",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 479.12200927734375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29392365,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM GESTAO E MEIO AMBIENTE",
    codCidade: 2904605,
    cidade: "BRUMADO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 493.9179992675781,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29024803,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM GESTAO E NEGOCIOS DO NORTE BAIANO",
    codCidade: 2918407,
    cidade: "JUAZEIRO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29301394,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM GESTAO E TECNOLOGIA DA INFORMACAO ALVARO MELO VIEIR",
    codCidade: 2913606,
    cidade: "ILHEUS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 472.6400146484375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29229529,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM GESTAO E TECNOLOGIA DA INFORMACAO REGIS PACHECO",
    codCidade: 2918001,
    cidade: "JEQUIE",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29187320,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM GESTAO NEGOCIOS E TURISMO LUIZ NAVARRO DE BRITO",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29181542,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM GESTAO SEVERINO VIEIRA",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 459.75,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29301483,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM LOGISTICA TRANSPORTE E PRODUCAO INDUSTRIAL",
    codCidade: 2913606,
    cidade: "ILHEUS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29277736,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM SAUDE ADELIA TEIXEIRA",
    codCidade: 2933307,
    cidade: "VITORIA DA CONQUISTA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29181151,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM SAUDE ANISIO TEIXEIRA",
    codCidade: 2927408,
    cidade: "SALVADOR",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29093520,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM SAUDE DO CENTRO BAIANO",
    codCidade: 2910800,
    cidade: "FEIRA DE SANTANA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29290732,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM SAUDE DO LESTE BAIANO",
    codCidade: 2932903,
    cidade: "VALENCA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29243920,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM SAUDE E GESTAO",
    codCidade: 2911709,
    cidade: "GUANAMBI",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29055385,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM SAUDE TANCREDO NEVES",
    codCidade: 2930105,
    cidade: "SENHOR DO BONFIM",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29201632,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM SERVICOS E PROCESSOS INDUSTRIAIS IRMA DULCE",
    codCidade: 2930709,
    cidade: "SIMOES FILHO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29170877,
    nome: "EE - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM TURISMO DO LESTE BAIANO",
    codCidade: 2928604,
    cidade: "SANTO AMARO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29410134,
    nome: "EE - CENTRO ESTADUAL EDUCACAO ESPECIAL DE CAETITE PROFESSORA IELITA NEVES COTRIM SILVA",
    codCidade: 2905206,
    cidade: "CAETITE",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29220246,
    nome: "EE - CENTRO ESTADUAL EDUCACAO PROFISSIONAL EM TURISMO DO CENTRO BAIANO LETICE OLIVEIRA MACIEL",
    codCidade: 2929909,
    cidade: "SEABRA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29093457,
    nome: "EE - CENTRO INTEGRADO DE EDUCACAO ASSIS CHATEAUBRIAND",
    codCidade: 2910800,
    cidade: "FEIRA DE SANTANA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 501.6440124511719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29155673,
    nome: "EE - CENTRO INTEGRADO DE EDUCACAO DO CONDE",
    codCidade: 2908606,
    cidade: "CONDE",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29304296,
    nome: "EE - CENTRO INTEGRADO OSCAR MARINHO FALCAO - CIOMF",
    codCidade: 2914802,
    cidade: "ITABUNA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 484.78399658203125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29457343,
    nome: "EE - CENTRO NOTURNO DE EDUCACAO DA BAHIA-CENEB DE FEIRA DE SANTANA",
    codCidade: 2910800,
    cidade: "FEIRA DE SANTANA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29457513,
    nome: "EE - CENTRO NOTURNO DE EDUCACAO DA BAHIA-CENEB DE SENHOR DO BONFIM",
    codCidade: 2930105,
    cidade: "SENHOR DO BONFIM",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29101484,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DA BACIA DO JACUIPE",
    codCidade: 2914000,
    cidade: "IPIRA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29208297,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DA BACIA DO PARAMIRIM",
    codCidade: 2919801,
    cidade: "MACAUBAS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29014433,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DA BACIA DO RIO CORRENTE",
    codCidade: 2928109,
    cidade: "SANTA MARIA DA VITORIA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29000971,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DA BACIA DO RIO GRANDE",
    codCidade: 2903201,
    cidade: "BARREIRAS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 475.45599365234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29221943,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DA CHAPADA DIAMANTINA",
    codCidade: 2933406,
    cidade: "WAGNER",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29428203,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DA COSTA DO DESCOBRIMENTO",
    codCidade: 2910727,
    cidade: "EUNAPOLIS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29034922,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DE ITAPARICA",
    codCidade: 2924009,
    cidade: "PAULO AFONSO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29277990,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DE VITORIA DA CONQUISTA",
    codCidade: 2933307,
    cidade: "VITORIA DA CONQUISTA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 504.843994140625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29299063,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO BAIXO SUL",
    codCidade: 2911204,
    cidade: "GANDU",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 478.9800109863281,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29389631,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO EXTREMO SUL",
    codCidade: 2931350,
    cidade: "TEIXEIRA DE FREITAS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29149835,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO LITORAL NORTE E AGRESTE BAIANO",
    codCidade: 2900702,
    cidade: "ALAGOINHAS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29288142,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO LITORAL SUL - COMUNIDADE QUILOMBOLA",
    codCidade: 2920700,
    cidade: "MARAU",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29340500,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO LITORAL SUL II",
    codCidade: 2914802,
    cidade: "ITABUNA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 466.489990234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29283647,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO MEDIO SUDOESTE DA BAHIA",
    codCidade: 2917102,
    cidade: "ITORORO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29069580,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO PIEMONTE DA DIAMANTINA",
    codCidade: 2906873,
    cidade: "CAPIM GROSSO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29419468,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO PIEMONTE N DO ITAPICURU",
    codCidade: 2917706,
    cidade: "JAGUARARI",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29432626,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO RECONCAVO",
    codCidade: 2928703,
    cidade: "SANTO ANTONIO DE JESUS",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 489.4739990234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29133130,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO SEMI ARIDO NORDESTE II",
    codCidade: 2926608,
    cidade: "RIBEIRA DO POMBAL",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29024641,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO SERTAO DO SAO FRANCISCO",
    codCidade: 2918407,
    cidade: "JUAZEIRO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 458.2340087890625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29124484,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO SERTAO DO SAO FRANCISCO II ANTONIO CONSELHEIRO",
    codCidade: 2932002,
    cidade: "UAUA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29432235,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL DO SISAL",
    codCidade: 2930501,
    cidade: "SERRINHA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29332230,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL ITAPARICA II WILSON PEREIRA",
    codCidade: 2924009,
    cidade: "PAULO AFONSO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29083354,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL PIEMONTE DO PARAGUACU I",
    codCidade: 2914703,
    cidade: "ITABERABA",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 29086914,
    nome: "EE - CENTRO TERRITORIAL DE EDUCACAO PROFISSIONAL PIEMONTE DO PARAGUACU II",
    codCidade: 2922102,
    cidade: "MUNDO NOVO",
    estado: "BA",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataBA;
