let dataPI = [
  {
    anoCenso: 2013,
    cod: 22022015,
    nome: "CAIC - CENTRO DE ATENCAO INTEGRADO A CRIANCA-PROFESSOR MELO MAGALHAES",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.9000000953674316,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22021990,
    nome: "CAIC JOAO MENDES OLIMPIO DE MELO",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22022007,
    nome: "CAIC PROFESSOR BALDUINO BARBOSA DE DEUS",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 450.5260009765625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22022040,
    nome: "CEB PROF JAMES AZEVEDO",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 451.2139892578125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22111891,
    nome: "CEEP - CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL PROFESSOR BALDUINO BARBOSA DE DEUS",
    codCidade: 2207009,
    cidade: "OEIRAS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22118330,
    nome: "CEEP PROFESSORA ANGELINA MENDES BRAGA",
    codCidade: 2207900,
    cidade: "PEDRO II",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22028820,
    nome: "CEFTI -CENTRO DE ENSINO FUNDAMENTAL TEMPO INTEGRAL - PADRE JOAQUIM NONATO GOMES",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22027319,
    nome: "CEFTI PROFESSOR DARCY ARAUJO",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.0,
    idebAF: 4.800000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22026487,
    nome: "CEJA - CENTRO DE ENSINO JOVENS E ADULTOS - PROFESSORA MARIA RODRIGUES DAS MERCEDES",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22026495,
    nome: "CEJA - PROFESSORA SHIRLEY COSTA E SILVA",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22014500,
    nome: "CEJA JONAS CORREIA",
    codCidade: 2207702,
    cidade: "PARNAIBA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22045503,
    nome: "CEJA MARIA DO AMPARO M SILVA",
    codCidade: 2208809,
    cidade: "REGENERACAO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22000054,
    nome: "CEJA PROF CONRADO AMORIM DE SOUSA",
    codCidade: 2201200,
    cidade: "BARRAS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22022287,
    nome: "CEJA PROFESSOR ARTUR FURTADO",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22022295,
    nome: "CEJA PROFESSOR CLAUDIO FERREIRA",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22006249,
    nome: "CEJA-UNIDADE ESCOLAR JOSE LOPES DE ARAUJO",
    codCidade: 2205805,
    cidade: "LUZILANDIA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22100083,
    nome: "CEMJA ESCOLA NORMAL SENADOR JOSE CANDIDO FERRAZ",
    codCidade: 2210003,
    cidade: "SAO JOAO DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 413.8919982910156,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22131450,
    nome: "CEMTI - PAULO FREIRE",
    codCidade: 2204550,
    cidade: "GUARIBAS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22027475,
    nome: "CEMTI DIDACIO SILVA",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.199999809265137,
    enemMediaGeral: 481.406005859375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22256725,
    nome: "CEMTI JOAO HENRIQUE DE ALMEIDA SOUZA",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 535.3179931640625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22033971,
    nome: "CENT DE EDUC DE JOVENS E ADULTO PROFA MULATA LIMA",
    codCidade: 2202208,
    cidade: "CAMPO MAIOR",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22058117,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO AGRONOMO PARENTES",
    codCidade: 2203909,
    cidade: "FLORIANO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22057790,
    nome: "CENTRO DE EDUCACAO DE JOVENS ADULTOS PROFESSORA SOCORRO MENDES",
    codCidade: 2203909,
    cidade: "FLORIANO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22051180,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS VITORIA DA COSTA LIMA",
    codCidade: 2211308,
    cidade: "VALENCA DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22053484,
    nome: "CENTRO DE EDUCACAO PROFISSIONAL DE TEMPO INTEGRAL - CEPTI - MARIA PIRES LIMA",
    codCidade: 2211209,
    cidade: "URUCUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22022120,
    nome: "CENTRO DE ENSINO DE TEMPO INTEGRAL GOVERNADOR FREITAS NETO",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.300000190734863,
    idebAF: 4.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22028145,
    nome: "CENTRO DE ENSINO FUNDAMENTAL DE TEMPO INTEGRAL DUQUE DE CAXIAS",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.400000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22062610,
    nome: "CENTRO DE ENSINO MEDIO DE TEMPO INTEGRAL - CEMTI-FRANKLIN DORIA",
    codCidade: 2201903,
    cidade: "BOM JESUS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 444.447998046875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22072667,
    nome: "CENTRO DE ENSINO MEDIO DE TEMPO INTEGRAL MODERNA",
    codCidade: 2210607,
    cidade: "SAO RAIMUNDO NONATO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 464.9580078125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22015809,
    nome: "CENTRO DE ENSINO MEDIO DE TEMPO INTEGRAL POLIVALENTE LIMA REBELO",
    codCidade: 2207702,
    cidade: "PARNAIBA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 502.22601318359375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22053620,
    nome: "CENTRO DE ENSINO MEDIO JORNADA AMPLIADA - CICERO COELHO",
    codCidade: 2211209,
    cidade: "URUCUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 442.7239990234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22133976,
    nome: "CENTRO DE ENSINO MEDIO JOSE SOARES",
    codCidade: 2208700,
    cidade: "REDENCAO DO GURGUEIA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 433.697998046875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22022147,
    nome: "CENTRO DE HABILITACAO ANA CORDEIRO",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22133674,
    nome: "CENTRO EDUCACIONAL INTEGRADO ANGELIM",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22135030,
    nome: "CENTRO EDUCACIONAL SEBASTIAO DE SOUSA",
    codCidade: 2201572,
    cidade: "BELEM DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22128450,
    nome: "CENTRO ENSINO MEDIO RAIMUNDO NEIVA DE SOUSA",
    codCidade: 2208551,
    cidade: "PORTO ALEGRE DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 401.0559997558594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22141162,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL CORINA MACHADO VIEIRA",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22100717,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL DEPUTADO FRANCISCO ANTONIO PAES LANDIM NETO",
    codCidade: 2210003,
    cidade: "SAO JOAO DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22027726,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL DESEMBARGADOR HENRIQUE COUTO",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22025316,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL EM SAUDE MONSENHOR JOSE LUIS BARBOSA CORTEZ",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 489.49200439453125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22004823,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL LEONARDO DAS DORES",
    codCidade: 2203701,
    cidade: "ESPERANTINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 479.17999267578125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22136711,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL MANOEL JOSE DE ALMEIDA",
    codCidade: 2201200,
    cidade: "BARRAS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 436.59600830078125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22015221,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL MINISTRO PETRONIO PORTELLA",
    codCidade: 2207702,
    cidade: "PARNAIBA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22027742,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL PAULO FERRAZ",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22081348,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL PETRONIO PORTELLA",
    codCidade: 2208007,
    cidade: "PICOS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 454.5140075683594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22160809,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL RURAL ALCIDES VIEIRA DE MOURA",
    codCidade: 2210805,
    cidade: "SIMPLICIO MENDES",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22147209,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL RURAL MANOEL OTAVIO",
    codCidade: 2211100,
    cidade: "UNIAO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 442.8800048828125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22162011,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONAL RURAL PROFª MARIA AMALIA",
    codCidade: 2201705,
    cidade: "BERTOLINIA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22057498,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONALIZANTE - CALISTO LOBO",
    codCidade: 2203909,
    cidade: "FLORIANO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 460.74798583984375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22088857,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFISSIONALIZANTE JOAO MARTINS DO REGO",
    codCidade: 2204303,
    cidade: "FRONTEIRAS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22027297,
    nome: "CENTRO ESTADUAL DE ENSINO FUNDAMENTAL DE TEMPO INTEGRAL PROFESSOR RALDIR CAVALCANTE BASTOS",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 7.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22169601,
    nome: "CENTRO INTEGRADO DE EDUCACAO ESPECIAL - CIES",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22033998,
    nome: "CEPTI CANDIDO BORGES CASTELO BRANCO",
    codCidade: 2202208,
    cidade: "CAMPO MAIOR",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 475.1300048828125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22025308,
    nome: "CEPTI GOVERNADOR DIRCEU MENDES ARCOVERDE",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 487.62799072265625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22022376,
    nome: "COL EST ZACARIAS DE GOIS",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 521.3759765625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22088814,
    nome: "COLEGIO ESTADUAL FRANCISCA PEREIRA DE SOUSA MORAIS",
    codCidade: 2204303,
    cidade: "FRONTEIRAS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 437.99798583984375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22014535,
    nome: "COLEGIO ESTADUAL LIMA REBELO",
    codCidade: 2207702,
    cidade: "PARNAIBA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 436.91400146484375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22118900,
    nome: "COLEGIO ESTADUAL PROFESSOR JOSE ATANASIO DE SANTANA",
    codCidade: 2210805,
    cidade: "SIMPLICIO MENDES",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22032339,
    nome: "COLEGIO ESTADUAL PROFESSOR RAIMUNDINHO ANDRADE",
    codCidade: 2202208,
    cidade: "CAMPO MAIOR",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 1.899999976158142,
    enemMediaGeral: 484.8380126953125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22135782,
    nome: "COLEGIO ESTADUAL PROFESSORA MARIA DO SOCORRO SAMPAIO MARTINS",
    codCidade: 2202653,
    cidade: "CAXINGO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22133070,
    nome: "COLEGIO ESTADUAL SENADOR CHAGAS RODRIGUES",
    codCidade: 2207702,
    cidade: "PARNAIBA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 452.1960144042969,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22135456,
    nome: "COLEGIO LICEU PARNAIBANO",
    codCidade: 2207702,
    cidade: "PARNAIBA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 455.1300048828125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22053190,
    nome: "EDUC S JOSE DA ACAO SOCIAL DIV C JESUS",
    codCidade: 2209203,
    cidade: "SANTA FILOMENA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22136002,
    nome: "ENSINO MEDIO AUGUSTINHO BRANDAO",
    codCidade: 2202729,
    cidade: "COCAL DOS ALVES",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 538.1259765625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22136037,
    nome: "ENSINO MEDIO PINHEIRO MACHADO",
    codCidade: 2202703,
    cidade: "COCAL",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22042954,
    nome: "ESC ISOL ADALBERTO CORREIA LIMA",
    codCidade: 2207108,
    cidade: "OLHO D AGUA DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 444.2179870605469,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22072292,
    nome: "ESC NORMAL GERCILIO DE CASTRO MACEDO",
    codCidade: 2210607,
    cidade: "SAO RAIMUNDO NONATO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 438.9360046386719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22025324,
    nome: "ESC TEC EST PREF JOAO MENDES OLIMPIO DE MELO",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 472.2699890136719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22062726,
    nome: "ESCOLA AGRICOLA DO DNOCS",
    codCidade: 2200459,
    cidade: "ALVORADA DO GURGUEIA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22249753,
    nome: "ESCOLA AGROTECNICA DA FAMILIA AGRICOLA DO GURGUEIA",
    codCidade: 2202752,
    cidade: "COLONIA DO GURGUEIA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22140115,
    nome: "ESCOLA AGROTECNICA DEP RIBEIRO MAGALHAES",
    codCidade: 2202703,
    cidade: "COCAL",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22015159,
    nome: "ESCOLA DE APLICACAO FRANCISCO CORREIA",
    codCidade: 2207702,
    cidade: "PARNAIBA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22138412,
    nome: "ESCOLA DE ENSINO MEDIO VILA MARIA",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22080686,
    nome: "ESCOLA ESTADUAL PEDRO EVANGELISTA CAMINHA",
    codCidade: 2204352,
    cidade: "GEMINIANO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22050043,
    nome: "ESCOLA ISOLADA GETULIO VARGAS",
    codCidade: 2210383,
    cidade: "SAO MIGUEL DA BAIXA GRANDE",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 449.4339904785156,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22081291,
    nome: "ESCOLA NORMAL OFICIAL DE PICOS",
    codCidade: 2208007,
    cidade: "PICOS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 463.7879943847656,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22095500,
    nome: "ESCOLA REUNIDA DE PATOS",
    codCidade: 2207777,
    cidade: "PATOS DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 444.66400146484375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22061258,
    nome: "ESCOLA REUNIDA MIGUEL MARINHO",
    codCidade: 2210391,
    cidade: "SAO MIGUEL DO FIDALGO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 418.343994140625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22015191,
    nome: "ESCOLA SAO FCO DOS CAPUCHINHOS",
    codCidade: 2207702,
    cidade: "PARNAIBA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22156801,
    nome: "ESCOLA TECNICA DE TEATRO GOMES CAMPOS",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22018654,
    nome: "GIN EST LUIZ ALVES DE ALMEIDA",
    codCidade: 2201606,
    cidade: "BENEDITINOS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22105117,
    nome: "GIN EST SEN CHAGAS RODRIGUES",
    codCidade: 2206605,
    cidade: "MONTE ALEGRE DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22055142,
    nome: "GINASIO EST NOSSA SENHORA DE FATIMA",
    codCidade: 2203602,
    cidade: "ELISEU MARTINS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 433.6679992675781,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22078096,
    nome: "GINASIO ESTADUAL DR JOSE GUSMAO",
    codCidade: 2202778,
    cidade: "COLONIA DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 423.5979919433594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22009019,
    nome: "GINASIO PROF ARIMATHEA",
    codCidade: 2206803,
    cidade: "NOSSA SENHORA DOS REMEDIOS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22045910,
    nome: "GRUPO ESCOLAR FRANCISCO NUNES",
    codCidade: 2209807,
    cidade: "SAO GONCALO DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 438.8280029296875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22053182,
    nome: "GRUPO ESCOLAR PROF LOURENCO FILHO",
    codCidade: 2209203,
    cidade: "SANTA FILOMENA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22018670,
    nome: "GRUPO ESCOLAR RAIMUNDO ARAUJO PRADO",
    codCidade: 2201606,
    cidade: "BENEDITINOS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22140859,
    nome: "INSTITUTO DE EDUCACAO ANTONINO FREIRE",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22041591,
    nome: "JD DA INFANCIA MENINO JESUS",
    codCidade: 2200202,
    cidade: "AGUA BRANCA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22044590,
    nome: "JOAQUIM BARBOSA DE ALMEIDA",
    codCidade: 2207504,
    cidade: "PALMEIRAIS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22088806,
    nome: "NEJA CAROLINA MARIA BEZERRA",
    codCidade: 2204303,
    cidade: "FRONTEIRAS",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22023208,
    nome: "NEJA GAYOSO E ALMENDRA",
    codCidade: 2211001,
    cidade: "TERESINA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22100580,
    nome: "NEJA PROFESSOR ADAIL COELHO MAIA",
    codCidade: 2210003,
    cidade: "SAO JOAO DO PIAUI",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22029435,
    nome: "NES LUIS CARLOS BOA VISTA R MONTEIRO",
    codCidade: 2211100,
    cidade: "UNIAO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22107055,
    nome: "NUC ENS JOVENS ADULTOS OTACILIA RAMOS",
    codCidade: 2200509,
    cidade: "AMARANTE",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22109633,
    nome: "NUCLEO DE EDC JOVENS E ADULTOS LUIZ PADRE",
    codCidade: 2200202,
    cidade: "AGUA BRANCA",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22108378,
    nome: "NUCLEO DE EUCACAO DE JOVENS E ADULTOS TERESA ROSADO SIMOES",
    codCidade: 2208205,
    cidade: "PIO IX",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22137947,
    nome: "U E DEPUTADA FRANCISCA TRINDADE",
    codCidade: 2202000,
    cidade: "BURITI DOS LOPES",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 455.4179992675781,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 22133682,
    nome: "U E LUIZ UBIRACI DE CARVALHO",
    codCidade: 2204907,
    cidade: "ISAIAS COELHO",
    estado: "PI",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 401.73199462890625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataPI;
