let dataPE = [
  {
    anoCenso: 2013,
    cod: 26158531,
    nome: "C INT DE EDUCACAO INFANTIL BEM ME QUER",
    codCidade: 2605459,
    cidade: "FERNANDO DE NORONHA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26123150,
    nome: "CAIC CREUSA BARRETO DORNELAS CAMARA",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26011018,
    nome: "CEJA CENTRO DE EDUCACAO DE JOVENS E ADULTOS",
    codCidade: 2612208,
    cidade: "SALGUEIRO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26117916,
    nome: "CEJA POETA JOAQUIM CARDOZO",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26121824,
    nome: "CEJA VALDEMAR DE OLIVEIRA",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26024659,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO",
    codCidade: 2601201,
    cidade: "ARCOVERDE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26153688,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO DO RECIFE - CAEER",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26053756,
    nome: "CENTRO DE ATENDIMENTO EDUCACIONAL ESPECIALIZADO ROTARY CLUB CARUARU",
    codCidade: 2604106,
    cidade: "CARUARU",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26033836,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS JOAO BARRACAO",
    codCidade: 2611101,
    cidade: "PETROLINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26133753,
    nome: "CENTRO DE REAB E EDUCACAO ESPECIAL LIONS CLUB",
    codCidade: 2606002,
    cidade: "GARANHUNS",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26069202,
    nome: "CENTRO DE REABILITACAO E EDUCACAO ESPECIAL",
    codCidade: 2608909,
    cidade: "LIMOEIRO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26024667,
    nome: "CENTRO ENS SUP CICERO FRANKLIN CORDEIRO",
    codCidade: 2601201,
    cidade: "ARCOVERDE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26182955,
    nome: "CENTRO TECNOLOGICO DE CULTURA DIGITAL",
    codCidade: 2609600,
    cidade: "OLINDA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26181886,
    nome: "CENTRO TECNOLOGICO DO AGRESTE",
    codCidade: 2604106,
    cidade: "CARUARU",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26179440,
    nome: "CENTRO TECNOLOGICO DO ARARIPE",
    codCidade: 2601102,
    cidade: "ARARIPINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26180871,
    nome: "CENTRO TECNOLOGICO DO PAJEU",
    codCidade: 2613909,
    cidade: "SERRA TALHADA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26181720,
    nome: "CENTRO TECNOLOGICO INSTITUTO DE LATICINIOS DO AGRESTE",
    codCidade: 2606002,
    cidade: "GARANHUNS",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26014564,
    nome: "COL NORMAL EST DE AFOGADOS DA INGAZEIRA",
    codCidade: 2600104,
    cidade: "AFOGADOS DA INGAZEIRA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26122120,
    nome: "COLEGIO DA POLICIA MILITAR DE PERNAMBUCO",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 7.0,
    idebAF: 5.699999809265137,
    enemMediaGeral: 579.4840087890625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26135396,
    nome: "CONSERVATORIO PERNAMBUCANO DE MUSICA",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26437724,
    nome: "DOM HELDER CAMARA",
    codCidade: 2606804,
    cidade: "IGARASSU",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26132230,
    nome: "ESC APLICACAO PROFA IVONITA ALVES GUERRA",
    codCidade: 2606002,
    cidade: "GARANHUNS",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 6.199999809265137,
    enemMediaGeral: 571.1599731445312,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26127270,
    nome: "ESC CARLOS ALBERTO GONCALVES DE ALMEIDA",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.800000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26014572,
    nome: "ESC CONEGO JOAO LEITE GONCALVES DE ANDRADE",
    codCidade: 2600104,
    cidade: "AFOGADOS DA INGAZEIRA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26087880,
    nome: "ESC DEPUTADO JOAO TEOBALDO DE AZEVEDO",
    codCidade: 2604007,
    cidade: "CARPINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.799999952316284,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26130947,
    nome: "ESC DOMINGOS ALBUQUERQUE",
    codCidade: 2607208,
    cidade: "IPOJUCA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26075733,
    nome: "ESC DUQUE DE CAXIAS ENSINO FUNDAMENTAL E MEDIO",
    codCidade: 2606002,
    cidade: "GARANHUNS",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26130149,
    nome: "ESC EMIDIO CAVALCANTI DE ALBUQUERQUE",
    codCidade: 2602902,
    cidade: "CABO DE SANTO AGOSTINHO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26140128,
    nome: "ESC FERNANDO IDALINO BEZERRA ENSINO MEDIO",
    codCidade: 2611101,
    cidade: "PETROLINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26107597,
    nome: "ESC FRANCISCO DE PAULA CORREIA DE ARAUJO",
    codCidade: 2603454,
    cidade: "CAMARAGIBE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26020998,
    nome: "ESC IRMA ELIZABETH ENS FUND E MEDIO",
    codCidade: 2613909,
    cidade: "SERRA TALHADA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26034441,
    nome: "ESC MAR ANTONIO ALVES FILHO",
    codCidade: 2611101,
    cidade: "PETROLINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 476.05999755859375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26153491,
    nome: "ESC MON MAN LEONARDO DE BARROS BARRETO",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.5,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26121638,
    nome: "ESC MONSENHOR FRANCISCO SALLES",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26004453,
    nome: "ESC NOSSA SENHORA DO BOM CONSELHO",
    codCidade: 2606309,
    cidade: "GRANITO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26004488,
    nome: "ESC NOSSA SRA DO SOCORRO",
    codCidade: 2607307,
    cidade: "IPUBI",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26105497,
    nome: "ESC ORFANATO SAGRADO CORACAO DE JESUS",
    codCidade: 2606804,
    cidade: "IGARASSU",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26121670,
    nome: "ESC POETA MANUEL BANDEIRA",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26123576,
    nome: "ESC PRES HUMBERTO CASTELLO BRANCO",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 488.260009765625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26122880,
    nome: "ESC PRESIDENTE ARTHUR DA COSTA E SILVA",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26008882,
    nome: "ESC PROF ANTONIA MARINHO APOLINARIO",
    codCidade: 2615607,
    cidade: "TRINDADE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26074923,
    nome: "ESC PROF CLARICE GODOY ENS FUNDAMENTAL",
    codCidade: 2604700,
    cidade: "CORRENTES",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26075920,
    nome: "ESC PROF ELVIRA VIANA ENSINO FUNDAMENTAL E MEDIO",
    codCidade: 2606002,
    cidade: "GARANHUNS",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26091925,
    nome: "ESC PROF JOAO ROBERTO MOREIRA",
    codCidade: 2615300,
    cidade: "TIMBAUBA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.200000047683716,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26097591,
    nome: "ESC PROF JOAQUIM AUGUSTO NORONHA FILHO",
    codCidade: 2601409,
    cidade: "BARREIROS",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26124807,
    nome: "ESC PROF JOSE VICENTE BARBOSA",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26035111,
    nome: "ESC PROF MANOEL XAVIER PAES BARRETO",
    codCidade: 2611101,
    cidade: "PETROLINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26019949,
    nome: "ESC PROF SEBASTIAO FERREIRA RABELO SOBRINHO",
    codCidade: 2613602,
    cidade: "SAO JOSE DO EGITO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.400000095367432,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26113872,
    nome: "ESC PROFA DEANNA CLARCK XAVIER",
    codCidade: 2609600,
    cidade: "OLINDA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26063948,
    nome: "ESC PROFA Mª DO SOCORRO ARAGAO FLORENCIO",
    codCidade: 2612505,
    cidade: "SANTA CRUZ DO CAPIBARIBE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26116391,
    nome: "ESC PROFA ZULMIRA DE PAULA ALMEIDA",
    codCidade: 2610707,
    cidade: "PAULISTA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26116383,
    nome: "ESC PROFESSORA MARIA ALVES MACHADO",
    codCidade: 2610707,
    cidade: "PAULISTA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26106337,
    nome: "ESC PROFª GERCINA FERNANDES RODRIGUES",
    codCidade: 2607752,
    cidade: "ITAPISSUMA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26089947,
    nome: "ESC SEVERINO GOUVEIA DE LIMA",
    codCidade: 2607802,
    cidade: "ITAQUITINGA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26009323,
    nome: "ESC VALDICLEIWTSON DA SILVA MENEZES",
    codCidade: 2604304,
    cidade: "CEDRO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26011352,
    nome: "ESC0LA PROFESSORA MAURINA RODRIGUES DOS SANTOS",
    codCidade: 2612208,
    cidade: "SALGUEIRO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26129566,
    nome: "ESCOLA 10 DE AGOSTO",
    codCidade: 2613701,
    cidade: "SAO LOURENCO DA MATA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 439.91400146484375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26056550,
    nome: "ESCOLA AARAO LINS DE ANDRADE",
    codCidade: 2606408,
    cidade: "GRAVATA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26092298,
    nome: "ESCOLA AGAMENON MAGALHAES",
    codCidade: 2615508,
    cidade: "TRACUNHAEM",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26123479,
    nome: "ESCOLA ALBERTO TORRES",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 482.31201171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26110148,
    nome: "ESCOLA ALFREDO TENORIO",
    codCidade: 2607901,
    cidade: "JABOATAO DOS GUARARAPES",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.9000000953674316,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26121840,
    nome: "ESCOLA ALMIRANTE TAMANDARE",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26110849,
    nome: "ESCOLA ALTO DOS GUARARAPES",
    codCidade: 2607901,
    cidade: "JABOATAO DOS GUARARAPES",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26088258,
    nome: "ESCOLA ALUISIO GERMANO",
    codCidade: 2604007,
    cidade: "CARPINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 462.1300048828125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26110857,
    nome: "ESCOLA ALZIRA DA FONSECA BREUEL",
    codCidade: 2607901,
    cidade: "JABOATAO DOS GUARARAPES",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26048078,
    nome: "ESCOLA AMALIA CAVALCANTI DA COSTA LIMA",
    codCidade: 2610806,
    cidade: "PEDRA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26029812,
    nome: "ESCOLA AMARO LAFAYETTE",
    codCidade: 2614105,
    cidade: "SERTANIA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26074591,
    nome: "ESCOLA AMELIA GUEIROS LEITE",
    codCidade: 2603702,
    cidade: "CANHOTINHO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26111411,
    nome: "ESCOLA AMOR DIVINO",
    codCidade: 2607901,
    cidade: "JABOATAO DOS GUARARAPES",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 1.600000023841858,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26091879,
    nome: "ESCOLA ANA EUFRASIA CABRAL DE MOURA",
    codCidade: 2615300,
    cidade: "TIMBAUBA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 5.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26065401,
    nome: "ESCOLA ANA FAUSTINA",
    codCidade: 2614501,
    cidade: "SURUBIM",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26125986,
    nome: "ESCOLA ANA MALTA DA COSTA AZEVEDO",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26010100,
    nome: "ESCOLA ANDRE NUNES",
    codCidade: 2609303,
    cidade: "MIRANDIBA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26089190,
    nome: "ESCOLA ANDRE VIDAL DE NEGREIROS",
    codCidade: 2606200,
    cidade: "GOIANA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26047845,
    nome: "ESCOLA ANETE VALE DE OLIVEIRA",
    codCidade: 2610806,
    cidade: "PEDRA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26131668,
    nome: "ESCOLA ANIBAL CARDOSO",
    codCidade: 2607208,
    cidade: "IPOJUCA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26001624,
    nome: "ESCOLA ANIZIO RODRIGUES COELHO",
    codCidade: 2601102,
    cidade: "ARARIPINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26054019,
    nome: "ESCOLA ANTONIA CAVALCANTI DE ALBUQUERQUE",
    codCidade: 2604106,
    cidade: "CARUARU",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26035340,
    nome: "ESCOLA ANTONIO CASSIMIRO",
    codCidade: 2611101,
    cidade: "PETROLINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26030950,
    nome: "ESCOLA ANTONIO CAVALCANTI FILHO",
    codCidade: 2600203,
    cidade: "AFRANIO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26107546,
    nome: "ESCOLA ANTONIO CORREIA DE ARAUJO",
    codCidade: 2603454,
    cidade: "CAMARAGIBE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26090767,
    nome: "ESCOLA ANTONIO COUTINHO",
    codCidade: 2609006,
    cidade: "MACAPARANA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26037726,
    nome: "ESCOLA ANTONIO DE AMORIM COELHO",
    codCidade: 2608750,
    cidade: "LAGOA GRANDE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26068508,
    nome: "ESCOLA ANTONIO INACIO",
    codCidade: 2605400,
    cidade: "FEIRA NOVA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26024721,
    nome: "ESCOLA ANTONIO JAPIASSU",
    codCidade: 2601201,
    cidade: "ARCOVERDE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26034298,
    nome: "ESCOLA ANTONIO PADILHA",
    codCidade: 2611101,
    cidade: "PETROLINA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26113198,
    nome: "ESCOLA ANTONIO SOUTO FILHO",
    codCidade: 2609600,
    cidade: "OLINDA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 490.0039978027344,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26020963,
    nome: "ESCOLA ANTONIO TIMOTEO",
    codCidade: 2613909,
    cidade: "SERRA TALHADA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26011050,
    nome: "ESCOLA ANTONIO VIEIRA DE BARROS",
    codCidade: 2612208,
    cidade: "SALGUEIRO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26113210,
    nome: "ESCOLA ARGENTINA CASTELLO BRANCO",
    codCidade: 2609600,
    cidade: "OLINDA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26023245,
    nome: "ESCOLA ARNALDO ALVES CAVALCANTI - ENSINO FUNDAMENTAL MEDIO E NORMAL MEDIO",
    codCidade: 2614600,
    cidade: "TABIRA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26089530,
    nome: "ESCOLA ARRUDA CAMARA",
    codCidade: 2607653,
    cidade: "ITAMBE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 457.1679992675781,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26111853,
    nome: "ESCOLA ARTUR MENDONCA",
    codCidade: 2609402,
    cidade: "MORENO",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0,
    enemMediaGeral: 446.6260070800781,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26101157,
    nome: "ESCOLA ASCENSO FERREIRA",
    codCidade: 2610004,
    cidade: "PALMARES",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26124440,
    nome: "ESCOLA ASSIS CHATEAUBRIAND",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26098210,
    nome: "ESCOLA ATHAYDE ACCIOLY LINS",
    codCidade: 2604205,
    cidade: "CATENDE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26113236,
    nome: "ESCOLA AUREA DE MOURA CAVALCANTI",
    codCidade: 2609600,
    cidade: "OLINDA",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 2.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26105187,
    nome: "ESCOLA BARAO DE VERA CRUZ",
    codCidade: 2606804,
    cidade: "IGARASSU",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26123720,
    nome: "ESCOLA BARAO DO BONITO",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 26127571,
    nome: "ESCOLA BARROS CARVALHO",
    codCidade: 2611606,
    cidade: "RECIFE",
    estado: "PE",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.0,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataPE;
