let dataAL = [
  {
    anoCenso: 2013,
    cod: 27237400,
    nome: "CAS - CENTRO DE ATENDIMENTO AS PESSOAS COM SURDEZ",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27013880,
    nome: "CENTRO DE EDUCAC DE JOVENS E ADULTOS REMY MAIA",
    codCidade: 2706307,
    cidade: "PALMEIRA DOS INDIOS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27224546,
    nome: "CENTRO EDC DE JOVENS E ADULTOS PAULO FREIRE - CEJA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27218163,
    nome: "CENTRO ESTADUAL DE EDUCACAO PROFª WANDETTE GOMES DE CASTRO",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27044211,
    nome: "ESC ESTADUAL DE ED BASICA PEDRO JOAQUIM DE JESUS",
    codCidade: 2709152,
    cidade: "TEOTONIO VILELA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27038734,
    nome: "ESC ESTADUAL PROF EDMILSON DE VASCONCELOS PONTES",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 1.600000023841858,
    enemMediaGeral: 488.08599853515625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27045234,
    nome: "ESCOLA DE 1º E 2º GRAUS DR ALCIDES ANDRADE",
    codCidade: 2706703,
    cidade: "PENEDO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27016366,
    nome: "ESCOLA ESTADUAL ADRIANO JORGE",
    codCidade: 2700300,
    cidade: "ARAPIRACA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.699999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27035646,
    nome: "ESCOLA ESTADUAL ALFREDO GASPAR DE MENDONCA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27014959,
    nome: "ESCOLA ESTADUAL ALMEIDA CAVALCANTI",
    codCidade: 2706307,
    cidade: "PALMEIRA DOS INDIOS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27033210,
    nome: "ESCOLA ESTADUAL AMBROSIO LIRA",
    codCidade: 2706505,
    cidade: "PASSO DE CAMARAGIBE",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27043622,
    nome: "ESCOLA ESTADUAL ANA LINS",
    codCidade: 2708600,
    cidade: "SAO MIGUEL DOS CAMPOS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27013995,
    nome: "ESCOLA ESTADUAL ANTONIA MACEDO",
    codCidade: 2706307,
    cidade: "PALMEIRA DOS INDIOS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27215024,
    nome: "ESCOLA ESTADUAL AQUILINA BULHOES BARROS",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27027597,
    nome: "ESCOLA ESTADUAL ARISTHEU DE ANDRADE",
    codCidade: 2702108,
    cidade: "COLONIA LEOPOLDINA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27016390,
    nome: "ESCOLA ESTADUAL AURINO MACIEL",
    codCidade: 2700300,
    cidade: "ARAPIRACA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27032566,
    nome: "ESCOLA ESTADUAL BATISTA ACIOLY",
    codCidade: 2704500,
    cidade: "MARAGOGI",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27006050,
    nome: "ESCOLA ESTADUAL BRAULIO CAVALCANTE",
    codCidade: 2706406,
    cidade: "PAO DE ACUCAR",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27035697,
    nome: "ESCOLA ESTADUAL CAMPOS TEIXEIRA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 441.7300109863281,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27038491,
    nome: "ESCOLA ESTADUAL CAPITAO ALVARO VICTOR",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27023583,
    nome: "ESCOLA ESTADUAL CARLOS LYRA",
    codCidade: 2708303,
    cidade: "SAO JOSE DA LAJE",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27038467,
    nome: "ESCOLA ESTADUAL CINCINATO PINTO",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27033384,
    nome: "ESCOLA ESTADUAL CIRIDIAO DURVAL",
    codCidade: 2707404,
    cidade: "PORTO DE PEDRAS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27034240,
    nome: "ESCOLA ESTADUAL CONEGO AMANDO GUSMAO",
    codCidade: 2702207,
    cidade: "COQUEIRO SECO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27009904,
    nome: "ESCOLA ESTADUAL CONEGO JASSON SOUTO",
    codCidade: 2703403,
    cidade: "JACARE DOS HOMENS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27045420,
    nome: "ESCOLA ESTADUAL CONEGO TEOTONIO RIBEIRO",
    codCidade: 2706703,
    cidade: "PENEDO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27010074,
    nome: "ESCOLA ESTADUAL CONSTANCA DE GOES MONTEIRO",
    codCidade: 2704401,
    cidade: "MAJOR ISIDORO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27035700,
    nome: "ESCOLA ESTADUAL CORONEL FRANCISCO ALVES MATA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.300000190734863,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27045757,
    nome: "ESCOLA ESTADUAL CORREIA TITARA E ANEXOS",
    codCidade: 2706802,
    cidade: "PIACABUCU",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27032280,
    nome: "ESCOLA ESTADUAL D ELISEU MARIA GOMES OLIVEIRA",
    codCidade: 2703601,
    cidade: "JAPARATINGA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 431.1619873046875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27038505,
    nome: "ESCOLA ESTADUAL D PEDRO II",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.5999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27046303,
    nome: "ESCOLA ESTADUAL D SANTA BULHOES",
    codCidade: 2707503,
    cidade: "PORTO REAL DO COLEGIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27036057,
    nome: "ESCOLA ESTADUAL DE CEGOS CYRO ACCIOLY",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27009998,
    nome: "ESCOLA ESTADUAL DE JARAMATAIA",
    codCidade: 2703700,
    cidade: "JARAMATAIA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27010767,
    nome: "ESCOLA ESTADUAL DE MONTEIROPOLIS",
    codCidade: 2705408,
    cidade: "MONTEIROPOLIS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.200000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27008827,
    nome: "ESCOLA ESTADUAL DE RIACHO GRANDE",
    codCidade: 2708956,
    cidade: "SENADOR RUI PALMEIRA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27004376,
    nome: "ESCOLA ESTADUAL DE XINGO I EEXI",
    codCidade: 2707107,
    cidade: "PIRANHAS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27004368,
    nome: "ESCOLA ESTADUAL DE XINGO II- EEX-II",
    codCidade: 2707107,
    cidade: "PIRANHAS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.4000000953674316,
    idebAF: 1.899999976158142,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27029336,
    nome: "ESCOLA ESTADUAL DELMO FERREIRA DA SILVA",
    codCidade: 2703908,
    cidade: "JUNDIA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 436.5780029296875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27216136,
    nome: "ESCOLA ESTADUAL DEP GUILHERMINO DE OLIVEIRA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27021637,
    nome: "ESCOLA ESTADUAL DEPUTADO JOSE MEDEIROS",
    codCidade: 2709202,
    cidade: "TRAIPU",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27035883,
    nome: "ESCOLA ESTADUAL DEPUTADO NENOI PINTO",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27036448,
    nome: "ESCOLA ESTADUAL DEPUTADO RUBENS CANUTO",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27011577,
    nome: "ESCOLA ESTADUAL DESEMBARGADOR AUGUSTO COSTA",
    codCidade: 2706000,
    cidade: "OLIVENCA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27035875,
    nome: "ESCOLA ESTADUAL DOM OTAVIO BARBOSA AGUIAR",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27000710,
    nome: "ESCOLA ESTADUAL DOMINGOS MOEDA",
    codCidade: 2700102,
    cidade: "AGUA BRANCA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27030725,
    nome: "ESCOLA ESTADUAL DR ARTUR LOPES FERREIRA",
    codCidade: 2705507,
    cidade: "MURICI",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27024059,
    nome: "ESCOLA ESTADUAL DR CARLOS GOMES DE BARROS",
    codCidade: 2709301,
    cidade: "UNIAO DOS PALMARES",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27004490,
    nome: "ESCOLA ESTADUAL DR EMILIO DE MAIA",
    codCidade: 2701803,
    cidade: "CARNEIROS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27035948,
    nome: "ESCOLA ESTADUAL DR FERNANDES LIMA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 490.656005859375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27220052,
    nome: "ESCOLA ESTADUAL DR FRANCISCO MELO",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27038297,
    nome: "ESCOLA ESTADUAL DR JOSE MARIA CORREIA DAS NEVES",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27216667,
    nome: "ESCOLA ESTADUAL DR JOSE MARIA DE MELO",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.5999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27016404,
    nome: "ESCOLA ESTADUAL DR JOSE TAVARES",
    codCidade: 2700300,
    cidade: "ARAPIRACA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27038556,
    nome: "ESCOLA ESTADUAL DR MIGUEL GUEDES NOGUEIRA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27024067,
    nome: "ESCOLA ESTADUAL DR PAULO DE CASTRO SARMENTO",
    codCidade: 2709301,
    cidade: "UNIAO DOS PALMARES",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27036561,
    nome: "ESCOLA ESTADUAL DRª EUNICE DE LEMOS CAMPOS",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27014088,
    nome: "ESCOLA ESTADUAL ESTADO DE NOVA JERSEY",
    codCidade: 2706307,
    cidade: "PALMEIRA DOS INDIOS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27026337,
    nome: "ESCOLA ESTADUAL FLORIANO PEIXOTO",
    codCidade: 2700409,
    cidade: "ATALAIA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27045404,
    nome: "ESCOLA ESTADUAL FREITAS MELRO",
    codCidade: 2706703,
    cidade: "PENEDO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27045250,
    nome: "ESCOLA ESTADUAL GABINO BESOURO",
    codCidade: 2706703,
    cidade: "PENEDO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27014029,
    nome: "ESCOLA ESTADUAL GRACILIANO RAMOS",
    codCidade: 2706307,
    cidade: "PALMEIRA DOS INDIOS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27045684,
    nome: "ESCOLA ESTADUAL HERMILIO DE FREITAS MELRO",
    codCidade: 2706703,
    cidade: "PENEDO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.400000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27042251,
    nome: "ESCOLA ESTADUAL INACIO DE CARVALHO",
    codCidade: 2702306,
    cidade: "CORURIPE",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27036464,
    nome: "ESCOLA ESTADUAL JARSEN COSTA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27003892,
    nome: "ESCOLA ESTADUAL JOAO FRANCISCO SOARES",
    codCidade: 2705804,
    cidade: "OLHO D AGUA DO CASADO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27040771,
    nome: "ESCOLA ESTADUAL JOAO MORAIS CAVALCANTE",
    codCidade: 2707701,
    cidade: "RIO LARGO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27035581,
    nome: "ESCOLA ESTADUAL JOAO PAULO II",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27039013,
    nome: "ESCOLA ESTADUAL JORNALISTA RAUL LIMA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27029166,
    nome: "ESCOLA ESTADUAL JOSE RIBEIRO CAMINHA",
    codCidade: 2701357,
    cidade: "CAMPESTRE",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27008479,
    nome: "ESCOLA ESTADUAL JOSE SOARES FILHO",
    codCidade: 2708402,
    cidade: "SAO JOSE DA TAPERA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 1.2999999523162842,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27041603,
    nome: "ESCOLA ESTADUAL JOSEFA CAVALCANTE SURUAGY",
    codCidade: 2701001,
    cidade: "BOCA DA MATA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27026370,
    nome: "ESCOLA ESTADUAL JUVENAL LOPES F DE OMENA",
    codCidade: 2701100,
    cidade: "BRANQUINHA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27016480,
    nome: "ESCOLA ESTADUAL LIONS CLUB",
    codCidade: 2700300,
    cidade: "ARAPIRACA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5,
    enemMediaGeral: 454.2760009765625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27007162,
    nome: "ESCOLA ESTADUAL LIONS CLUB",
    codCidade: 2708006,
    cidade: "SANTANA DO IPANEMA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27036758,
    nome: "ESCOLA ESTADUAL LIONS MACEIO PAJUCARA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.200000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27008452,
    nome: "ESCOLA ESTADUAL LUCILO JOSE RIBEIRO",
    codCidade: 2708402,
    cidade: "SAO JOSE DA TAPERA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27001237,
    nome: "ESCOLA ESTADUAL LUIZ BASTOS",
    codCidade: 2701605,
    cidade: "CANAPI",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27012166,
    nome: "ESCOLA ESTADUAL LUIZ DUARTE",
    codCidade: 2702553,
    cidade: "ESTRELA DE ALAGOAS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27028380,
    nome: "ESCOLA ESTADUAL MAJOR LUIZ CAVALCANTE",
    codCidade: 2703502,
    cidade: "JACUIPE",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27023516,
    nome: "ESCOLA ESTADUAL MANOEL DE MATOS",
    codCidade: 2708105,
    cidade: "SANTANA DO MUNDAU",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27018350,
    nome: "ESCOLA ESTADUAL MANOEL LEANDRO DE LIRA",
    codCidade: 2702603,
    cidade: "FEIRA GRANDE",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27014037,
    nome: "ESCOLA ESTADUAL MANOEL PASSOS LIMA",
    codCidade: 2706307,
    cidade: "PALMEIRA DOS INDIOS",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.200000047683716,
    idebAF: 1.7000000476837158,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27005852,
    nome: "ESCOLA ESTADUAL MANOEL PEREIRA FILHO",
    codCidade: 2706208,
    cidade: "PALESTINA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27226948,
    nome: "ESCOLA ESTADUAL MARCELO RESENDE",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27216608,
    nome: "ESCOLA ESTADUAL MARCOS ANTONIO C SILVA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27012638,
    nome: "ESCOLA ESTADUAL MARIA AMELIA SAMPAIO LUZ",
    codCidade: 2703106,
    cidade: "IGACI",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27225569,
    nome: "ESCOLA ESTADUAL MARIA DAS GRACAS DE SA TEIXEIRA",
    codCidade: 2704302,
    cidade: "MACEIO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.0,
    enemMediaGeral: 462.2239990234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27029123,
    nome: "ESCOLA ESTADUAL MARIO GOMES DE BARROS",
    codCidade: 2703809,
    cidade: "JOAQUIM GOMES",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27011844,
    nome: "ESCOLA ESTADUAL MARQUES DA SILVA",
    codCidade: 2700805,
    cidade: "BELEM",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27034070,
    nome: "ESCOLA ESTADUAL MISAEL GONCALVES FERREIRA",
    codCidade: 2700607,
    cidade: "BARRA DE SAO MIGUEL",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 460.4540100097656,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27024016,
    nome: "ESCOLA ESTADUAL MONSENHOR CLOVIS DUARTE DE BARROS",
    codCidade: 2709301,
    cidade: "UNIAO DOS PALMARES",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27022838,
    nome: "ESCOLA ESTADUAL MONSENHOR LUIZ CARLOS DE OLIVEIRA BARBOSA",
    codCidade: 2703007,
    cidade: "IBATEGUARA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27025519,
    nome: "ESCOLA ESTADUAL MONSENHOR MACHADO",
    codCidade: 2709400,
    cidade: "VICOSA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.299999952316284,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27000095,
    nome: "ESCOLA ESTADUAL MONSENHOR SEBASTIAO ALVES BEZERRA",
    codCidade: 2700102,
    cidade: "AGUA BRANCA",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 448.1579895019531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27021645,
    nome: "ESCOLA ESTADUAL MORENO BRANDAO",
    codCidade: 2709202,
    cidade: "TRAIPU",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27031063,
    nome: "ESCOLA ESTADUAL NOSSA SENHORA DA APRESENTACAO",
    codCidade: 2707305,
    cidade: "PORTO CALVO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27018962,
    nome: "ESCOLA ESTADUAL OLIMPIA TENORIO LIMA",
    codCidade: 2702900,
    cidade: "GIRAU DO PONCIANO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27039960,
    nome: "ESCOLA ESTADUAL OLIVEIRA E SILVA",
    codCidade: 2706901,
    cidade: "PILAR",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 27040836,
    nome: "ESCOLA ESTADUAL OSORIA DE MOURA LIMA",
    codCidade: 2707701,
    cidade: "RIO LARGO",
    estado: "AL",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataAL;
