
let dataSP =
    [
      {
        "anoCenso": 2013,
        "cod": 35923370,
        "nome": "16 DE JULHO",
        "codCidade": 3547809,
        "cidade": "SANTO ANDRE",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35033881,
        "nome": "17 DE SETEMBRO",
        "codCidade": 3540002,
        "cidade": "POMPEIA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35032220,
        "nome": "18 DE JUNHO",
        "codCidade": 3541307,
        "cidade": "PRESIDENTE EPITACIO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 475.0400085449219,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35009283,
        "nome": "20 DE AGOSTO",
        "codCidade": 3548708,
        "cidade": "SAO BERNARDO DO CAMPO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.199999809265137,
        "enemMediaGeral": 508.2760009765625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35026189,
        "nome": "21 DE ABRIL",
        "codCidade": 3527108,
        "cidade": "LINS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35018533,
        "nome": "31 DE MARCO",
        "codCidade": 3509502,
        "cidade": "CAMPINAS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35031264,
        "nome": "9 DE JULHO",
        "codCidade": 3514403,
        "cidade": "DRACENA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.0,
        "enemMediaGeral": 509.39599609375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35024880,
        "nome": "9 DE JULHO",
        "codCidade": 3553708,
        "cidade": "TAQUARITINGA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.900000095367432,
        "enemMediaGeral": 468.85198974609375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35909026,
        "nome": "A HEBRAICA",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.5,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35022100,
        "nome": "ABDALLA MIGUEL",
        "codCidade": 3552700,
        "cidade": "TABATINGA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.099999904632568,
        "enemMediaGeral": 493.4419860839844,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35440620,
        "nome": "ABDIAS DO NASCIMENTO ETEC",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 534.1640014648438,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35038885,
        "nome": "ABDIEL LOPES MONTEIRO PROF",
        "codCidade": 3543006,
        "cidade": "RIBEIRAO BRANCO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35033820,
        "nome": "ABEL AUGUSTO FRAGATA",
        "codCidade": 3529005,
        "cidade": "MARILIA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35024399,
        "nome": "ABEL DOS REIS",
        "codCidade": 3510906,
        "cidade": "CASSIA DOS COQUEIROS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35041506,
        "nome": "ABELARDO CESAR DOUTOR",
        "codCidade": 3515186,
        "cidade": "ESPIRITO SANTO DO PINHAL",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.5,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35021246,
        "nome": "ABIGAIL DE AZEVEDO GRILLO PROFESSOR",
        "codCidade": 3538709,
        "cidade": "PIRACICABA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35022767,
        "nome": "ABILIO ALVES MARQUES",
        "codCidade": 3506102,
        "cidade": "BEBEDOURO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.900000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35015106,
        "nome": "ABILIO FONTES PROF",
        "codCidade": 3522307,
        "cidade": "ITAPETININGA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35022603,
        "nome": "ABILIO MANOEL",
        "codCidade": 3506102,
        "cidade": "BEBEDOURO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 481.614013671875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35903188,
        "nome": "ABILIO RAPOSO FERRAZ JUNIOR",
        "codCidade": 3521804,
        "cidade": "ITAI",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35049098,
        "nome": "ABRAHAO DE MORAES PROFESSOR",
        "codCidade": 3522208,
        "cidade": "ITAPECERICA DA SERRA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35012051,
        "nome": "ABRAHAO JACOB LAFER DOUTOR",
        "codCidade": 3541000,
        "cidade": "PRAIA GRANDE",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.900000095367432,
        "enemMediaGeral": 497.09600830078125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35907224,
        "nome": "ABRANCHE JOSE PROF",
        "codCidade": 3502804,
        "cidade": "ARACATUBA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35904831,
        "nome": "ABRAO BENJAMIM PROF",
        "codCidade": 3513405,
        "cidade": "CRUZEIRO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35016196,
        "nome": "ACACIO DE VASCONCELLOS CAMARGO PROFESSOR",
        "codCidade": 3552205,
        "cidade": "SOROCABA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35901179,
        "nome": "ACACIO DOS SANTOS PELEGRINI PROFESSOR",
        "codCidade": 3510807,
        "cidade": "CASA BRANCA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.400000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35028502,
        "nome": "ACHILES MALVEZZI",
        "codCidade": 3540804,
        "cidade": "POTIRENDABA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 498.5719909667969,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35900576,
        "nome": "ACHILES RODRIGUES PROFESSOR",
        "codCidade": 3556404,
        "cidade": "VARGEM GRANDE DO SUL",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35015817,
        "nome": "ACYLINO AMARAL GURGEL PROF",
        "codCidade": 3545209,
        "cidade": "SALTO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35919019,
        "nome": "ADA CARIANI AVALONE PROFA",
        "codCidade": 3506003,
        "cidade": "BAURU",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35028685,
        "nome": "ADAHIR GUIMARAES FOGACA PROFESSOR",
        "codCidade": 3549805,
        "cidade": "SAO JOSE DO RIO PRETO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35048823,
        "nome": "ADAIL JARBAS DUCLOS",
        "codCidade": 3516408,
        "cidade": "FRANCO DA ROCHA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.699999809265137,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35008936,
        "nome": "ADAIL LUIZ MILLER DOUTOR",
        "codCidade": 3548708,
        "cidade": "SAO BERNARDO DO CAMPO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 490.7799987792969,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35910892,
        "nome": "ADAIL NUNES DA SILVA DR ETE",
        "codCidade": 3553708,
        "cidade": "TAQUARITINGA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 553.7219848632812,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35914800,
        "nome": "ADALBERTO MECCA SAMPAIO PROFESSOR",
        "codCidade": 3510609,
        "cidade": "CARAPICUIBA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.199999809265137,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35018284,
        "nome": "ADALBERTO NASCIMENTO",
        "codCidade": 3509502,
        "cidade": "CAMPINAS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35018260,
        "nome": "ADALBERTO PRADO E SILVA PROFESSOR",
        "codCidade": 3509502,
        "cidade": "CAMPINAS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 481.77801513671875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35034162,
        "nome": "ADALGISA CAVEZZALE DE CAMPOS PROFA",
        "codCidade": 3535309,
        "cidade": "PALMITAL",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.800000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35903395,
        "nome": "ADALGISA DE SAO JOSE GUALTIERI",
        "codCidade": 3516200,
        "cidade": "FRANCA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 7.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35002537,
        "nome": "ADALGISA MOREIRA PIRES PROFESSORA",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35004194,
        "nome": "ADALGIZA SEGURADO DA SILVEIRA PROFESSORA",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35005654,
        "nome": "ADAMASTOR BAPTISTA PROF",
        "codCidade": 3516408,
        "cidade": "FRANCO DA ROCHA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.5,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35008576,
        "nome": "ADAMASTOR DE CARVALHO PROFESSOR",
        "codCidade": 3547809,
        "cidade": "SANTO ANDRE",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35007730,
        "nome": "ADELAIDE ESCOBAR BUENO PROFESSORA",
        "codCidade": 3529401,
        "cidade": "MAUA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.400000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35002549,
        "nome": "ADELAIDE FERRAZ DE OLIVEIRA PROFA",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35924830,
        "nome": "ADELAIDE MARIA DE BARROS PROFESSORA",
        "codCidade": 3530607,
        "cidade": "MOGI DAS CRUZES",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35049189,
        "nome": "ADELAIDE PATROCINIO DOS SANTOS",
        "codCidade": 3541000,
        "cidade": "PRAIA GRANDE",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.800000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35925998,
        "nome": "ADELAIDE ROSA FERNANDES MACHADO DE SOUZA PROFESSORA",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35046826,
        "nome": "ADELIA CHUCRI NEME",
        "codCidade": 3549904,
        "cidade": "SAO JOSE DOS CAMPOS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35022573,
        "nome": "ADELIA FRASCINO DONA",
        "codCidade": 3540200,
        "cidade": "PONTAL",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35004303,
        "nome": "ADELINA ISSA ASHCAR",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.199999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35911252,
        "nome": "ADELINA PASQUINO CASSIS PROFA",
        "codCidade": 3516200,
        "cidade": "FRANCA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35027054,
        "nome": "ADELINO BERTANI",
        "codCidade": 3529658,
        "cidade": "MESOPOLIS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 6.0,
        "enemMediaGeral": 433.1419982910156,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35911203,
        "nome": "ADELINO CHUBA GUIMARO PROFESSOR",
        "codCidade": 3541307,
        "cidade": "PRESIDENTE EPITACIO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35003232,
        "nome": "ADELINO JOSE DA SILVA D AZEVEDO PROF",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35030442,
        "nome": "ADELINO PETERS",
        "codCidade": 3537305,
        "cidade": "PENAPOLIS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35017802,
        "nome": "ADELIO FERRAZ DE CASTRO",
        "codCidade": 3556354,
        "cidade": "VARGEM",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35001351,
        "nome": "ADEMAR HIROSHI SUDA PROF",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.800000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35020734,
        "nome": "ADEMAR VIEIRA PISCO",
        "codCidade": 3547007,
        "cidade": "SANTA MARIA DA SERRA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35923886,
        "nome": "ADENILSON DOS SANTOS FRANCO PROFESSOR",
        "codCidade": 3552809,
        "cidade": "TABOAO DA SERRA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.0,
        "enemMediaGeral": 489.27801513671875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35903536,
        "nome": "ADERVAL DA SILVA PROF",
        "codCidade": 3529302,
        "cidade": "MATAO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.199999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35003244,
        "nome": "ADHEMAR ANTONIO PRADO PROFESSOR",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35006592,
        "nome": "ADHEMAR BOLINA PROFESSOR",
        "codCidade": 3506607,
        "cidade": "BIRITIBA-MIRIM",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35042286,
        "nome": "ADHERBAL DE CASTRO PROF",
        "codCidade": 3524402,
        "cidade": "JACAREI",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35015088,
        "nome": "ADHERBAL DE PAULA FERREIRA",
        "codCidade": 3522307,
        "cidade": "ITAPETININGA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 6.300000190734863,
        "enemMediaGeral": 504.3160095214844,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35039962,
        "nome": "ADIB MIGUEL HADDAD",
        "codCidade": 3525904,
        "cidade": "JUNDIAI",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35922420,
        "nome": "ADIWALDE DE OLIVEIRA COELHO PROFESSOR",
        "codCidade": 3509502,
        "cidade": "CAMPINAS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35004200,
        "nome": "ADOLFINO DE ARRUDA CASTANHO PROFESSOR",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35024697,
        "nome": "ADOLFO ALFEU FERRERO",
        "codCidade": 3549409,
        "cidade": "SAO JOAQUIM DA BARRA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35005381,
        "nome": "ADOLFO CASAIS MONTEIRO PROF",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35004212,
        "nome": "ADOLFO GORDO SENADOR",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 520.3980102539062,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35004259,
        "nome": "ADOLFO TRIPOLI PROFESSOR",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.599999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35920551,
        "nome": "ADOLPHO BEREZIN ETE",
        "codCidade": 3531100,
        "cidade": "MONGAGUA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 594.0900268554688,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35048324,
        "nome": "ADOLPHO CARVALHO PROFESSOR",
        "codCidade": 3538709,
        "cidade": "PIRACICABA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35462412,
        "nome": "ADOLPHO DE ARRUDA MELLO PROF ETEC",
        "codCidade": 3541406,
        "cidade": "PRESIDENTE PRUDENTE",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35044301,
        "nome": "ADOLPHO PLUSKAT PROF",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.5,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35047776,
        "nome": "ADOLPHO ROSSIN MAJOR",
        "codCidade": 3509502,
        "cidade": "CAMPINAS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.800000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35022135,
        "nome": "ADOLPHO THOMAS DE AQUINO",
        "codCidade": 3532058,
        "cidade": "MOTUCA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35904703,
        "nome": "ADONIAS FILHO",
        "codCidade": 3513801,
        "cidade": "DIADEMA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35049451,
        "nome": "ADONIRAN BARBOSA",
        "codCidade": 3556206,
        "cidade": "VALINHOS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 511.4200134277344,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35019744,
        "nome": "ADONIRO LADEIRA PROFESSOR",
        "codCidade": 3525904,
        "cidade": "JUNDIAI",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 481.0320129394531,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35919548,
        "nome": "ADREANA COMAR PROFA",
        "codCidade": 3514007,
        "cidade": "DOBRADA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.199999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35038261,
        "nome": "ADRIAO BERNARDES PROF",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.199999809265137,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35013468,
        "nome": "AFFONSO DE CARVALHO DESEMBARGADOR",
        "codCidade": 3548203,
        "cidade": "SANTO ANTONIO DO PINHAL",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 483.3479919433594,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35909543,
        "nome": "AFFONSO JOSE FIORAVANTI PROFESSOR",
        "codCidade": 3538709,
        "cidade": "PIRACICABA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35916791,
        "nome": "AFIZ GEBARA DOUTOR",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 497.0559997558594,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35007894,
        "nome": "AFONSO ARINOS SENADOR",
        "codCidade": 3543303,
        "cidade": "RIBEIRAO PIRES",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.599999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35026897,
        "nome": "AFONSO CAFARO",
        "codCidade": 3515509,
        "cidade": "FERNANDOPOLIS",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 6.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35041853,
        "nome": "AFONSO MORENO",
        "codCidade": 3516309,
        "cidade": "FRANCISCO MORATO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35412983,
        "nome": "AFONSO PASCHOTTE PADRE",
        "codCidade": 3529401,
        "cidade": "MAUA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 473.62200927734375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35026311,
        "nome": "AFONSO PENA PRESIDENTE",
        "codCidade": 3508801,
        "cidade": "CAFELANDIA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35002653,
        "nome": "AFONSO PENNA JUNIOR PROF",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35011435,
        "nome": "AFONSO SCHIMIDT",
        "codCidade": 3513504,
        "cidade": "CUBATAO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35016846,
        "nome": "AFONSO VERGUEIRO DOUTOR",
        "codCidade": 3545308,
        "cidade": "SALTO DE PIRAPORA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.800000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35907194,
        "nome": "AFRANIO DE OLIVEIRA",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35000760,
        "nome": "AFRANIO PEIXOTO",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35000197,
        "nome": "AGENOR COUTO DE MAGALHAES DOUTOR",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35036110,
        "nome": "AGENOR DE CAMPOS",
        "codCidade": 3531100,
        "cidade": "MONGAGUA",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35020382,
        "nome": "AGENOR DE CARVALHO CAPITAO",
        "codCidade": 3557303,
        "cidade": "ESTIVA GERBI",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 35438054,
        "nome": "AGENOR DE MIRANDA ARAUJO NETO - CAZUZA",
        "codCidade": 3550308,
        "cidade": "SAO PAULO",
        "estado": "SP",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      }
    ]
  export default dataSP;