let dataRN = [
  {
    anoCenso: 2013,
    cod: 24096008,
    nome: "C E DE EDUC PROFIS SEN JESSE PINTO FREIRE - CENEP",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24066788,
    nome: "CAIC ESCOLA ESTADUAL JERONIMO VINGT ROSADO MAIA",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24089001,
    nome: "CE DE APOIO PEDAGOGICO PROFESSORA IAPISSARA AGUIAR",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24083925,
    nome: "CE DE CAP DE ED E ATEN SURDO - CAS",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24001155,
    nome: "CE INTEGRADA PROF ELISEU VIANA",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 474.8340148925781,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24001252,
    nome: "CEJA PROF ALFREDO SIMONETTI",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24056774,
    nome: "CEJA PROF FELIPE GUERRA",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24064912,
    nome: "CEJA PROF REGINALDO TEOFILO",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24056987,
    nome: "CEJA PROFA LIA CAMPOS",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24031313,
    nome: "CENTRO DE EDU DE JOVENS E ADULTOS SENADOR GUERRA",
    codCidade: 2402006,
    cidade: "CAICO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24082880,
    nome: "CENTRO DE FORMACAO DE PESSOAL PARA OS SERVICOS DE SAUDE - CEFOPE",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24036420,
    nome: "CENTRO EDUC FELINTO ELISIO",
    codCidade: 2405702,
    cidade: "JARDIM DO SERIDO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 474.4360046386719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24064173,
    nome: "CENTRO EDUCACIONAL ALFERES TIRADENTES",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.099999904632568,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24031348,
    nome: "CENTRO EDUCACIONAL JOSE AUGUSTO",
    codCidade: 2402006,
    cidade: "CAICO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 1.899999976158142,
    enemMediaGeral: 454.78399658203125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24083720,
    nome: "CENTRO ESTADUAL DE CAPACITACAO DE EDUCADORES E ATENDIMENTO AO SURDO - CAS",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24082791,
    nome: "CENTRO ESTADUAL DE EDUCACAO ESPECIAL",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24082716,
    nome: "CENTRO REG EDUC ESP GEOVANIA ANDRADE DE MORAIS",
    codCidade: 2401008,
    cidade: "APODI",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24082759,
    nome: "CENTRO REGIONAL DE EDUCACAO ESPECIAL",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24035432,
    nome: "CES PROFA CREUZA BEZERRA",
    codCidade: 2403103,
    cidade: "CURRAIS NOVOS",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057053,
    nome: "COL EST DO ATHENEU NORTE RIOGRANDENSE",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 472.16400146484375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24038253,
    nome: "E E ANTONIO GOMES",
    codCidade: 2405801,
    cidade: "JOAO CAMARA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24049549,
    nome: "E E DES VICENTE LEMOS",
    codCidade: 2413102,
    cidade: "SENADOR ELOI DE SOUZA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 435.3840026855469,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24052167,
    nome: "E E INTERVENTOR UBALDO BEZERRA DE MELO",
    codCidade: 2402600,
    cidade: "CEARA-MIRIM",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24079162,
    nome: "E E JOAO SOARES DE SOUZA",
    codCidade: 2414753,
    cidade: "VENHA-VER",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 421.1820068359375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24037516,
    nome: "E E JOAO VILAR DA CUNHA ENSINO FUNDAM E MEDIO",
    codCidade: 2411429,
    cidade: "SANTANA DO SERIDO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.599999904632568,
    enemMediaGeral: 471.4119873046875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24026115,
    nome: "E E JOSE AVELINO ENSINO FUNDAMENTAL",
    codCidade: 2400307,
    cidade: "AFONSO BEZERRA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24016705,
    nome: "E E PRAXEDES MARTINS ENS FUNDAMENTAL",
    codCidade: 2404903,
    cidade: "ITAU",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24068586,
    nome: "E E PREFEITO JOSE DO CARMO DOS SANTOS",
    codCidade: 2411502,
    cidade: "SANTO ANTONIO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24026816,
    nome: "E E PROF FRANCISCA ALVES DA SILVA ENS FUNDAMENTAL E MEDIO",
    codCidade: 2403756,
    cidade: "FERNANDO PEDROZA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 426.1199951171875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24005878,
    nome: "E E PROF LOURENCO GURGEL OLIVEIRA ENS FUND E MEDIO",
    codCidade: 2402303,
    cidade: "CARAUBAS",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.5,
    idebAF: 3.0,
    enemMediaGeral: 452.6099853515625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24005894,
    nome: "E E PROF MARIA SILVIA DE V CAMARA",
    codCidade: 2402303,
    cidade: "CARAUBAS",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.9000000953674316,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24004294,
    nome: "E E PROFA ALVANI DE FREITAS DIAS",
    codCidade: 2401008,
    cidade: "APODI",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24071595,
    nome: "E E PROFA MARIA ZENILDA GAMA TORRES",
    codCidade: 2401008,
    cidade: "APODI",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 430.1440124511719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24061530,
    nome: "E E PROFESSOR JOAO MARIA DIAS",
    codCidade: 2403509,
    cidade: "ESPIRITO SANTO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.5999999046325684,
    idebAF: 2.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24025577,
    nome: "E E PROFESSOR JOSE OLAVO DO VALE - ENSINO DE 1º E 2º GRAUS",
    codCidade: 2407203,
    cidade: "MACAU",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24038237,
    nome: "E E PROFESSORA MARLUCE LUCAS",
    codCidade: 2405801,
    cidade: "JOAO CAMARA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057568,
    nome: "EE 12 DE OUTUBRO",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24059994,
    nome: "EE 15 DE OUTUBRO ENS DE 1 GRAU",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 1.7000000476837158,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24025887,
    nome: "EE 1º E 2º GRAUS SEN DINARTE MARIZ",
    codCidade: 2411601,
    cidade: "SAO BENTO DO NORTE",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24061220,
    nome: "EE 4 DE MARCO ENSINO DE 1 GRAU",
    codCidade: 2402204,
    cidade: "CANGUARETAMA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24026875,
    nome: "EE 7 DE SETEMBRO ENSINO DE 1 GRAU",
    codCidade: 2401909,
    cidade: "CAICARA DO RIO DO VENTO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24002046,
    nome: "EE ABOLICAO IV ENSINO FUNDAMENTAL",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24051080,
    nome: "EE ADAO MARCELO DA ROCHA ENS 1 E 2 GRAUS",
    codCidade: 2413904,
    cidade: "TAIPU",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24061000,
    nome: "EE AGUIDA SUCUPIRA",
    codCidade: 2401404,
    cidade: "BAIA FORMOSA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.200000047683716,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057576,
    nome: "EE ALBERTO TORRES ENS DE 1 GRAU",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 2.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24060011,
    nome: "EE ALCEU AMOROSO LIMA ENS DE 1 GRAU",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24010251,
    nome: "EE ALCIDES WANDERLEY ENS DE 2 GRAU",
    codCidade: 2402501,
    cidade: "CARNAUBAIS",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24060020,
    nome: "EE ALDO FERNANDES DE MELO ENS DE 1 GRAU",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24002070,
    nome: "EE ALEIXO ROSA DA SILVA ENS 1 GRAU",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24052884,
    nome: "EE ALFREDO M FILHO ENS 1 E 2 GRAUS",
    codCidade: 2407104,
    cidade: "MACAIBA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057584,
    nome: "EE ALM NEWTON BRAGA FARIA",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.099999904632568,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24056340,
    nome: "EE ALM TAMANDARE ENS DE 1 E 2 GRAUS",
    codCidade: 2403608,
    cidade: "EXTREMOZ",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24053910,
    nome: "EE ALMIR DA SILVA LEITE",
    codCidade: 2408201,
    cidade: "NISIA FLORESTA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057363,
    nome: "EE AMB MATIAS MOREIRA",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057371,
    nome: "EE AMBULATORIO PE JOAO MARIA",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24068039,
    nome: "EE ANA MARIA VIEIRA LIBERATO",
    codCidade: 2401305,
    cidade: "AUGUSTO SEVERO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24005843,
    nome: "EE ANTONIO CARLOS ENS DE 1 GRAU",
    codCidade: 2402303,
    cidade: "CARAUBAS",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 4.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24052892,
    nome: "EE ARCELINA FERNANDES ENS 1 GRAU",
    codCidade: 2407104,
    cidade: "MACAIBA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24029670,
    nome: "EE ARISTOFANES FERNANDES ENSINO FUND E MEDIO",
    codCidade: 2411403,
    cidade: "SANTANA DO MATOS",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 453.0419921875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24070432,
    nome: "EE ARQ ELIZABETH FATIMA ARAUJO GUILHERMINO",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.299999952316284,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057592,
    nome: "EE AUGUSTO SEVERO - ENSINO FUNDAMENTAL",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24052914,
    nome: "EE AUTA DE SOUZA",
    codCidade: 2407104,
    cidade: "MACAIBA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24052094,
    nome: "EE BARAO DE CEARA MIRIM",
    codCidade: 2402600,
    cidade: "CEARA-MIRIM",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24055328,
    nome: "EE BARAO DE MIPIBU ENS DE 1 GRAU",
    codCidade: 2412203,
    cidade: "SAO JOSE DE MIPIBU",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057606,
    nome: "EE BELEM CAMARA ENSINO FUNDAMENTAL E MEDIO",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057614,
    nome: "EE BERILO WANDERLEY",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 490.79998779296875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057630,
    nome: "EE CAFE FILHO ENS DE 1 GRAU",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057649,
    nome: "EE CALAZANS PINHEIRO",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24038261,
    nome: "EE CAP JOSE DA PENHA ENS DE 1 GRAU",
    codCidade: 2405801,
    cidade: "JOAO CAMARA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.799999952316284,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24056740,
    nome: "EE CASA DO MENOR TRABALHADOR",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.200000047683716,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057657,
    nome: "EE CASTRO ALVES ENS DE 1º E DE 2º GRAU",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 461.9779968261719,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24051470,
    nome: "EE CEL ANTONIO DO LAGO ENS 1 GRAU",
    codCidade: 2414407,
    cidade: "TOUROS",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.200000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24040428,
    nome: "EE CEL MANOEL MEDEIROS I",
    codCidade: 2405405,
    cidade: "JAPI",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24040436,
    nome: "EE CEL MANOEL MEDEIROS II",
    codCidade: 2405405,
    cidade: "JAPI",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24003409,
    nome: "EE CENTENARIO DE MOSSORO",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24077798,
    nome: "EE CLARA CAMARAO",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24002127,
    nome: "EE CON ESTEVAM DANTAS ENS DE 1 GRAU",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 2.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24060046,
    nome: "EE CON LUIZ WANDERLEY ENS 1 E 2 GR",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057436,
    nome: "EE CONEGO MONTE",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24000140,
    nome: "EE CONSELHEIRO BRITO GUERRA ENSINO FUNDAMENTAL II E MEDIO",
    codCidade: 2401107,
    cidade: "AREIA BRANCA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 1.2000000476837158,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24027057,
    nome: "EE CORONEL MIGUEL TEIXEIRA ENS FUND E MEDIO",
    codCidade: 2405504,
    cidade: "JARDIM DE ANGICOS",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 474.04998779296875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24041572,
    nome: "EE COSME FERREIRA MARQUES ENS FUNDAMENTAL E EJA",
    codCidade: 2411205,
    cidade: "SANTA CRUZ",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24345300,
    nome: "EE DE ENSINO MEDIO DO CONJUNTO AMARANTE",
    codCidade: 2412005,
    cidade: "SAO GONCALO DO AMARANTE",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24052949,
    nome: "EE DEP JESSE PINTO FREIRE FILHO",
    codCidade: 2407104,
    cidade: "MACAIBA",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057690,
    nome: "EE DEP MARCIO MARINHO ENS 1 G",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 1.399999976158142,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057703,
    nome: "EE DES FLORIANO CAVALCANTI ENS 1 E 2 GRAUS",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 489.1700134277344,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057711,
    nome: "EE DES REGULO TINOCO ENS FUNDAMENTAL E MEDIO",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 461.2820129394531,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24008028,
    nome: "EE DESEMBARGADOR FELIPE GUERRA - ENS FUND E MEDIO",
    codCidade: 2414456,
    cidade: "TRIUNFO POTIGUAR",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24042757,
    nome: "EE DIOGENES DA CUNHA LIMA ENS 1 E 2 GRA",
    codCidade: 2412302,
    cidade: "SAO JOSE DO CAMPESTRE",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24064459,
    nome: "EE DIRAN RAMOS DO AMARAL",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 3.799999952316284,
    enemMediaGeral: 472.3479919433594,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057738,
    nome: "EE DJALMA A MARINHO ENS 1 E 2 GRAUS",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.700000047683716,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24334316,
    nome: "EE DO GUARAPES - ENS MEDIO",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24060070,
    nome: "EE DOM JOSE ADELINO DANTAS ENS 1 E 2 GR",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24080470,
    nome: "EE DOM NIVALDO MONTE",
    codCidade: 2403251,
    cidade: "PARNAMIRIM",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 484.6419982910156,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24055786,
    nome: "EE DR ANTONIO DE SOUZA ENS FUND E MEDIO",
    codCidade: 2403251,
    cidade: "PARNAMIRIM",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24002186,
    nome: "EE DR EWERTON D CORTEZ ENS 1 GRAU",
    codCidade: 2408003,
    cidade: "MOSSORO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.099999904632568,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24026883,
    nome: "EE DR GERALDO ANDRADE TEIXEIRA",
    codCidade: 2401909,
    cidade: "CAICARA DO RIO DO VENTO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057762,
    nome: "EE DR GRACILIANO LORDAO ENS 1 GRAU",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24039608,
    nome: "EE DR JOSE BORGES DE OLIVEIRA - ENS FUNDAMENTAL E EJA",
    codCidade: 2402105,
    cidade: "CAMPO REDONDO",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 24057789,
    nome: "EE DR MAIA NETO ENS DE 1 GRAU",
    codCidade: 2408102,
    cidade: "NATAL",
    estado: "RN",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataRN;
