let dataPA = [
  {
    anoCenso: 2013,
    cod: 15576370,
    nome: "CE PALMIRA GABRIEL",
    codCidade: 1501303,
    cidade: "BARCARENA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15574865,
    nome: "CEEM DEPUTADO NICIAS RIBEIRO",
    codCidade: 1505809,
    cidade: "PORTEL",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 438.093994140625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15572099,
    nome: "CEEM PRESIDENTE FERNANDO HENRIQUE",
    codCidade: 1504802,
    cidade: "MONTE ALEGRE",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 461.64801025390625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15587878,
    nome: "CENTRO INTEGRADO DE EDUC DO BAIXO TOCANTINS",
    codCidade: 1502103,
    cidade: "CAMETA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 492.7120056152344,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15106250,
    nome: "COLEGIO ESTADUAL DE ENSINO MEDIO BRASIL NOVO",
    codCidade: 1501725,
    cidade: "BRASIL NOVO",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 448.5039978027344,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15057119,
    nome: "E E E F M CORONEL ALUIZIO PINHEIRO FERREIRA",
    codCidade: 1501709,
    cidade: "BRAGANCA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15059731,
    nome: "E E E F M MARIA MIRTES SIDRIM PESSOA",
    codCidade: 1502202,
    cidade: "CAPANEMA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.200000047683716,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15533255,
    nome: "E E E F M MESTRE LUCINDO",
    codCidade: 1502202,
    cidade: "CAPANEMA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15011674,
    nome: "E E E F M PLACIDO DE CASTRO",
    codCidade: 1506807,
    cidade: "SANTAREM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 455.5660095214844,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15059677,
    nome: "E E E F M PROF OLIVEIRA BRITO",
    codCidade: 1502202,
    cidade: "CAPANEMA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 459.9800109863281,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15094693,
    nome: "E E E F PROF VICENTINA SODRE DE ARAUJO",
    codCidade: 1507201,
    cidade: "SAO DOMINGOS DO CAPIM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.5999999046325684,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15011712,
    nome: "E E E F RICHARD HENNINGTON",
    codCidade: 1506807,
    cidade: "SANTAREM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15043550,
    nome: "E E E I F ALMIRANTE GUILLOBEL",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 4.800000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15063615,
    nome: "E E E M ROSA CARRERA LOUREIRO AQUINO",
    codCidade: 1506906,
    cidade: "SANTAREM NOVO",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15587916,
    nome: "E E E TECNOLOGICA DO ESTADO DO PARA",
    codCidade: 1507953,
    cidade: "TAILANDIA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15587886,
    nome: "E E T E PA MONTE ALEGRE",
    codCidade: 1504802,
    cidade: "MONTE ALEGRE",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 472.3080139160156,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15567877,
    nome: "E R C CENTRO INTEGRADO DE EDUCACAO ESPECIAL FONTE VIVA",
    codCidade: 1503606,
    cidade: "ITAITUBA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15572153,
    nome: "EE ANEXO CENT DE INT DE ADOL MASC CIAM FUNCAP",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15037665,
    nome: "EE CENTRO DE ESTUDOS SUPLETIVO PROF LUIZ OTAVIO PEREIRA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15125440,
    nome: "EE GEN EUCLYDES F FIGUEIREDO",
    codCidade: 1505536,
    cidade: "PARAUAPEBAS",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15134563,
    nome: "EEEF 14 DE ABRIL",
    codCidade: 1502707,
    cidade: "CONCEICAO DO ARAGUAIA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.099999904632568,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15081052,
    nome: "EEEF ALOISIO DA COSTA CHAVES",
    codCidade: 1502756,
    cidade: "CONCORDIA DO PARA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15011402,
    nome: "EEEF BARAO DO TAPAJOS",
    codCidade: 1506807,
    cidade: "SANTAREM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15039170,
    nome: "EEEF BENTO XV",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15042677,
    nome: "EEEF BRASILIA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.700000047683716,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15039870,
    nome: "EEEF CABANAGEM",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15573605,
    nome: "EEEF CARANANDUBA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15035620,
    nome: "EEEF CARLOS DRUMMOND DE ANDRADE",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15058751,
    nome: "EEEF CASA DA AMIZADE",
    codCidade: 1501709,
    cidade: "BRAGANCA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034330,
    nome: "EEEF CELINA DEL TETTO",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.9000000953674316,
    idebAF: 4.099999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15056643,
    nome: "EEEF CENTRO EDUCACIONAL CORACAO DE JESUS",
    codCidade: 1501709,
    cidade: "BRAGANCA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.9000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15042766,
    nome: "EEEF COLONIA DO FIDELIS",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034828,
    nome: "EEEF COMANDANTE LAURINDO CANDIDO AZEITONA",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034550,
    nome: "EEEF DEP ARMANDO CORREA",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.400000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034046,
    nome: "EEEF DOM ALBERTO GALDENCIO RAMOS",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.700000047683716,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15039544,
    nome: "EEEF DONA ALZIRA TEIXEIRA DE SOUZA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15039927,
    nome: "EEEF DR MARIO CHERMONT",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15056775,
    nome: "EEEF DRA PAULA PINHEIRO",
    codCidade: 1501709,
    cidade: "BRAGANCA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15045510,
    nome: "EEEF ERNESTINA THEDY",
    codCidade: 1502400,
    cidade: "CASTANHAL",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15064905,
    nome: "EEEF ESMERINA BOU HABIB",
    codCidade: 1500107,
    cidade: "ABAETETUBA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15517039,
    nome: "EEEF ESPIRITO SANTO",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15005151,
    nome: "EEEF FULGENCIO SIMOES",
    codCidade: 1500404,
    cidade: "ALENQUER",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15039960,
    nome: "EEEF GENERAL GURJAO",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15011593,
    nome: "EEEF GONCALVES DIAS",
    codCidade: 1506807,
    cidade: "SANTAREM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 4.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034810,
    nome: "EEEF GREGORIO DE ALMEIDA BRITO",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15043312,
    nome: "EEEF INGLES DE SOUZA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.299999952316284,
    idebAF: 4.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15528855,
    nome: "EEEF JADER FONTENELLE BARBALHO",
    codCidade: 1506807,
    cidade: "SANTAREM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 417.42401123046875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034755,
    nome: "EEEF JOSE MARCELINO DE OLIVEIRA",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15028488,
    nome: "EEEF JOSE RODRIGUES VIANA",
    codCidade: 1502004,
    cidade: "CACHOEIRA DO ARARI",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.9000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034631,
    nome: "EEEF JULIA SEFFER",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0999999046325684,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15057259,
    nome: "EEEF LEANDRO LOBAO DA SILVEIRA",
    codCidade: 1501709,
    cidade: "BRAGANCA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15043991,
    nome: "EEEF LEAO IRINEU HAUSSLER DELGADO",
    codCidade: 1501501,
    cidade: "BENEVIDES",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034763,
    nome: "EEEF LUCY CORREA DE ARAUJO",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 446.8320007324219,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15060705,
    nome: "EEEF MACARIO FELIPE ANTONIO",
    codCidade: 1503200,
    cidade: "IGARAPE-ACU",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.5,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15040437,
    nome: "EEEF MANOEL DE JESUS MORAES",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.200000047683716,
    idebAF: 3.0,
    enemMediaGeral: 483.3160095214844,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15140587,
    nome: "EEEF MARIA DE NAZARE MARQUES RIOS",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.9000000953674316,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15048853,
    nome: "EEEF MARIA HYLUISA PINTO FERREIRA",
    codCidade: 1502905,
    cidade: "CURUCA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15042537,
    nome: "EEEF MARILDA NUNES",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15040070,
    nome: "EEEF MATEUS DO CARMO",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15057135,
    nome: "EEEF MONSENHOR MANCIO RIBEIRO",
    codCidade: 1501709,
    cidade: "BRAGANCA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.4000000953674316,
    enemMediaGeral: 483.3320007324219,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15045609,
    nome: "EEEF NILZA NASCIMENTO",
    codCidade: 1502400,
    cidade: "CASTANHAL",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15041344,
    nome: "EEEF NOSSA SENHORA DAS GRACAS GUAMA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15574156,
    nome: "EEEF NOSSA SENHORA DE GUADALUPE",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15011410,
    nome: "EEEF NOSSA SENHORA DO GUADALUPE",
    codCidade: 1506807,
    cidade: "SANTAREM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15042138,
    nome: "EEEF NOSSA SENHORA DO PERPETUO SOCORRO",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15093620,
    nome: "EEEF PADRE ANGELO MORETTI",
    codCidade: 1505403,
    cidade: "OUREM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15059650,
    nome: "EEEF PADRE SALES",
    codCidade: 1502202,
    cidade: "CAPANEMA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15572102,
    nome: "EEEF PARACURI II",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15040089,
    nome: "EEEF PAULO MARANHAO",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15056732,
    nome: "EEEF PE PAULINO BRAMBILLA",
    codCidade: 1501709,
    cidade: "BRAGANCA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15580768,
    nome: "EEEF PRATINHA II",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034453,
    nome: "EEEF PRES TANCREDO DE ALMEIDA NEVES",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.5999999046325684,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15040461,
    nome: "EEEF PRESIDENTE COSTA E SILVA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 455.6000061035156,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15061132,
    nome: "EEEF PRINCESA IZABEL",
    codCidade: 1503200,
    cidade: "IGARAPE-ACU",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15131823,
    nome: "EEEF PROF ANICETO CARLOS LARANJEIRA",
    codCidade: 1506161,
    cidade: "RIO MARIA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15043738,
    nome: "EEEF PROF DEUSARINA NASCIMENTO DE SOUSA",
    codCidade: 1501501,
    cidade: "BENEVIDES",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15139581,
    nome: "EEEF PROF LENIRA TEIXEIRA MOURA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15049809,
    nome: "EEEF PROF MANOEL JOAQUIM MONTEIRO",
    codCidade: 1504109,
    cidade: "MAGALHAES BARATA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 1.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15131840,
    nome: "EEEF PROF MARIZETE FIGUEREDO DE CASTRO",
    codCidade: 1506161,
    cidade: "RIO MARIA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.9000000953674316,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15011321,
    nome: "EEEF PROF ROMANA TAVARES LEAL",
    codCidade: 1506807,
    cidade: "SANTAREM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.099999904632568,
    idebAF: 1.899999976158142,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15039803,
    nome: "EEEF PROF SANTANA MARQUES",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15052192,
    nome: "EEEF PROF TEODATO DE REZENDE",
    codCidade: 1506203,
    cidade: "SALINOPOLIS",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15057194,
    nome: "EEEF PROF YOLANDA CHAVES",
    codCidade: 1501709,
    cidade: "BRAGANCA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15517691,
    nome: "EEEF PROFA CLAUDINE GABRIELE LIMA E SILVA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15054390,
    nome: "EEEF PROFA ESTER NUNES BIBAS",
    codCidade: 1508209,
    cidade: "VIGIA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15042294,
    nome: "EEEF PROFA GUAJARINA DE SOUZA DA SILVA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15038696,
    nome: "EEEF PROFA MARLUCE PACHECO FERREIRA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.200000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15042790,
    nome: "EEEF PROFA ODETE MARVAO",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15040518,
    nome: "EEEF PROFA ROSALINA ALVARES SILVA CRUZ",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15573699,
    nome: "EEEF ROSA MISTICA",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15034887,
    nome: "EEEF RUI BARATA",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15040186,
    nome: "EEEF RUI BARBOSA",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15040208,
    nome: "EEEF RUTH PASSARINHO",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15573206,
    nome: "EEEF SANTA LUZIA DE MARILAC",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15043622,
    nome: "EEEF SANTA MARIA BERTILLA",
    codCidade: 1501501,
    cidade: "BENEVIDES",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15041409,
    nome: "EEEF SANTO AFONSO",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15041417,
    nome: "EEEF SANTO AGOSTINHO",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15039773,
    nome: "EEEF SANTOS DUMONT",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15042600,
    nome: "EEEF SAO FRANCISCO DE ASSIS",
    codCidade: 1501402,
    cidade: "BELEM",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 15535134,
    nome: "EEEF SAO VICENTE",
    codCidade: 1500800,
    cidade: "ANANINDEUA",
    estado: "PA",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.200000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataPA;
