let dataDF =
    [
      {
        "anoCenso": 2013,
        "cod": 53009649,
        "nome": "CAIC ALBERT SABIN",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005953,
        "nome": "CAIC ASSIS CHATEAUBRIAND",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.900000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007255,
        "nome": "CAIC BERNARDO SAYAO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.400000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53002458,
        "nome": "CAIC CARLOS CASTELLO BRANCO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.400000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008952,
        "nome": "CAIC HELENA REIS",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005309,
        "nome": "CAIC JULIA KUBITSCHEK DE OLIVEIRA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007034,
        "nome": "CAIC JUSCELINO KUBITSCHEK",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.199999809265137,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007263,
        "nome": "CAIC PROF ANISIO TEIXEIRA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.599999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53004973,
        "nome": "CAIC PROF BENEDITO CARLOS DE OLIVEIRA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53003381,
        "nome": "CAIC PROF WALTER JOSE DE MOURA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.599999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53009657,
        "nome": "CAIC SANTA MARIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.599999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53006712,
        "nome": "CAIC SANTA PAULINA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.099999904632568,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53009720,
        "nome": "CAIC UNESCO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53006062,
        "nome": "CED 01 DE PLANALTINA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.099999904632568,
        "enemMediaGeral": 484.20001220703125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008790,
        "nome": "CED 01 DO CRUZEIRO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.0999999046325684,
        "enemMediaGeral": 505.3059997558594,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008456,
        "nome": "CED 01 DO GUARA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 498.0419921875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53068092,
        "nome": "CED 01 DO RIACHO FUNDO II",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 469.77801513671875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005023,
        "nome": "CED 02 DE BRAZLANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005473,
        "nome": "CED 02 DE SOBRADINHO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 493.0840148925781,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53003578,
        "nome": "CED 02 DE TAGUATINGA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008804,
        "nome": "CED 02 DO CRUZEIRO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 497.60400390625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008464,
        "nome": "CED 02 DO GUARA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 514.333984375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53012720,
        "nome": "CED 03 DE BRAZLANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 480.1180114746094,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53006283,
        "nome": "CED 03 DE PLANALTINA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 480.9360046386719,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005341,
        "nome": "CED 03 DE SOBRADINHO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 496.1099853515625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008472,
        "nome": "CED 03 DO GUARA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 519.8179931640625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53012542,
        "nome": "CED 04 DE SOBRADINHO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 486.385986328125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53003594,
        "nome": "CED 04 DE TAGUATINGA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0,
        "enemMediaGeral": 489.14801025390625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008480,
        "nome": "CED 04 DO GUARA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 499.5039978027344,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53003608,
        "nome": "CED 05 DE TAGUATINGA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.9000000953674316,
        "enemMediaGeral": 511.72198486328125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007530,
        "nome": "CED 06 DE CEILANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 515.4879760742188,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53003616,
        "nome": "CED 06 DE TAGUATINGA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 495.4280090332031,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53002610,
        "nome": "CED 06 DO GAMA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.400000095367432,
        "idebAF": 0.0,
        "enemMediaGeral": 479.1059875488281,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007549,
        "nome": "CED 07 DE CEILANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 486.8340148925781,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53003624,
        "nome": "CED 07 DE TAGUATINGA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 489.03399658203125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53002563,
        "nome": "CED 07 DO GAMA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53002482,
        "nome": "CED 08 DO GAMA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 488.6059875488281,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53011066,
        "nome": "CED 104 DO RECANTO DAS EMAS",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.0,
        "enemMediaGeral": 485.2200012207031,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007921,
        "nome": "CED 11 DE CEILANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 491.54998779296875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53012097,
        "nome": "CED 123 DE SAMAMBAIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.9000000953674316,
        "enemMediaGeral": 472.6940002441406,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007360,
        "nome": "CED 14 DE CEILANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 477.6960144042969,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007387,
        "nome": "CED 15 DE CEILANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 478.6199951171875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53068181,
        "nome": "CED 310 DE SANTA MARIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 481.2340087890625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53010000,
        "nome": "CED 416 DE SANTA MARIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53010019,
        "nome": "CED 619 DE SAMAMBAIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.799999952316284,
        "enemMediaGeral": 471.86199951171875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53006968,
        "nome": "CED AGROURBANO IPE RIACHO FUNDO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 4.5,
        "enemMediaGeral": 480.9620056152344,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53012011,
        "nome": "CED CONDOMINIO ESTANCIA III",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53011520,
        "nome": "CED DARCY RIBEIRO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 488.9219970703125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53009479,
        "nome": "CED DO LAGO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 493.28399658203125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53012356,
        "nome": "CED DO LAGO NORTE",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 470.6180114746094,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53068068,
        "nome": "CED DONA AMERICA GUIMARAES",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.9000000953674316,
        "enemMediaGeral": 463.156005859375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005392,
        "nome": "CED FERCAL",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53001044,
        "nome": "CED GISNO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 1.899999976158142,
        "enemMediaGeral": 499.7879943847656,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008979,
        "nome": "CED MYRIAM ERVILHA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 480.0360107421875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53014308,
        "nome": "CED POMPILIO MARQUES DE SOUZA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 487.7860107421875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53019806,
        "nome": "CED SAO FRANCISCO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0,
        "enemMediaGeral": 486.53399658203125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53013840,
        "nome": "CED STELLA DOS CHERUBINS GUIMARAES TROIS",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 487.38800048828125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53014316,
        "nome": "CED VALE DO AMANHECER",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0999999046325684,
        "enemMediaGeral": 486.04400634765625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53009460,
        "nome": "CED VARGEM BONITA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.0,
        "idebAF": 5.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53000439,
        "nome": "CEE 01 DE BRASILIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005040,
        "nome": "CEE 01 DE BRAZLANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53003802,
        "nome": "CEE 01 DE CEILANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53006097,
        "nome": "CEE 01 DE PLANALTINA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53012780,
        "nome": "CEE 01 DE SAMAMBAIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53013336,
        "nome": "CEE 01 DE SANTA MARIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005848,
        "nome": "CEE 01 DE SOBRADINHO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53003810,
        "nome": "CEE 01 DE TAGUATINGA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53010752,
        "nome": "CEE 01 DO GAMA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53010744,
        "nome": "CEE 01 DO GUARA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53000200,
        "nome": "CEE 02 DE BRASILIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53012771,
        "nome": "CEE 02 DE CEILANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53000714,
        "nome": "CEE DE DEFICIENTES VISUAIS",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53009312,
        "nome": "CEF 01 DA CANDANGOLANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53048008,
        "nome": "CEF 01 DA ESTRUTURAL",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.199999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53000846,
        "nome": "CEF 01 DE BRASILIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53004990,
        "nome": "CEF 01 DE BRAZLANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005996,
        "nome": "CEF 01 DE PLANALTINA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 2.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005333,
        "nome": "CEF 01 DE SOBRADINHO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.5,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008774,
        "nome": "CEF 01 DO CRUZEIRO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.199999809265137,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53002784,
        "nome": "CEF 01 DO GAMA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008391,
        "nome": "CEF 01 DO GUARA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53009410,
        "nome": "CEF 01 DO LAGO NORTE",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.300000190734863,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007042,
        "nome": "CEF 01 DO NUCLEO BANDEIRANTE",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.900000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53012429,
        "nome": "CEF 01 DO PARANOA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53000854,
        "nome": "CEF 01 DO PLANALTO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.0,
        "idebAF": 2.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53013034,
        "nome": "CEF 01 DO RIACHO FUNDO II",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53068157,
        "nome": "CEF 02 DA ESTRUTURAL",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53000862,
        "nome": "CEF 02 DE BRASILIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005090,
        "nome": "CEF 02 DE BRAZLANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.599999904632568,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53007280,
        "nome": "CEF 02 DE CEILANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53006003,
        "nome": "CEF 02 DE PLANALTINA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.900000095367432,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008782,
        "nome": "CEF 02 DO CRUZEIRO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53008529,
        "nome": "CEF 02 DO GUARA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53012003,
        "nome": "CEF 02 DO PARANOA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53011023,
        "nome": "CEF 02 DO RIACHO FUNDO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53068106,
        "nome": "CEF 02 RIACHO FUNDO II",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53000870,
        "nome": "CEF 03 DE BRASILIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 5.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53014553,
        "nome": "CEF 03 DE BRAZLANDIA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005961,
        "nome": "CEF 03 DE PLANALTINA",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 53005350,
        "nome": "CEF 03 DE SOBRADINHO",
        "codCidade": 5300108,
        "cidade": "BRASILIA",
        "estado": "DF",
        "regiao": "Centro-Oeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      }
    ]
  export default dataDF;