let dataSC = 
    [
      {
        "anoCenso": 2013,
        "cod": 42145007,
        "nome": "CASA FAMILIAR RURAL DE GUARACIABA",
        "codCidade": 4206405,
        "cidade": "GUARACIABA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42144990,
        "nome": "CASA FAMILIAR RURAL ESPERANCA",
        "codCidade": 4207650,
        "cidade": "IPORA DO OESTE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42142407,
        "nome": "CEDUP - CENTRO DE EDUCACAO PROFISSIONAL",
        "codCidade": 4210100,
        "cidade": "MAFRA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42012201,
        "nome": "CEDUP ABILIO PAULO",
        "codCidade": 4204608,
        "cidade": "CRICIUMA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42348269,
        "nome": "CEDUP ALTO VALE",
        "codCidade": 4214805,
        "cidade": "RIO DO SUL",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42020506,
        "nome": "CEDUP DARIO GERALDO SALLES",
        "codCidade": 4209102,
        "cidade": "JOINVILLE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42199204,
        "nome": "CEDUP DE CHAPECO",
        "codCidade": 4204202,
        "cidade": "CHAPECO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42144671,
        "nome": "CEDUP DE LAGES",
        "codCidade": 4209300,
        "cidade": "LAGES",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42144191,
        "nome": "CEDUP DE TIMBO",
        "codCidade": 4218202,
        "cidade": "TIMBO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42015987,
        "nome": "CEDUP HERMANN HERING",
        "codCidade": 4202404,
        "cidade": "BLUMENAU",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42261201,
        "nome": "CEDUP JORGE LACERDA",
        "codCidade": 4205407,
        "cidade": "FLORIANOPOLIS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42029961,
        "nome": "CEDUP RENATO RAMOS DA SILVA",
        "codCidade": 4209300,
        "cidade": "LAGES",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 495.5539855957031,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42110904,
        "nome": "CEI VIDA E MOVIMENTO",
        "codCidade": 4205407,
        "cidade": "FLORIANOPOLIS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126452,
        "nome": "CEJA CANOINHAS",
        "codCidade": 4203808,
        "cidade": "CANOINHAS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42125979,
        "nome": "CEJA CENTRO DE EDUCACAO DE JOVENS E ADULTOS DE BRACO DO NORTE",
        "codCidade": 4202800,
        "cidade": "BRACO DO NORTE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126304,
        "nome": "CEJA DE ARARANGUA",
        "codCidade": 4201406,
        "cidade": "ARARANGUA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42071356,
        "nome": "CEJA DE BALNEARIO CAMBORIU",
        "codCidade": 4202008,
        "cidade": "BALNEARIO CAMBORIU",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126797,
        "nome": "CEJA DE BLUMENAU",
        "codCidade": 4202404,
        "cidade": "BLUMENAU",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42128340,
        "nome": "CEJA DE BRUSQUE",
        "codCidade": 4202909,
        "cidade": "BRUSQUE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126150,
        "nome": "CEJA DE CACADOR",
        "codCidade": 4203006,
        "cidade": "CACADOR",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42128293,
        "nome": "CEJA DE CAMPOS NOVOS",
        "codCidade": 4203600,
        "cidade": "CAMPOS NOVOS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126738,
        "nome": "CEJA DE CHAPECO",
        "codCidade": 4204202,
        "cidade": "CHAPECO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126517,
        "nome": "CEJA DE CONCORDIA",
        "codCidade": 4204301,
        "cidade": "CONCORDIA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126525,
        "nome": "CEJA DE CRICIUMA",
        "codCidade": 4204608,
        "cidade": "CRICIUMA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42134463,
        "nome": "CEJA DE CURITIBANOS",
        "codCidade": 4204806,
        "cidade": "CURITIBANOS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126509,
        "nome": "CEJA DE FLORIANOPOLIS",
        "codCidade": 4205407,
        "cidade": "FLORIANOPOLIS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42127866,
        "nome": "CEJA DE IBIRAMA",
        "codCidade": 4206900,
        "cidade": "IBIRAMA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42133793,
        "nome": "CEJA DE IMBITUBA",
        "codCidade": 4207304,
        "cidade": "IMBITUBA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126622,
        "nome": "CEJA DE ITAJAI",
        "codCidade": 4208203,
        "cidade": "ITAJAI",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126550,
        "nome": "CEJA DE ITUPORANGA",
        "codCidade": 4208500,
        "cidade": "ITUPORANGA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42125600,
        "nome": "CEJA DE JOACABA",
        "codCidade": 4209003,
        "cidade": "JOACABA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42133416,
        "nome": "CEJA DE JOINVILLE",
        "codCidade": 4209102,
        "cidade": "JOINVILLE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126657,
        "nome": "CEJA DE LAGES",
        "codCidade": 4209300,
        "cidade": "LAGES",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42129362,
        "nome": "CEJA DE LAGUNA",
        "codCidade": 4209409,
        "cidade": "LAGUNA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42125308,
        "nome": "CEJA DE MAFRA",
        "codCidade": 4210100,
        "cidade": "MAFRA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126851,
        "nome": "CEJA DE MARAVILHA",
        "codCidade": 4210506,
        "cidade": "MARAVILHA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42128552,
        "nome": "CEJA DE PALMITOS",
        "codCidade": 4212106,
        "cidade": "PALMITOS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42128498,
        "nome": "CEJA DE QUILOMBO",
        "codCidade": 4214201,
        "cidade": "QUILOMBO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42127971,
        "nome": "CEJA DE RIO DO SUL",
        "codCidade": 4214805,
        "cidade": "RIO DO SUL",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126207,
        "nome": "CEJA DE SAO BENTO DO SUL",
        "codCidade": 4215802,
        "cidade": "SAO BENTO DO SUL",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42133807,
        "nome": "CEJA DE SAO JOAQUIM",
        "codCidade": 4216503,
        "cidade": "SAO JOAQUIM",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42027152,
        "nome": "CEJA DE SAO JOSE",
        "codCidade": 4216602,
        "cidade": "SAO JOSE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126223,
        "nome": "CEJA DE SAO LOURENCO DO OESTE",
        "codCidade": 4216909,
        "cidade": "SAO LOURENCO DO OESTE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42129001,
        "nome": "CEJA DE SAO MIGUEL D OESTE",
        "codCidade": 4217204,
        "cidade": "SAO MIGUEL DO OESTE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42352274,
        "nome": "CEJA DE SEARA",
        "codCidade": 4217501,
        "cidade": "SEARA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42146500,
        "nome": "CEJA DE TAIO",
        "codCidade": 4217808,
        "cidade": "TAIO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42020875,
        "nome": "CEJA DE TIMBO",
        "codCidade": 4218202,
        "cidade": "TIMBO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42125871,
        "nome": "CEJA DE TUBARAO",
        "codCidade": 4218707,
        "cidade": "TUBARAO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42129699,
        "nome": "CEJA DE VIDEIRA",
        "codCidade": 4219309,
        "cidade": "VIDEIRA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126665,
        "nome": "CEJA DE XANXERE",
        "codCidade": 4219507,
        "cidade": "XANXERE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42348293,
        "nome": "CEJA DIONISIO CERQUEIRA",
        "codCidade": 4205001,
        "cidade": "DIONISIO CERQUEIRA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42126410,
        "nome": "CEJA ITAPIRANGA",
        "codCidade": 4208401,
        "cidade": "ITAPIRANGA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42006716,
        "nome": "CENTRO DE ED PROFISSIONAL DIOMICIO FREITAS",
        "codCidade": 4218707,
        "cidade": "TUBARAO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42013763,
        "nome": "EEB ABILIO CESAR BORGES",
        "codCidade": 4211603,
        "cidade": "NOVA VENEZA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.599999904632568,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42069610,
        "nome": "EEB ADELAIDE KONDER",
        "codCidade": 4211306,
        "cidade": "NAVEGANTES",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.900000095367432,
        "idebAF": 4.800000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42002079,
        "nome": "EEB ADERBAL RAMOS DA SILVA",
        "codCidade": 4205407,
        "cidade": "FLORIANOPOLIS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 497.0820007324219,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42071208,
        "nome": "EEB ADOLFO ANTONIO CABRAL",
        "codCidade": 4212809,
        "cidade": "BALNEARIO PICARRAS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42023815,
        "nome": "EEB ADOLFO BOVING",
        "codCidade": 4202859,
        "cidade": "BRACO DO TROMBUDO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42034817,
        "nome": "EEB ADOLFO JOSE MARTINS",
        "codCidade": 4202503,
        "cidade": "BOM JARDIM DA SERRA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 4.5,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 441.8240051269531,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42060583,
        "nome": "EEB ADOLFO SILVEIRA",
        "codCidade": 4212239,
        "cidade": "PARAISO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 4.5,
        "enemMediaGeral": 496.44000244140625,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42016002,
        "nome": "EEB ADOLPHO KONDER",
        "codCidade": 4202404,
        "cidade": "BLUMENAU",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42031079,
        "nome": "EEB AGAR ALVES NUNES",
        "codCidade": 4211751,
        "cidade": "OTACILIO COSTA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 3.9000000953674316,
        "idebAF": 3.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42020417,
        "nome": "EEB ALBANO SCHMIDT",
        "codCidade": 4209102,
        "cidade": "JOINVILLE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.5,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42060559,
        "nome": "EEB ALBERICO AZEVEDO",
        "codCidade": 4217204,
        "cidade": "SAO MIGUEL DO OESTE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42072310,
        "nome": "EEB ALBINA MOSCONI",
        "codCidade": 4210050,
        "cidade": "MACIEIRA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.699999809265137,
        "enemMediaGeral": 479.2279968261719,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42074878,
        "nome": "EEB ALCIDES CARLOS BONET",
        "codCidade": 4215505,
        "cidade": "SANTA CECILIA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42109159,
        "nome": "EEB ALCUINO GONCALO VIEIRA",
        "codCidade": 4203204,
        "cidade": "CAMBORIU",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42003750,
        "nome": "EEB ALDO CAMARA DA SILVA",
        "codCidade": 4216602,
        "cidade": "SAO JOSE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.300000190734863,
        "idebAF": 5.699999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42052270,
        "nome": "EEB ALECIO ALEXANDRE CELLA",
        "codCidade": 4204202,
        "cidade": "CHAPECO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.800000190734863,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42071321,
        "nome": "EEB ALEXANDRE GUILHERME FIGUEREDO",
        "codCidade": 4212809,
        "cidade": "BALNEARIO PICARRAS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 482.3840026855469,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42036283,
        "nome": "EEB ALEXANDRE GUSMAO",
        "codCidade": 4202602,
        "cidade": "BOM RETIRO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.599999904632568,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42081173,
        "nome": "EEB ALEXANDRE TERNES FILHO",
        "codCidade": 4218004,
        "cidade": "TIJUCAS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42023122,
        "nome": "EEB ALFREDO DALFOVO",
        "codCidade": 4214805,
        "cidade": "RIO DO SUL",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 482.7239990234375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42091942,
        "nome": "EEB ALFREDO ZIMMERMANN",
        "codCidade": 4206504,
        "cidade": "GUARAMIRIM",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.199999809265137,
        "idebAF": 3.9000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42040930,
        "nome": "EEB ALINOR VIEIRA CORTE",
        "codCidade": 4212205,
        "cidade": "PAPANDUVA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.099999904632568,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42089344,
        "nome": "EEB ALMIRANTE BARROSO",
        "codCidade": 4203808,
        "cidade": "CANOINHAS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 513.6680297851562,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42021685,
        "nome": "EEB ALMIRANTE BOITEUX",
        "codCidade": 4201307,
        "cidade": "ARAQUARI",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.5999999046325684,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42012333,
        "nome": "EEB ALOYSIUS BACK",
        "codCidade": 4205456,
        "cidade": "FORQUILHINHA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.599999904632568,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42002893,
        "nome": "EEB ALTAMIRO GUIMARAES",
        "codCidade": 4201208,
        "cidade": "ANTONIO CARLOS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 7.599999904632568,
        "idebAF": 5.099999904632568,
        "enemMediaGeral": 532.4639892578125,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42005655,
        "nome": "EEB ALTINO FLORES",
        "codCidade": 4201109,
        "cidade": "ANITAPOLIS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42091594,
        "nome": "EEB ALVINO TRIBESS",
        "codCidade": 4208906,
        "cidade": "JARAGUA DO SUL",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.0,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42102669,
        "nome": "EEB AMERICA DUTRA MACHADO",
        "codCidade": 4205407,
        "cidade": "FLORIANOPOLIS",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 3.5999999046325684,
        "idebAF": 2.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42093910,
        "nome": "EEB ANA GONDIN",
        "codCidade": 4209409,
        "cidade": "LAGUNA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.199999809265137,
        "idebAF": 3.4000000953674316,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42078946,
        "nome": "EEB ANA MACHADO DAL TOE",
        "codCidade": 4211256,
        "cidade": "MORRO GRANDE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.900000095367432,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42006171,
        "nome": "EEB ANISIO V DE FREITAS",
        "codCidade": 4215703,
        "cidade": "SANTO AMARO DA IMPERATRIZ",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 3.200000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42070732,
        "nome": "EEB ANITA GARIBALDI",
        "codCidade": 4208302,
        "cidade": "ITAPEMA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.199999809265137,
        "idebAF": 4.300000190734863,
        "enemMediaGeral": 486.7300109863281,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42064619,
        "nome": "EEB ANTENOR NASCENTES",
        "codCidade": 4214151,
        "cidade": "PRINCESA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 4.0,
        "enemMediaGeral": 476.6820068359375,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42013054,
        "nome": "EEB ANTONIO COLONETTI",
        "codCidade": 4207007,
        "cidade": "ICARA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.0,
        "idebAF": 4.099999904632568,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42013119,
        "nome": "EEB ANTONIO G SOBRINHO",
        "codCidade": 4207007,
        "cidade": "ICARA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.800000190734863,
        "idebAF": 4.199999809265137,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42090610,
        "nome": "EEB ANTONIO GONZAGA",
        "codCidade": 4213609,
        "cidade": "PORTO UNIAO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.0,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42012112,
        "nome": "EEB ANTONIO MILANEZ NETTO",
        "codCidade": 4204608,
        "cidade": "CRICIUMA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42053919,
        "nome": "EEB ANTONIO MORANDINI",
        "codCidade": 4204202,
        "cidade": "CHAPECO",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.300000190734863,
        "idebAF": 4.400000095367432,
        "enemMediaGeral": 475.0740051269531,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42069700,
        "nome": "EEB ANTONIO ROCHA ANDRADE",
        "codCidade": 4212502,
        "cidade": "PENHA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.0,
        "idebAF": 3.5,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42083907,
        "nome": "EEB APARICIO JULIO FARRAPO",
        "codCidade": 4219507,
        "cidade": "XANXERE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.699999809265137,
        "idebAF": 3.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42076315,
        "nome": "EEB APOLONIO IRENO CARDOSO",
        "codCidade": 4201950,
        "cidade": "BALNEARIO ARROIO DO SILVA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.900000095367432,
        "idebAF": 3.299999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42047722,
        "nome": "EEB ARABUTA",
        "codCidade": 4201273,
        "cidade": "ARABUTA",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42036941,
        "nome": "EEB ARAUJO FIGUEIREDO",
        "codCidade": 4218905,
        "cidade": "URUBICI",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.400000095367432,
        "idebAF": 2.700000047683716,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42020522,
        "nome": "EEB ARNALDO MOREIRA DOUAT",
        "codCidade": 4209102,
        "cidade": "JOINVILLE",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 7.099999904632568,
        "idebAF": 4.599999904632568,
        "enemMediaGeral": 505.56201171875,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42016959,
        "nome": "EEB ARNOLDO AGENOR ZIMMERMANN",
        "codCidade": 4205902,
        "cidade": "GASPAR",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 5.900000095367432,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 42101093,
        "nome": "EEB ARY DE SOUZA BORGES",
        "codCidade": 4216503,
        "cidade": "SAO JOAQUIM",
        "estado": "SC",
        "regiao": "Sul",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 6.199999809265137,
        "idebAF": 3.799999952316284,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      }
    ]
  
    export default dataSC;