let dataRO = [
  {
    anoCenso: 2013,
    cod: 11033924,
    nome: "CEEJA 6 DE JULHO",
    codCidade: 1100031,
    cidade: "CABIXI",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11025697,
    nome: "CEEJA AIDA FIBIGER DE OLIVEIRA",
    codCidade: 1100049,
    cidade: "CACOAL",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11006757,
    nome: "CEEJA ARIQUEMES",
    codCidade: 1100023,
    cidade: "ARIQUEMES",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11034467,
    nome: "CEEJA CARLOS DRUMOND DE ANDRADE",
    codCidade: 1100056,
    cidade: "CEREJEIRAS",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11028483,
    nome: "CEEJA CEL JORGE TEIXEIRA DE OLIVEIRA",
    codCidade: 1100288,
    cidade: "ROLIM DE MOURA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11011165,
    nome: "CEEJA DE JARU",
    codCidade: 1100114,
    cidade: "JARU",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11029510,
    nome: "CEEJA DOMINGOS VONA",
    codCidade: 1100296,
    cidade: "SANTA LUZIA D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11037237,
    nome: "CEEJA DONIZETE ROMUALDO DA SILVA",
    codCidade: 1100098,
    cidade: "ESPIGAO D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11006013,
    nome: "CEEJA DR CLAUDIO FIALHO",
    codCidade: 1100106,
    cidade: "GUAJARA-MIRIM",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11023023,
    nome: "CEEJA EUCLIDES DA CUNHA",
    codCidade: 1100346,
    cidade: "ALVORADA D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11031441,
    nome: "CEEJA GLICERIA MARIA OLIVEIRA CRIVELLI",
    codCidade: 1100189,
    cidade: "PIMENTA BUENO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11041749,
    nome: "CEEJA PAULO FREIRE",
    codCidade: 1100072,
    cidade: "CORUMBIARA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11007982,
    nome: "CEEJA PAULO FREIRE",
    codCidade: 1100130,
    cidade: "MACHADINHO D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11037601,
    nome: "CEEJA PE MORETTI",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11016230,
    nome: "CEEJA PROF ANTONIO DE ALMEIDA",
    codCidade: 1100155,
    cidade: "OURO PRETO DO OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11046902,
    nome: "CEEJA PROFESSOR EDSON DUARTE LOPES",
    codCidade: 1101302,
    cidade: "MIRANTE DA SERRA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11046856,
    nome: "CEEJA PROFESSORA BARBARA CONCEICAO DOS REIS",
    codCidade: 1100502,
    cidade: "NOVO HORIZONTE DO OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11003839,
    nome: "CEEJA PROFª DORALICE SALES CAVALCANTE",
    codCidade: 1100338,
    cidade: "NOVA MAMORE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11035099,
    nome: "CEEJA TANCREDO DE ALMEIDA NEVES",
    codCidade: 1100064,
    cidade: "COLORADO DO OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11015446,
    nome: "CEEJA TERESA MITSUKO TUSTUMI",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11033193,
    nome: "CEEJA VILHENA",
    codCidade: 1100304,
    cidade: "VILHENA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11042559,
    nome: "CENTRO EDUCACIONAL DE ENSINO FUNDAMENTAL PADRE ENZO MANGANO",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11058803,
    nome: "CENTRO ESTADUAL DE EDUCACAO DE JOVENS E ADULTOS VALE DO GUAPORE",
    codCidade: 1101500,
    cidade: "SERINGUEIRAS",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11034696,
    nome: "E E E F FLORIANO PEIXOTO",
    codCidade: 1100056,
    cidade: "CEREJEIRAS",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 7.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11045906,
    nome: "E E E F FRANCISCO JOSE CHIQUILITO ERSE",
    codCidade: 1100452,
    cidade: "BURITIS",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.400000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11005475,
    nome: "E E E F M CAMPOS SALES",
    codCidade: 1101492,
    cidade: "SAO FRANCISCO DO GUAPORE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.900000095367432,
    idebAF: 4.699999809265137,
    enemMediaGeral: 476.8380126953125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11005041,
    nome: "E E E F M CARLOS DRUMMOND DE ANDRADE",
    codCidade: 1100809,
    cidade: "CANDEIAS DO JAMARI",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.799999952316284,
    enemMediaGeral: 487.8680114746094,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11036486,
    nome: "E E E F M DR OSWALDO PIANA",
    codCidade: 1100072,
    cidade: "CORUMBIARA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 457.8580017089844,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11045914,
    nome: "E E E F M MARIA DE ABREU BIANCO",
    codCidade: 1100452,
    cidade: "BURITIS",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.5,
    idebAF: 4.199999809265137,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11047208,
    nome: "E E E M JOVEM GONCALVES VILELA",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 513.1240234375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11040793,
    nome: "EEEB PROF JOAO BENTO DA COSTA",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 526.6060180664062,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11017899,
    nome: "EEEF 15 DE NOVEMBRO",
    codCidade: 1100254,
    cidade: "PRESIDENTE MEDICI",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11006846,
    nome: "EEEF ALBINA MARCIO SORDI",
    codCidade: 1100023,
    cidade: "ARIQUEMES",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11031549,
    nome: "EEEF ANISIO SERRAO DE CARVALHO",
    codCidade: 1100189,
    cidade: "PIMENTA BUENO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 7.099999904632568,
    idebAF: 6.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11000651,
    nome: "EEEF BOM JESUS",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11031700,
    nome: "EEEF BOM SUCESSO",
    codCidade: 1100189,
    cidade: "PIMENTA BUENO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11003154,
    nome: "EEEF BRANCA DE NEVE",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11005980,
    nome: "EEEF CAP GODOY",
    codCidade: 1100106,
    cidade: "GUAJARA-MIRIM",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11003162,
    nome: "EEEF CASA DE DAVI",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11034610,
    nome: "EEEF CEL JORGE TEIXEIRA DE OLIVEIRA",
    codCidade: 1100056,
    cidade: "CEREJEIRAS",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.599999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11048140,
    nome: "EEEF CUSTODIO GABRIEL FILHO",
    codCidade: 1100403,
    cidade: "ALTO PARAISO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11022450,
    nome: "EEEF DEONILDO CARAGNATTO",
    codCidade: 1100320,
    cidade: "SAO MIGUEL DO GUAPORE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11006048,
    nome: "EEEF DURVALINA ESTILBEM DE OLIVEIRA",
    codCidade: 1100106,
    cidade: "GUAJARA-MIRIM",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.400000095367432,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11024682,
    nome: "EEEF EURIDICE LOPES PEDROSO",
    codCidade: 1100015,
    cidade: "ALTA FLORESTA D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.400000095367432,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11027690,
    nome: "EEEF FERNANDA SOUZA DE PAULA",
    codCidade: 1100098,
    cidade: "ESPIGAO D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.400000095367432,
    idebAF: 5.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11019743,
    nome: "EEEF FLORIZEL LAMEGO FERRARI",
    codCidade: 1101302,
    cidade: "MIRANTE DA SERRA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11026464,
    nome: "EEEF FREI CANECA",
    codCidade: 1100049,
    cidade: "CACOAL",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 5.099999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11032030,
    nome: "EEEF FREI SILVESTRE BIZZOTTO",
    codCidade: 1100189,
    cidade: "PIMENTA BUENO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11035420,
    nome: "EEEF GOVERNADOR ANGELO ANGELIN",
    codCidade: 1100064,
    cidade: "COLORADO DO OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11001178,
    nome: "EEEF HELIO NEVES BOTELHO",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.400000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11034750,
    nome: "EEEF IRMA DULCE",
    codCidade: 1100056,
    cidade: "CEREJEIRAS",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11001240,
    nome: "EEEF JANIO DA SILVA QUADROS",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11014172,
    nome: "EEEF JARDIM DOS MIGRANTES",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.199999809265137,
    idebAF: 5.300000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11027762,
    nome: "EEEF JERRIS ADRIANI TURATTI",
    codCidade: 1100098,
    cidade: "ESPIGAO D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.199999809265137,
    idebAF: 5.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11040882,
    nome: "EEEF JOAO FRANCISCO CORREIA",
    codCidade: 1101104,
    cidade: "ITAPUA DO OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11035544,
    nome: "EEEF JULIETA VILELA VELOZO",
    codCidade: 1100064,
    cidade: "COLORADO DO OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11055600,
    nome: "EEEF LUIZ SOARES DE CASSIA",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11014830,
    nome: "EEEF M PROFª EDILCE DOS SANTOS FREITAS",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 4.400000095367432,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11029099,
    nome: "EEEF MARIA COMANDOLLI LIRA",
    codCidade: 1100288,
    cidade: "ROLIM DE MOURA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11106816,
    nome: "EEEF MARIA DI SANCTI SANTOS",
    codCidade: 1100098,
    cidade: "ESPIGAO D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11033398,
    nome: "EEEF MARIZETI MENDES DE OLIVEIRA",
    codCidade: 1100304,
    cidade: "VILHENA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11023430,
    nome: "EEEF MONTE ALEGRE",
    codCidade: 1100346,
    cidade: "ALVORADA D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11003197,
    nome: "EEEF MUNDO MAGICO",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11001666,
    nome: "EEEF NACOES UNIDAS",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11012382,
    nome: "EEEF NILTON OLIVEIRA DE ARAUJO",
    codCidade: 1100114,
    cidade: "JARU",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11001712,
    nome: "EEEF NOSSA SENHORA DAS GRACAS",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11026839,
    nome: "EEEF NOSSA SRA DO CARMO",
    codCidade: 1100049,
    cidade: "CACOAL",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11014636,
    nome: "EEEF OSVALDO PIANA",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.0,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11006358,
    nome: "EEEF PAUL HARRIS",
    codCidade: 1100106,
    cidade: "GUAJARA-MIRIM",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.699999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11014806,
    nome: "EEEF PROF CARMEM ROCHA BORGES",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.900000095367432,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11002000,
    nome: "EEEF PROF ELOISA BENTES RAMOS",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11000201,
    nome: "EEEF PROF HERBERT DE ALENCAR",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11001992,
    nome: "EEEF PROF ROBERTO DUARTE PIRES",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11017430,
    nome: "EEEF PROFª MARGARIDA CUSTODIO DE SOUZA",
    codCidade: 1100155,
    cidade: "OURO PRETO DO OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11048018,
    nome: "EEEF PROFª MARIA CONCEICAO DE SOUZA",
    codCidade: 1100130,
    cidade: "MACHADINHO D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11022884,
    nome: "EEEF RUI BARBOSA DE OLIVEIRA",
    codCidade: 1101500,
    cidade: "SERINGUEIRAS",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11089806,
    nome: "EEEF SALOMAO JUSTINIANO DE MELGAR",
    codCidade: 1100106,
    cidade: "GUAJARA-MIRIM",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11032774,
    nome: "EEEF SANDOVAL MEIRA",
    codCidade: 1100189,
    cidade: "PIMENTA BUENO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11037598,
    nome: "EEEF SANTA CLARA DE ASSIS",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11000295,
    nome: "EEEF SANTA MARCELINA",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11016019,
    nome: "EEEF SAO FRANCISCO",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11015357,
    nome: "EEEF SAO PEDRO",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11002301,
    nome: "EEEF SAO SEBASTIAO I",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 4.099999904632568,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11002328,
    nome: "EEEF SEBASTIANA LIMA DE OLIVEIRA",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11013273,
    nome: "EEEF SILVIO MICHELUZZI",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 4.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11015411,
    nome: "EEEF TANCREDO DE ALMEIDA NEVES",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 3.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11012943,
    nome: "EEEF TITO LOURENCO DE LIMA",
    codCidade: 1100114,
    cidade: "JARU",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11028394,
    nome: "EEEF VINICIUS DE MORAES",
    codCidade: 1100098,
    cidade: "ESPIGAO D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 4.800000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11020962,
    nome: "EEEF WALDEMAR HIGINO DE SOUZA",
    codCidade: 1101708,
    cidade: "URUPA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 6.300000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11004347,
    nome: "EEEFM 15 DE OUTUBRO",
    codCidade: 1100700,
    cidade: "CAMPO NOVO DE RONDONIA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11035110,
    nome: "EEEFM 16 DE JUNHO",
    codCidade: 1100064,
    cidade: "COLORADO DO OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11017775,
    nome: "EEEFM 28 DE NOVEMBRO",
    codCidade: 1100155,
    cidade: "OURO PRETO DO OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 4.300000190734863,
    enemMediaGeral: 495.98199462890625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11013389,
    nome: "EEEFM 31 DE MARCO",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.599999904632568,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11000384,
    nome: "EEEFM 4 DE JANEIRO",
    codCidade: 1100205,
    cidade: "PORTO VELHO",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.4000000953674316,
    enemMediaGeral: 454.87799072265625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11028424,
    nome: "EEEFM 7 DE SETEMBRO",
    codCidade: 1100098,
    cidade: "ESPIGAO D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 475.6059875488281,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11008008,
    nome: "EEEFM ALBERTO NEPOMUCENO",
    codCidade: 1100130,
    cidade: "MACHADINHO D OESTE",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.300000190734863,
    idebAF: 4.599999904632568,
    enemMediaGeral: 490.1719970703125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11005939,
    nome: "EEEFM ALKINDAR BRASIL DE AROUCA",
    codCidade: 1100106,
    cidade: "GUAJARA-MIRIM",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.200000047683716,
    enemMediaGeral: 468.6239929199219,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11020504,
    nome: "EEEFM ALTAMIR BILLY SOARES",
    codCidade: 1101708,
    cidade: "URUPA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.800000190734863,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11015608,
    nome: "EEEFM ALUIZIO FERREIRA",
    codCidade: 1100122,
    cidade: "JI-PARANA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.0,
    enemMediaGeral: 471.4320068359375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 11033797,
    nome: "EEEFM ALVARES DE AZEVEDO",
    codCidade: 1100304,
    cidade: "VILHENA",
    estado: "RO",
    regiao: "Norte",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 4.599999904632568,
    enemMediaGeral: 481.8160095214844,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataRO;
