let dataMG = [

      {
        "anoCenso": 2013,
        "cod": 31210005,
        "nome": "C INTERESCOLAR E DE LINGUAS",
        "codCidade": 3170107,
        "cidade": "UBERABA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31298913,
        "nome": "CENTRO DE EDUCACAO PROFISSIONAL PAULO VIANA",
        "codCidade": 3168606,
        "cidade": "TEOFILO OTONI",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31218588,
        "nome": "CENTRO DE ORIENTACAO E PESQUISA EM EDUCACAO ESPECIAL",
        "codCidade": 3170107,
        "cidade": "UBERABA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31167860,
        "nome": "CENTRO ESTADUAL DE EDUCACAO ESPECIAL",
        "codCidade": 3170206,
        "cidade": "UBERLANDIA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31232131,
        "nome": "CENTRO ESTADUAL DE EDUCACAO ESPECIAL MARIA DO ROSARIO",
        "codCidade": 3105608,
        "cidade": "BARBACENA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31310778,
        "nome": "CEP CENTRO DE EDUCACAO PROFISSIONAL DE ITAJUBA",
        "codCidade": 3132404,
        "cidade": "ITAJUBA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31054488,
        "nome": "CEP CENTRO EDUCACAO PROFISSIONAL TANCREDO NEVES",
        "codCidade": 3108909,
        "cidade": "BRASOPOLIS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31344656,
        "nome": "CEPCENTRO DE EDUCACAO PROFISSIONAL DE CAXAMBU",
        "codCidade": 3115508,
        "cidade": "CAXAMBU",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31346268,
        "nome": "CESEC AFONSO ARINOS",
        "codCidade": 3104502,
        "cidade": "ARINOS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31138011,
        "nome": "CESEC ALDA POLASTRE",
        "codCidade": 3164704,
        "cidade": "SAO SEBASTIAO DO PARAISO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31118648,
        "nome": "CESEC AUGUSTA RAQUEL DA SILVEIRA",
        "codCidade": 3137106,
        "cidade": "LAGAMAR",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31082091,
        "nome": "CESEC BELINHA ROSA DE JESUS",
        "codCidade": 3152204,
        "cidade": "PORTEIRINHA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31108928,
        "nome": "CESEC CANDIDA PIMENTEL ULHOA",
        "codCidade": 3147006,
        "cidade": "PARACATU",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31008885,
        "nome": "CESEC CLEMENTE DE FARIA",
        "codCidade": 3118601,
        "cidade": "CONTAGEM",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31196703,
        "nome": "CESEC CLORINDA MARTINS TAVARES",
        "codCidade": 3134202,
        "cidade": "ITUIUTABA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31011070,
        "nome": "CESEC CONJUNTO HABITACIONAL CAIEIRAS",
        "codCidade": 3171204,
        "cidade": "VESPASIANO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31010723,
        "nome": "CESEC CONJUNTO HABITACIONAL CRISTINA",
        "codCidade": 3157807,
        "cidade": "SANTA LUZIA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31010901,
        "nome": "CESEC CONJUNTO HABITACIONAL PALMITAL",
        "codCidade": 3157807,
        "cidade": "SANTA LUZIA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31007765,
        "nome": "CESEC DE BETIM",
        "codCidade": 3106705,
        "cidade": "BETIM",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31346322,
        "nome": "CESEC DE BURITIZEIRO",
        "codCidade": 3109402,
        "cidade": "BURITIZEIRO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31351032,
        "nome": "CESEC DE CAPELINHA",
        "codCidade": 3112307,
        "cidade": "CAPELINHA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31346080,
        "nome": "CESEC DE CURVELO",
        "codCidade": 3120904,
        "cidade": "CURVELO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31313700,
        "nome": "CESEC DE FORMIGA",
        "codCidade": 3126109,
        "cidade": "FORMIGA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31043036,
        "nome": "CESEC DE GOVERNADOR VALADARES",
        "codCidade": 3127701,
        "cidade": "GOVERNADOR VALADARES",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31009148,
        "nome": "CESEC DE IBIRITE",
        "codCidade": 3129806,
        "cidade": "IBIRITE",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31351423,
        "nome": "CESEC DE ITABIRINHA",
        "codCidade": 3131802,
        "cidade": "ITABIRINHA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31024244,
        "nome": "CESEC DE ITAMARANDIBA",
        "codCidade": 3132503,
        "cidade": "ITAMARANDIBA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31312126,
        "nome": "CESEC DE JOAIMA",
        "codCidade": 3136009,
        "cidade": "JOAIMA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31103373,
        "nome": "CESEC DE JOAO MONLEVADE",
        "codCidade": 3136207,
        "cidade": "JOAO MONLEVADE",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31346365,
        "nome": "CESEC DE JUSTINOPOLIS",
        "codCidade": 3154606,
        "cidade": "RIBEIRAO DAS NEVES",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31069108,
        "nome": "CESEC DE LIMA DUARTE",
        "codCidade": 3138609,
        "cidade": "LIMA DUARTE",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31081582,
        "nome": "CESEC DE MONTES CLAROS",
        "codCidade": 3143302,
        "cidade": "MONTES CLAROS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31346373,
        "nome": "CESEC DE NOVA PAMPULHA",
        "codCidade": 3154606,
        "cidade": "RIBEIRAO DAS NEVES",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31346195,
        "nome": "CESEC DE NOVA SERRANA",
        "codCidade": 3145208,
        "cidade": "NOVA SERRANA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31010014,
        "nome": "CESEC DE RIBEIRAO DAS NEVES",
        "codCidade": 3154606,
        "cidade": "RIBEIRAO DAS NEVES",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31103721,
        "nome": "CESEC DE RIO PIRACICABA",
        "codCidade": 3155702,
        "cidade": "RIO PIRACICABA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31045144,
        "nome": "CESEC DE SANTA MARIA DE SUACUI",
        "codCidade": 3158201,
        "cidade": "SANTA MARIA DO SUACUI",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31141615,
        "nome": "CESEC DE SETE LAGOAS",
        "codCidade": 3167202,
        "cidade": "SETE LAGOAS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31148199,
        "nome": "CESEC DE TEOFILO OTONI",
        "codCidade": 3168606,
        "cidade": "TEOFILO OTONI",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31313751,
        "nome": "CESEC DE UBERABA",
        "codCidade": 3170107,
        "cidade": "UBERABA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31167835,
        "nome": "CESEC DE UBERLANDIA",
        "codCidade": 3170206,
        "cidade": "UBERLANDIA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31346306,
        "nome": "CESEC DE VESPASIANO",
        "codCidade": 3171204,
        "cidade": "VESPASIANO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31055166,
        "nome": "CESEC DOM JOAO BOSCO",
        "codCidade": 3125101,
        "cidade": "EXTREMA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31035084,
        "nome": "CESEC DONA AFONSINA",
        "codCidade": 3147105,
        "cidade": "PARA DE MINAS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31232653,
        "nome": "CESEC DONA EMILIA LEAL",
        "codCidade": 3147907,
        "cidade": "PASSOS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31199150,
        "nome": "CESEC DORALICE ALVES RODRIGUES",
        "codCidade": 3148103,
        "cidade": "PATROCINIO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31033090,
        "nome": "CESEC DOUTOR FABIO BOTELHO NOTINI",
        "codCidade": 3122306,
        "cidade": "DIVINOPOLIS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31173100,
        "nome": "CESEC DOUTOR TANCREDO DE ALMEIDA NEVES",
        "codCidade": 3139003,
        "cidade": "MACHADO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31259551,
        "nome": "CESEC DR ALTAMIRO SARAIVA",
        "codCidade": 3171303,
        "cidade": "VICOSA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31079626,
        "nome": "CESEC DR CASSIANO ALVES DE OLIVEIRA",
        "codCidade": 3108602,
        "cidade": "BRASILIA DE MINAS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31043664,
        "nome": "CESEC DURCELINO DA SILVA REIS",
        "codCidade": 3128006,
        "cidade": "GUANHAES",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31311952,
        "nome": "CESEC EDIRALVA DE OLIVEIRA ALMEIDA",
        "codCidade": 3148707,
        "cidade": "PEDRA AZUL",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31108367,
        "nome": "CESEC ESMERIA MARIA DO CARMO",
        "codCidade": 3108206,
        "cidade": "BONFINOPOLIS DE MINAS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31024082,
        "nome": "CESEC FRANCISCO BORGES DE SOUZA",
        "codCidade": 3126505,
        "cidade": "FRANCISCO BADARO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31314129,
        "nome": "CESEC GOVERNADOR BIAS FORTES",
        "codCidade": 3143906,
        "cidade": "MURIAE",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31218685,
        "nome": "CESEC HUMBERTO JOSE ELIAS",
        "codCidade": 3125705,
        "cidade": "FELIXLANDIA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31166821,
        "nome": "CESEC JK",
        "codCidade": 3103504,
        "cidade": "ARAGUARI",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31032271,
        "nome": "CESEC JOAO APOLINARIO DE OLIVEIRA",
        "codCidade": 3105103,
        "cidade": "BAMBUI",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31313726,
        "nome": "CESEC JOAO GUIMARAES ROSA",
        "codCidade": 3131307,
        "cidade": "IPATINGA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31194131,
        "nome": "CESEC JOSE BRAS DOS REIS",
        "codCidade": 3145901,
        "cidade": "OURO BRANCO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31109070,
        "nome": "CESEC JULIO MARTINS FERREIRA",
        "codCidade": 3170404,
        "cidade": "UNAI",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31075434,
        "nome": "CESEC JURACY BATISTA CORREA",
        "codCidade": 3139508,
        "cidade": "MANHUMIRIM",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31023850,
        "nome": "CESEC JUSCELINO KUBITSCHEK DE OLIVEIRA",
        "codCidade": 3121605,
        "cidade": "DIAMANTINA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31063533,
        "nome": "CESEC LUIZ ELESBAO LOPES DOS REIS",
        "codCidade": 3170909,
        "cidade": "VARZELANDIA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31311871,
        "nome": "CESEC MAESTRO CARLOS RIBEIRO DA SILVA",
        "codCidade": 3161809,
        "cidade": "SAO GONCALO DO PARA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31310581,
        "nome": "CESEC MARIA CECILIA DE MOURA",
        "codCidade": 3131208,
        "cidade": "IPANEMA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31119601,
        "nome": "CESEC MARIA COELI FRANCO",
        "codCidade": 3162104,
        "cidade": "SAO GOTARDO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31002569,
        "nome": "CESEC MARIA VIEIRA BARBOSA",
        "codCidade": 3106200,
        "cidade": "BELO HORIZONTE",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31082988,
        "nome": "CESEC MAXIMILIANO GAIDZINSKI",
        "codCidade": 3170800,
        "cidade": "VARZEA DA PALMA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31024716,
        "nome": "CESEC MESTRA CHIQUINHA CARVALHAIS",
        "codCidade": 3156007,
        "cidade": "RIO VERMELHO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31032093,
        "nome": "CESEC MONSENHOR GERALDO M VASCONCELOS",
        "codCidade": 3104205,
        "cidade": "ARCOS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31311944,
        "nome": "CESEC NANETE ANTUNES GUIMARAES",
        "codCidade": 3141405,
        "cidade": "MEDINA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31118851,
        "nome": "CESEC ORDALINA VIEIRA RORIZ DA COSTA",
        "codCidade": 3148004,
        "cidade": "PATOS DE MINAS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31080578,
        "nome": "CESEC PADRE CLETO ALTOE",
        "codCidade": 3135100,
        "cidade": "JANAUBA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31055565,
        "nome": "CESEC PADRE MARIO PENOCK",
        "codCidade": 3132404,
        "cidade": "ITAJUBA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31307068,
        "nome": "CESEC POETA MURILO MENDES",
        "codCidade": 3106200,
        "cidade": "BELO HORIZONTE",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31044253,
        "nome": "CESEC PREFEITO JOSE ROMERO DUQUE",
        "codCidade": 3139607,
        "cidade": "MANTENA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31118532,
        "nome": "CESEC PROFESSOR ANTONIO DE DEUS VIEIRA NETO",
        "codCidade": 3114303,
        "cidade": "CARMO DO PARANAIBA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31019275,
        "nome": "CESEC PROFESSOR CELSO SIMOES CALDEIRA",
        "codCidade": 3113404,
        "cidade": "CARATINGA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31054666,
        "nome": "CESEC PROFESSOR CLOTARIO GUILHERME DE MACEDO",
        "codCidade": 3110509,
        "cidade": "CAMANDUCAIA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31075191,
        "nome": "CESEC PROFESSOR HIRAM DE CARVALHO",
        "codCidade": 3139409,
        "cidade": "MANHUACU",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31305219,
        "nome": "CESEC PROFESSOR JOAO DE OLIVEIRA BARBOSA",
        "codCidade": 3111200,
        "cidade": "CAMPO BELO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31134759,
        "nome": "CESEC PROFESSOR JOSE AMERICO DA COSTA",
        "codCidade": 3162500,
        "cidade": "SAO JOAO DEL REI",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31182028,
        "nome": "CESEC PROFESSOR JOSE CARNEIRO DE CASTRO",
        "codCidade": 3169901,
        "cidade": "UBA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31193704,
        "nome": "CESEC PROFESSOR JOSE MARTINS SOBRINHO",
        "codCidade": 3118304,
        "cidade": "CONSELHEIRO LAFAIETE",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31102971,
        "nome": "CESEC PROFESSOR JULIO CARVALHO SOARES",
        "codCidade": 3125903,
        "cidade": "FERROS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31182214,
        "nome": "CESEC PROFESSOR PAULO ROBERTO REIS DE ALMEIDA",
        "codCidade": 3172004,
        "cidade": "VISCONDE DO RIO BRANCO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31103284,
        "nome": "CESEC PROFESSORA DORINHA FERREIRA",
        "codCidade": 3131703,
        "cidade": "ITABIRA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31124214,
        "nome": "CESEC PROFESSORA ELVIRA RODRIGUES PEREIRA",
        "codCidade": 3110301,
        "cidade": "CALDAS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31124931,
        "nome": "CESEC PROFESSORA HELOISA LACERDA",
        "codCidade": 3151800,
        "cidade": "POCOS DE CALDAS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31056537,
        "nome": "CESEC PROFESSORA HERMELINDA TOLEDO",
        "codCidade": 3152501,
        "cidade": "POUSO ALEGRE",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31024503,
        "nome": "CESEC PROFESSORA MARIA GERALDA SILVA SANTOS",
        "codCidade": 3141801,
        "cidade": "MINAS NOVAS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31174203,
        "nome": "CESEC PROFESSORA NOEMIA GOULART FERREIRA",
        "codCidade": 3163706,
        "cidade": "SAO LOURENCO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31055972,
        "nome": "CESEC PROFESSORA PAULITA DE QUEIROZ MIRANDA",
        "codCidade": 3146008,
        "cidade": "OURO FINO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31158429,
        "nome": "CESEC PROFESSORA ROMILDA DINIZ",
        "codCidade": 3111101,
        "cidade": "CAMPINA VERDE",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31171280,
        "nome": "CESEC PROFESSORA SINHA LEITE",
        "codCidade": 3107109,
        "cidade": "BOA ESPERANCA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31129127,
        "nome": "CESEC PROFESSORA VERA PARENTONI",
        "codCidade": 3152105,
        "cidade": "PONTE NOVA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31032425,
        "nome": "CESEC PROFESSORA ZAIRA BATISTA TEIXEIRA",
        "codCidade": 3107406,
        "cidade": "BOM DESPACHO",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31045047,
        "nome": "CESEC PROFETA DANIEL",
        "codCidade": 3156809,
        "cidade": "SABINOPOLIS",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      },
      {
        "anoCenso": 2013,
        "cod": 31184578,
        "nome": "CESEC QUEROBIM FROIS OTONI",
        "codCidade": 3101706,
        "cidade": "ALMENARA",
        "estado": "MG",
        "regiao": "Sudeste",
        "situacaoFuncionamento": 1,
        "dependenciaAdministrativa": 2,
        "idebAI": 0.0,
        "idebAF": 0.0,
        "enemMediaGeral": 0.0,
        "situacaoFuncionamentoTxt": "Em atividade",
        "dependenciaAdministrativaTxt": "Estadual"
      }
    ]
  export default dataMG;