let dataPB = [
  {
    anoCenso: 2013,
    cod: 25092340,
    nome: "CAIC DAMASIO FRANCA",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 483.66400146484375,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25070703,
    nome: "CAIC JOSE JOFILLY",
    codCidade: 2504009,
    cidade: "CAMPINA GRANDE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 0.0,
    enemMediaGeral: 482.77801513671875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25009095,
    nome: "CEJA - CENTRO DE EDUCACAO DE JOVENS ADULTOS MONS VICENTE FREITAS",
    codCidade: 2503704,
    cidade: "CAJAZEIRAS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25018000,
    nome: "CEJA - PADRE DAGMAR NOBRE DE ALMEIDA",
    codCidade: 2516201,
    cidade: "SOUSA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25092499,
    nome: "CEJA PROF ANTONIO SEVERINO DE SOUSA",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25020668,
    nome: "CENT EST ESTUDOS SUPL PROFA SUELY E NOBREGA",
    codCidade: 2510808,
    cidade: "PATOS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25128000,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS",
    codCidade: 2504009,
    cidade: "CAMPINA GRANDE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25089218,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS",
    codCidade: 2509107,
    cidade: "MARI",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25098390,
    nome: "CENTRO DE EDUCACAO DE JOVENS E ADULTOS FUNCIONARIOS II",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25138200,
    nome: "CENTRO ESTADUAL DE ARTE - CEARTE",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25118340,
    nome: "CENTRO FORMADOR DE RECURSOS HUMANOS",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25092871,
    nome: "CENTRO PROFIS DEP ANTONIO CABRAL",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 489.5060119628906,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25068644,
    nome: "E E E F ANTENOR NAVARRO",
    codCidade: 2506301,
    cidade: "GUARABIRA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25067478,
    nome: "E E E F DOUTOR JOAO SOARES",
    codCidade: 2503605,
    cidade: "CAICARA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.9000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25065521,
    nome: "E E E F JOSE AMANCIO RAMALHO",
    codCidade: 2502706,
    cidade: "BORBOREMA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.299999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25042351,
    nome: "E E E F M ANTONIO COELHO DANTAS",
    codCidade: 2510303,
    cidade: "NOVA PALMEIRA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 5.0,
    enemMediaGeral: 490.85400390625,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25093835,
    nome: "E E E F M COMPOSITOR LUIS RAMALHO",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.299999952316284,
    enemMediaGeral: 486.4179992675781,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25065513,
    nome: "E E E F M EFIGENIO LEITE",
    codCidade: 2502706,
    cidade: "BORBOREMA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 422.7080078125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25061402,
    nome: "E E E F M FRANCISCO A SILVA",
    codCidade: 2501203,
    cidade: "AREIAL",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 501.59600830078125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25072129,
    nome: "E E E F M SAO SEBASTIAO",
    codCidade: 2504009,
    cidade: "CAMPINA GRANDE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.0999999046325684,
    enemMediaGeral: 479.0880126953125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25039040,
    nome: "E E E F MONSENHOR PEDRO ANISIO",
    codCidade: 2513406,
    cidade: "SANTA LUZIA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.800000190734863,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25028065,
    nome: "E E E F NOSSA SENHORA DE FATIMA",
    codCidade: 2504405,
    cidade: "CONCEICAO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.799999952316284,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25068652,
    nome: "E E E F PROFESSOR ANTONIO BENVINDO",
    codCidade: 2506301,
    cidade: "GUARABIRA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.9000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25068725,
    nome: "E E E F PROFESSOR EDGARDO JULIO",
    codCidade: 2506301,
    cidade: "GUARABIRA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25059017,
    nome: "E E E F TARGINO PEREIRA CEPES AN1",
    codCidade: 2501005,
    cidade: "ARARUNA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25057146,
    nome: "E E E FUNDAMENTAL E MEDIO AFONSO CAMPOS",
    codCidade: 2512002,
    cidade: "POCINHOS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 499.71600341796875,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25066676,
    nome: "E E E M FRANCISCO PESSOA DE BRITO",
    codCidade: 2500809,
    cidade: "ARACAGI",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25123181,
    nome: "E E N PROF ESTELA MARIS DE MOURA CAMARA",
    codCidade: 2501005,
    cidade: "ARARUNA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25011669,
    nome: "E EST DE CURSO NORMAL EM NIVEL MEDIO SAO JOSE",
    codCidade: 2514503,
    cidade: "SAO JOSE DE PIRANHAS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25081438,
    nome: "EEE F DR JOAO FLORENTINO MEIRA DE VASCONCELOS",
    codCidade: 2506905,
    cidade: "ITABAIANA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 2.0999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25051296,
    nome: "EEE FUNDAMENTAL E MEDIO MELQUIADES TEJO",
    codCidade: 2501708,
    cidade: "BARRA DE SAO MIGUEL",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 459.385986328125,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25036335,
    nome: "EEEB NOSSA SENHORA DO BOM CONSELHO",
    codCidade: 2512309,
    cidade: "PRINCESA ISABEL",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 3.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25024540,
    nome: "EEEEF CONEGO BERNARDO",
    codCidade: 2504801,
    cidade: "COREMAS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.900000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25024531,
    nome: "EEEF 31 DE MARCO",
    codCidade: 2504801,
    cidade: "COREMAS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094955,
    nome: "EEEF ADELAIDE NOVAIS",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25100459,
    nome: "EEEF ALBERTO LUNDGREN",
    codCidade: 2503001,
    cidade: "CAAPORA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.299999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25072340,
    nome: "EEEF ALCEU DO AMOROSO LIMA",
    codCidade: 2504009,
    cidade: "CAMPINA GRANDE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.900000095367432,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25090925,
    nome: "EEEF ALICE AZEVEDO",
    codCidade: 2501807,
    cidade: "BAYEUX",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25099132,
    nome: "EEEF ALINE SILVA MADRUGA",
    codCidade: 2513703,
    cidade: "SANTA RITA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25104330,
    nome: "EEEF ALMIRANTE SALDANHA",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094327,
    nome: "EEEF ALMIRANTE TAMANDARE",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25090933,
    nome: "EEEF ALVARO DE CARVALHO",
    codCidade: 2501807,
    cidade: "BAYEUX",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25064142,
    nome: "EEEF ALVARO MACHADO",
    codCidade: 2501104,
    cidade: "AREIA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.799999952316284,
    idebAF: 2.799999952316284,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25016032,
    nome: "EEEF AMELIA MARIA DA LUZ",
    codCidade: 2512101,
    cidade: "POMBAL",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25000055,
    nome: "EEEF AMERICO MAIA",
    codCidade: 2502003,
    cidade: "BELEM DO BREJO DO CRUZ",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25018078,
    nome: "EEEF ANDRE GADELHA",
    codCidade: 2516201,
    cidade: "SOUSA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.700000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25055852,
    nome: "EEEF ANDRE VIDAL DE NEGREIROS",
    codCidade: 2505105,
    cidade: "CUITE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.099999904632568,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25099183,
    nome: "EEEF ANDRE VIDAL DE NEGREIROS",
    codCidade: 2513703,
    cidade: "SANTA RITA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25054767,
    nome: "EEEF ANESIO DEODONIO MORENO",
    codCidade: 2500908,
    cidade: "ARARA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25090941,
    nome: "EEEF ANITA GARIBALDI",
    codCidade: 2501807,
    cidade: "BAYEUX",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.9000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25012185,
    nome: "EEEF ANTONIO FRANCISCO DUARTE",
    codCidade: 2516805,
    cidade: "TRIUNFO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25000659,
    nome: "EEEF ANTONIO GOMES",
    codCidade: 2502805,
    cidade: "BREJO DO CRUZ",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25006037,
    nome: "EEEF ANTONIO GONCALVES MOREIRA",
    codCidade: 2502201,
    cidade: "BOM JESUS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094351,
    nome: "EEEF ANTONIO PESSOA",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25019228,
    nome: "EEEF ANTONIO TEODORO NETO",
    codCidade: 2516201,
    cidade: "SOUSA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.9000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25072196,
    nome: "EEEF ANTONIO VICENTE",
    codCidade: 2504009,
    cidade: "CAMPINA GRANDE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25062654,
    nome: "EEEF APOLLONIO ZENAYDE",
    codCidade: 2500304,
    cidade: "ALAGOA GRANDE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25111345,
    nome: "EEEF AROLDO CRUZ FILHO",
    codCidade: 2504009,
    cidade: "CAMPINA GRANDE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25091565,
    nome: "EEEF AUGUSTO SEVERO",
    codCidade: 2503209,
    cidade: "CABEDELO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094297,
    nome: "EEEF AZORCERIZ PIRES FERREIRA",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25027980,
    nome: "EEEF BAIRRO SAO JOSE",
    codCidade: 2504405,
    cidade: "CONCEICAO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25100041,
    nome: "EEEF BARAO DO ABIAI",
    codCidade: 2500601,
    cidade: "ALHANDRA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 2.5999999046325684,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25018124,
    nome: "EEEF BATISTA LEITE",
    codCidade: 2516201,
    cidade: "SOUSA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.699999809265137,
    idebAF: 3.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25070304,
    nome: "EEEF BELMIRA ARRUDA ALCOFORADO",
    codCidade: 2515930,
    cidade: "SERTAOZINHO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25057847,
    nome: "EEEF BENEDITA SILVA CARLOS",
    codCidade: 2512705,
    cidade: "REMIGIO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.4000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25018132,
    nome: "EEEF BENTO FREIRE",
    codCidade: 2516201,
    cidade: "SOUSA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094360,
    nome: "EEEF BORGES DA FONSECA",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.400000095367432,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25026410,
    nome: "EEEF BRASIL OITICICA",
    codCidade: 2511301,
    cidade: "PIANCO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25020650,
    nome: "EEEF CAIC DR ROMERO ABDON Q DA NOBREGA",
    codCidade: 2510808,
    cidade: "PATOS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.299999952316284,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25027999,
    nome: "EEEF CALULA LEITE",
    codCidade: 2504405,
    cidade: "CONCEICAO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.9000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25093754,
    nome: "EEEF CAPISTRANO DE ABREU",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094084,
    nome: "EEEF CAPITULINA SATYRO",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25090950,
    nome: "EEEF CARLOS GOMES",
    codCidade: 2501807,
    cidade: "BAYEUX",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25086332,
    nome: "EEEF CASTRO PINTO",
    codCidade: 2507309,
    cidade: "JACARAU",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094378,
    nome: "EEEF CASTRO PINTO",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.9000000953674316,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25007777,
    nome: "EEEF CEL JOAQUIM MATOS",
    codCidade: 2503704,
    cidade: "CAJAZEIRAS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25060384,
    nome: "EEEF CELSO CIRNE",
    codCidade: 2516003,
    cidade: "SOLANEA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.5,
    idebAF: 3.5,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25030620,
    nome: "EEEF CHAGAS SOARES",
    codCidade: 2507002,
    cidade: "ITAPORANGA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.5999999046325684,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25089862,
    nome: "EEEF COM RENATO RIBEIRO COUTINHO",
    codCidade: 2515302,
    cidade: "SAPE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 1.7000000476837158,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25078577,
    nome: "EEEF CONEGO ANTONIO GALDINO",
    codCidade: 2512408,
    cidade: "PUXINANA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.5,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25018221,
    nome: "EEEF CONEGO JOAO CARTAXO ROLIM",
    codCidade: 2516201,
    cidade: "SOUSA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25004972,
    nome: "EEEF CONEGO MANOEL JACOME",
    codCidade: 2500700,
    cidade: "SAO JOAO DO RIO DO PEIXE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25025813,
    nome: "EEEF CONEGO MANOEL OTAVIANO",
    codCidade: 2510402,
    cidade: "OLHO D AGUA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094386,
    nome: "EEEF CORACAO DIVINO",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25020960,
    nome: "EEEF CORIOLANO DE MEDEIROS",
    codCidade: 2510808,
    cidade: "PATOS",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 3.200000047683716,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25069721,
    nome: "EEEF D AMARO BELTRAO",
    codCidade: 2509800,
    cidade: "MULUNGU",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25049640,
    nome: "EEEF DE AMPARO",
    codCidade: 2500734,
    cidade: "AMPARO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25043242,
    nome: "EEEF DE BARAUNA",
    codCidade: 2501534,
    cidade: "BARAUNA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25018256,
    nome: "EEEF DE DEMONSTRACAO DE SOUSA",
    codCidade: 2516201,
    cidade: "SOUSA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25072234,
    nome: "EEEF DE MONTE SANTO",
    codCidade: 2504009,
    cidade: "CAMPINA GRANDE",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 2.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25042335,
    nome: "EEEF DE NOVA PALMEIRA",
    codCidade: 2510303,
    cidade: "NOVA PALMEIRA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25050478,
    nome: "EEEF DE VEREADOR JOAO MARTINIANO DOS SANTOS",
    codCidade: 2501351,
    cidade: "ASSUNCAO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 0.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25034227,
    nome: "EEEF DELMIRO DANTAS",
    codCidade: 2506707,
    cidade: "IMACULADA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.0,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25088793,
    nome: "EEEF DEMETRIO TOLEDO",
    codCidade: 2507903,
    cidade: "JURIPIRANGA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 2.799999952316284,
    idebAF: 3.4000000953674316,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25068660,
    nome: "EEEF DEP GUSTAVO AMORIM",
    codCidade: 2506301,
    cidade: "GUARABIRA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.700000047683716,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25056611,
    nome: "EEEF DEP JOSE PEREIRA",
    codCidade: 2510105,
    cidade: "NOVA FLORESTA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 3.799999952316284,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25118358,
    nome: "EEEF DEPUTADO PEDRO PASCOAL DE OLIVEIRA",
    codCidade: 2507705,
    cidade: "JUAZEIRINHO",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25054163,
    nome: "EEEF DEPUTADO TERTULIANO BRITO",
    codCidade: 2514008,
    cidade: "SAO JOAO DO CARIRI",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.599999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094408,
    nome: "EEEF DES BOTO DE MENEZES",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 5.099999904632568,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
  {
    anoCenso: 2013,
    cod: 25094416,
    nome: "EEEF DES BRAZ BARACUHY",
    codCidade: 2507507,
    cidade: "JOAO PESSOA",
    estado: "PB",
    regiao: "Nordeste",
    situacaoFuncionamento: 1,
    dependenciaAdministrativa: 2,
    idebAI: 4.199999809265137,
    idebAF: 0.0,
    enemMediaGeral: 0.0,
    situacaoFuncionamentoTxt: "Em atividade",
    dependenciaAdministrativaTxt: "Estadual",
  },
];
export default dataPB;
